# Direct Pipeline for English-to-Chinese Dialogue Summarization

This notebook implements a local Direct baseline for English-to-Chinese cross-lingual dialogue summarization.

The Direct pipeline uses a single local small language model agent. The agent reads the original English dialogue and directly generates a concise Chinese summary without using an intermediate English summary, full-dialogue translation, semantic representation, or revision step.

```text
English Dialogue
→ Direct Summarization Agent
→ Final Chinese Summary
```

The pipeline consists of one agent:

```text
Direct Summarization Agent
Input: original English dialogue
Output: concise Chinese summary
```
This setup is used as the simplest cross-lingual summarization baseline. Unlike Translate-then-Summarize, Summarize-then-Translate, or the Semantic-agent pipeline, the Direct pipeline performs the task in a single model call.

The local small language model is served through Ollama. The notebook controls the prompt design, input/output processing, direct summary generation, output inspection, and result saving.

## 0. Local Ollama Setup

Before running this notebook, install Ollama and download the local model used for the Direct baseline.

### Recommended model setup

This notebook uses one local small language model through Ollama.

```bash
ollama pull qwen3.5:27b
```

If qwen3.5:27b is too slow on your machine, you can use a smaller model for testing:

```bash
ollama pull "qwen3.5:9b"
```

```bash
DIRECT_MODEL = "qwen3.5:27b"
```

You can check downloaded models with:

```bash
ollama list
```

You can check currently loaded models with:

```bash
ollama ps
```

If the Ollama server is not running, start it with:

```bash
ollama serve
```

On macOS, opening the Ollama app usually starts the local server automatically.

In [1]:
# Cell 1: Install required Python packages.
# Run this only once if the packages are not installed

!pip install requests pandas tqdm

Requirement already satisfied: requests in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (2.33.1)
Requirement already satisfied: pandas in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (2.3.3)
Requirement already satisfied: tqdm in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from requests) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from requests) (2026.4.22)
Requirement already satisfied: numpy>=1.22.4 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: colorama in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
# Cell 2: Imports and global configuration

import json
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests
import pandas as pd
from tqdm.auto import tqdm

OLLAMA_HOST = "http://localhost:11434"

# Direct model
DIRECT_MODEL = "qwen3.5:27b"  # Change this if your local Ollama model name is different

DEFAULT_TEMPERATURE = 0.2
DEFAULT_NUM_CTX = 8192

# Gold set path
GOLD_SET_PATH = Path(
    "/Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/data/gold_results/gold_set_50_zh_XSAMSum_bart.json"
)

# Output directory
OUTPUT_DIR = Path(
    "/Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results"
)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Output files for Direct baseline
FULL_OUTPUT_PATH = OUTPUT_DIR / "direct_qwen27b_50samples.jsonl"
FINAL_CSV_PATH = OUTPUT_DIR / "direct_qwen27b_50samples.csv"
ERROR_OUTPUT_PATH = OUTPUT_DIR / "direct_qwen27b_50samples_errors.jsonl"

print("Gold set path:", GOLD_SET_PATH)
print("Output directory:", OUTPUT_DIR)
print("Full JSONL output path:", FULL_OUTPUT_PATH)
print("Final CSV output path:", FINAL_CSV_PATH)
print("Error output path:", ERROR_OUTPUT_PATH)

Gold set path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/data/gold_results/gold_set_50_zh_XSAMSum_bart.json
Output directory: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results
Full JSONL output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/direct_qwen27b_50samples.jsonl
Final CSV output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/direct_qwen27b_50samples.csv
Error output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/direct_qwen27b_50samples_errors.jsonl

In [3]:
print(GOLD_SET_PATH.exists())

True

In [4]:
# Cell 3: Check whether Ollama is running

def check_ollama_server() -> bool:
    try:
        response = requests.get(f"{OLLAMA_HOST}/api/tags", timeout=10)
        response.raise_for_status()
        models = response.json().get("models", [])

        print("Ollama server is running.")
        print(f"Downloaded models: {[m.get('name') for m in models]}")

        return True

    except Exception as e:
        print("Could not connect to Ollama.")
        print("Make sure Ollama is installed and running.")
        print("Try running this in Terminal:")
        print("  ollama serve")
        print()
        print("Error:", repr(e))

        return False


_ = check_ollama_server()

Ollama server is running.
Downloaded models: ['gemma3:27b', 'qwen3.5:27b']

In [5]:
# Cell 4: Ollama API helper

def call_ollama(
    model: str,
    prompt: str,
    system: Optional[str] = None,
    temperature: float = DEFAULT_TEMPERATURE,
    num_ctx: int = DEFAULT_NUM_CTX,
    timeout: int = 900,
) -> str:
    """Call Ollama's local chat API and return the assistant content."""

    messages = []

    if system:
        messages.append({"role": "system", "content": system})

    messages.append({"role": "user", "content": prompt})

    payload = {
        "model": model,
        "messages": messages,
        "stream": False,
        "options": {
            "temperature": temperature,
            "num_ctx": num_ctx,
            "num_predict": 1024,
        },
        "think": False,
    }

    response = requests.post(
        f"{OLLAMA_HOST}/api/chat",
        json=payload,
        timeout=timeout,
    )
    response.raise_for_status()

    data = response.json()
    content = data.get("message", {}).get("content", "")

    if content is None:
        content = ""

    return content.strip()

## 1. Prompt Templates

Each agent is defined as:

```text
Agent = model + role-specific prompt + input/output format
```

In the first version, we use a fixed workflow rather than a fully autonomous agent system.

In [6]:
# Cell 5: Direct prompt template
DIRECT_PROMPT = """You are a cross-lingual dialogue summarization agent.

Your task is to read the following English dialogue and directly generate a concise Chinese summary.

Requirements:
- Generate the summary directly in Chinese.
- Do not first write an English summary.
- Do not translate the full dialogue sentence by sentence.
- Summarize only the main information and final outcome.
- Keep the summary concise and faithful to the dialogue.
- Do not add information that is not stated or clearly implied.
- Do not explain your reasoning.
- Output only the final Chinese summary.

STRICT TRANSLATION RULE:
- You MUST translate ALL English proper nouns and speaker names into standard Chinese characters.
- ABSOLUTELY NO English letters or names should appear in the final Chinese summary.

Conciseness: 
- For simple dialogues, prefer 20-50 Chinese characters. 
- For complex dialogues, allow up to 80 Chinese characters.

English dialogue:
{dialogue}

Chinese summary:
"""

In [7]:
# Cell 6: JSONL utility functions

def append_jsonl(record: Dict[str, Any], path: Path) -> None:
    """Append one record to a JSONL file."""
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def load_jsonl(path: Path) -> List[Dict[str, Any]]:
    """Load a JSONL file into a list of dictionaries."""
    if not path.exists():
        return []

    records = []

    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            if line:
                records.append(json.loads(line))

    return records


def load_processed_ids(path: Path) -> set:
    """Return IDs that have already been processed."""
    records = load_jsonl(path)

    return {str(record["id"]) for record in records if "id" in record}

In [8]:
# Cell 7: Direct agent function

def fill_prompt(template: str, replacements: Dict[str, str]) -> str:
    """Replace named placeholders in the prompt."""
    prompt = template

    for key, value in replacements.items():
        prompt = prompt.replace("{" + key + "}", value)

    return prompt


def direct_agent(dialogue: str) -> str:
    """Direct baseline: English dialogue -> Chinese summary."""
    prompt = fill_prompt(
        DIRECT_PROMPT,
        {
            "dialogue": dialogue,
        },
    )

    response = call_ollama(
        model=DIRECT_MODEL,
        prompt=prompt,
        temperature=0.2,
    )

    return response.strip()

## 2. Agent Functions

Each function corresponds to one agent in the pipeline.

In [9]:
# Cell 8: Direct pipeline

def run_direct_pipeline(example: Dict[str, Any]) -> Dict[str, Any]:
    """Run the Direct pipeline: English dialogue -> Chinese summary."""

    sample_id = str(example.get("id", "unknown"))
    dialogue = example["dialogue"]

    reference_english_summary = example.get("reference_english_summary", "")
    reference_chinese_summary = example.get("reference_chinese_summary", "")

    final_chinese_summary = direct_agent(dialogue)

    return {
        "id": sample_id,
        "test_index": example.get("test_index", ""),
        "dialogue": dialogue,
        "reference_english_summary": reference_english_summary,
        "reference_chinese_summary": reference_chinese_summary,
        "final_summary": final_chinese_summary,
        "pipeline": "direct",
        "model": DIRECT_MODEL,
        "num_model_calls": 1,
    }

## 3. Test with Examples

Start with five examples before running the full dataset.  
This is the best way to inspect the intermediate outputs between agents.

In [10]:
# Cell 9: Load first 5 examples from the gold set

def load_examples_from_gold_set(path: Path, n: int = 5) -> List[Dict[str, Any]]:
    """Load the first n examples from the gold-set JSON file."""
    if not path.exists():
        raise FileNotFoundError(f"Gold set not found: {path}")

    with path.open("r", encoding="utf-8") as f:
        raw_data = json.load(f)

    examples = []

    for i, item in enumerate(raw_data[:n]):
        examples.append({
            "id": f"gold_{i+1:05d}",
            "test_index": item.get("test_index", ""),
            "dialogue": item["dialogue"],
            "reference_english_summary": item.get("summary", ""),
            "reference_chinese_summary": item.get("summary_zh", ""),
        })

    return examples


test_data = load_examples_from_gold_set(GOLD_SET_PATH, n=50)

print(f"Loaded {len(test_data)} examples.")
print("First example:")
print(test_data[0])

Loaded 50 examples.
First example:
{'id': 'gold_00001', 'test_index': 23, 'dialogue': "Anne: You were right, he was lying to me :/\nIrene: Oh no, what happened?\nJane: who? that Mark guy?\nAnne: yeah, he told me he's 30, today I saw his passport - he's 40\nIrene: You sure it's so important?\nAnne: he lied to me Irene", 'reference_english_summary': 'Mark lied to Anne about his age. Mark is 40.', 'reference_chinese_summary': '马克向安妮隐瞒了自己的年龄。他40岁了。'}

In [11]:
print(DIRECT_PROMPT)

You are a cross-lingual dialogue summarization agent.

Your task is to read the following English dialogue and directly generate a concise Chinese summary.

Requirements:
- Generate the summary directly in Chinese.
- Do not first write an English summary.
- Do not translate the full dialogue sentence by sentence.
- Summarize only the main information and final outcome.
- Keep the summary concise and faithful to the dialogue.
- Do not add information that is not stated or clearly implied.
- Do not explain your reasoning.
- Output only the final Chinese summary.

STRICT TRANSLATION RULE:
- You MUST translate ALL English proper nouns and speaker names into standard Chinese characters.
- ABSOLUTELY NO English letters or names should appear in the final Chinese summary.

Conciseness:
- For simple dialogues, prefer 20-50 Chinese characters.
- For complex dialogues, allow up to 80 Chinese characters.

English dialogue:
{dialogue}

Chinese summary:

In [12]:
# Cell 10: Run the Direct pipeline for the first example

result = run_direct_pipeline(test_data[4])
result

{'id': 'gold_00005',
 'test_index': 66,
 'dialogue': "Joyce: Check this out!\r\nJoyce: <link>\r\nMichael: That's cheap!\r\nEdson: No way! I'm booking my ticket now!! ",
 'reference_english_summary': 'Edson is booking his ticket now.',
 'reference_chinese_summary': '埃德森正在订票。',
 'final_summary': '乔伊斯分享了一个链接，迈克尔认为价格低廉，埃德森随即决定立即预订机票。',
 'pipeline': 'direct',
 'model': 'qwen3.5:27b',
 'num_model_calls': 1}

In [13]:
# Cell 11: Print Direct pipeline result clearly

def print_direct_result(result: Dict[str, Any]) -> None:
    print("=== Original Dialogue ===")
    print(result["dialogue"])
    print()

    print("=== Direct Chinese Summary ===")
    print(result["final_summary"])
    print()

    print("=== Reference English Summary ===")
    print(result["reference_english_summary"])
    print()

    print("=== Reference Chinese Summary ===")
    print(result["reference_chinese_summary"])
    print()

    print("=== Metadata ===")
    print("Pipeline:", result["pipeline"])
    print("Model:", result["model"])
    print("Model calls:", result["num_model_calls"])


print_direct_result(result)

=== Original Dialogue ===
Joyce: Check this out!
Joyce: <link>
Michael: That's cheap!
Edson: No way! I'm booking my ticket now!!

=== Direct Chinese Summary ===
乔伊斯分享了一个链接，迈克尔认为价格低廉，埃德森随即决定立即预订机票。

=== Reference English Summary ===
Edson is booking his ticket now.

=== Reference Chinese Summary ===
埃德森正在订票。

=== Metadata ===
Pipeline: direct
Model: qwen3.5:27b
Model calls: 1

## 4. Save Results

This saves all intermediate outputs and the final output.

In [14]:
# Cell 12: Reset previous outputs before batch inference

FULL_OUTPUT_PATH.unlink(missing_ok=True)
FINAL_CSV_PATH.unlink(missing_ok=True)
ERROR_OUTPUT_PATH.unlink(missing_ok=True)

print("Previous output files reset.")
print("JSONL output path:", FULL_OUTPUT_PATH)
print("CSV output path:", FINAL_CSV_PATH)
print("Error output path:", ERROR_OUTPUT_PATH)

Previous output files reset.
JSONL output path: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\direct_qwen27b_50samples.jsonl
CSV output path: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\direct_qwen27b_50samples.csv
Error output path: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\direct_qwen27b_50samples_errors.jsonl

## 5. Batch Inference with Checkpointing

This cell processes examples one by one and appends each completed result to `results/agentic_outputs.jsonl`.

If the notebook stops, already processed examples remain saved.

In [ ]:
# Cell 13: Batch inference with Direct pipeline
# Time stamp: 11m 46.1s

MAX_EXAMPLES = 50
SLEEP_SECONDS = 0.2

processed_ids = load_processed_ids(FULL_OUTPUT_PATH)
print(f"Already processed: {len(processed_ids)} examples")

subset = test_data[:MAX_EXAMPLES]

for ex in tqdm(subset, desc="Running Direct pipeline"):
    sample_id = str(ex.get("id", "unknown"))

    if sample_id in processed_ids:
        continue

    try:
        record = run_direct_pipeline(ex)
        append_jsonl(record, FULL_OUTPUT_PATH)
        processed_ids.add(sample_id)
        time.sleep(SLEEP_SECONDS)

    except Exception as e:
        error_record = {
            "id": sample_id,
            "test_index": ex.get("test_index", ""),
            "error": repr(e),
            "dialogue": ex.get("dialogue", ""),
        }

        append_jsonl(error_record, ERROR_OUTPUT_PATH)
        print(f"Error on {sample_id}: {repr(e)}")

print(f"Finished. Outputs saved to: {FULL_OUTPUT_PATH}")

Already processed: 0 examples

Running Direct pipeline:   0%|          | 0/50 [00:00<?, ?it/s]

Finished. Outputs saved to: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\direct_qwen27b_50samples.jsonl

## 6. Export Final Summaries to CSV

This file can be used for ROUGE, BERTScore, OmniScore, or manual analysis.

In [16]:
# Cell 14: Export Direct summaries to CSV

records = load_jsonl(FULL_OUTPUT_PATH)

rows = []

for record in records:
    if "final_summary" not in record:
        continue

    rows.append({
        "id": record.get("id", ""),
        "test_index": record.get("test_index", ""),
        "dialogue": record.get("dialogue", ""),
        "final_summary": record.get("final_summary", ""),
        "reference_english_summary": record.get("reference_english_summary", ""),
        "reference_chinese_summary": record.get("reference_chinese_summary", ""),
        "pipeline": record.get("pipeline", "direct"),
        "model": record.get("model", ""),
        "num_model_calls": record.get("num_model_calls", 1),
    })

df = pd.DataFrame(rows)

if not df.empty:
    df = df.drop_duplicates(subset=["id"], keep="last")

df.to_csv(FINAL_CSV_PATH, index=False, encoding="utf-8-sig")

print(f"Saved final summaries to: {FINAL_CSV_PATH}")
df

Saved final summaries to: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\direct_qwen27b_50samples.csv

,id,test_index,dialogue,final_summary,reference_english_summary,reference_chinese_summary,pipeline,model,num_model_calls
0,gold_00001,23,"Anne: You were right, he was lying to me :/\nI...",安妮发现马克在年龄上欺骗了她，他自称三十岁，实则四十岁。尽管艾琳质疑此事的重要性，安妮仍坚持...,Mark lied to Anne about his age. Mark is 40.,马克向安妮隐瞒了自己的年龄。他40岁了。,direct,qwen3.5:27b,1
1,gold_00002,30,"Mary: hey, im kinda broke, lend me a few box\r...",玛丽因缺钱向卡特借钱，卡特表示自己在火车站，一小时后归还。,Mary ran out of money. Carter is going to lend...,玛丽的钱用完了，卡特打算一小时后借给她一点。,direct,qwen3.5:27b,1
2,gold_00003,39,"Tina: I'll tell you something, this Emirate st...",蒂娜称赞阿联酋航空员工形象出众，并抱怨在机场延误一小时后终于赶上回程航班。阿拉随后告知自己正...,Tina will catch the evening flight back home. ...,蒂娜将乘晚间航班回家。阿拉正在去开会的路上。她会让蒂娜知道事情的进展。,direct,qwen3.5:27b,1
3,gold_00004,65,Ana: You sleeping?\r\nCatherine: Not yet.\r\nA...,安娜和凯瑟琳约定明天一起探望奶奶，并互道晚安。,Ana wants to visit grandma tomorrow. Catherine...,安娜明天想去看望奶奶。凯瑟琳会和她一起去。她起床后会给安娜打电话。,direct,qwen3.5:27b,1
4,gold_00005,66,Joyce: Check this out!\r\nJoyce: <link>\r\nMic...,乔伊斯分享了一个链接，迈克尔认为价格很便宜，埃德森随即决定立即预订机票。,Edson is booking his ticket now.,埃德森正在订票。,direct,qwen3.5:27b,1
5,gold_00006,67,Jane: google maps says it is at least 3h <file...,简因担心路况，提议将见面时间提前至 4 点半，史蒂文同意。两人最终确认在正门见面。,Jane wants to leave at 4.30 instead of 5 becau...,简想4点半就走，而不是等到5点，因为谷歌地图提示300公里的车程至少需要3小时，她不想迟到。...,direct,qwen3.5:27b,1
6,gold_00007,78,"Fiona: Are you free?\r\nTina: Yes, what's up?\...",菲奥娜想为克里斯准备蒂娜的塔塔，但馅料做成了炒蛋。蒂娜答应帮忙，并解释需持续搅拌才能避免失败。,Fiona wants to prepare dinner for Chris. She i...,菲奥娜想为克里斯准备晚餐。她想起了蒂娜做的馅饼。蒂娜会帮她做的。,direct,qwen3.5:27b,1
7,gold_00008,86,Olafur: are we doing anything for New Year's E...,奥拉夫、娜塔莉和佐伊决定新年夜去苏荷区参加蒂凡尼早餐派对，并需尽快购票。,"Nathalie, Olafur and Zoe are planning the New ...",娜塔莉、奥拉维尔和佐伊正在做新年前夜的计划。娜塔莉想要有格调的。但奥拉维尔不喜欢歌剧。他们想...,direct,qwen3.5:27b,1
8,gold_00009,120,"John: wanna go see ""A Star is Born"" on Wed?\r\...",约翰提议周三看电影，琼因忙碌拒绝，但周四有空。两人最终约定周四晚上八点观影，由约翰负责查询场...,"Joan and John are going to watch ""A Star is Bo...",琼和约翰星期四晚上8点左右去看《一个明星的诞生》。,direct,qwen3.5:27b,1
9,gold_00010,137,Peyton: I have been asking you to bring that v...,佩顿催促卡梅伦带回电子游戏，卡梅伦因需在外地多待一周无法回家。佩顿建议通过快递寄送，卡梅伦未...,Peyton is expecting Cameron to bring the video...,佩顿希望卡梅隆能带游戏机过来，但是卡梅隆可能还要再缺席一周。,direct,qwen3.5:27b,1
10,gold_00011,139,Paul: I just came back home\r\nPaul: What a bu...,保罗回家后发现错过了理疗，决定重新预约。艾玛表示将深夜到家，保罗提议为她准备食物，艾玛欣然接受。,Paul forgot about his physiotherapy and he wil...,保罗忘记去做理疗了，得重新预约。艾玛午夜后回家，所以保罗会给她准备一些吃的。,direct,qwen3.5:27b,1
11,gold_00012,192,"Harris: How are U?\r\nLena: Fine, U?\r\nHarris...",哈里斯告知莱娜，其好友青木昨日去世，死因尚不明。哈里斯称数月未与身在密歇根的青木见面，随后因...,"Harris' friend, Aoki, who lives in Michigan, d...",哈里斯的朋友青木住在密歇根州，昨天去世了。哈里斯有几个月没见她了。,direct,qwen3.5:27b,1
12,gold_00013,210,Yaz: Going to slimming club tonight?\r\nMary: ...,雅兹和玛丽今晚将一同前往瘦身俱乐部，尽管她们都因近期饮食放纵而忐忑，但决定面对前烹饪老师的责...,Yaz and Mary are meeting tonight around 6 and ...,亚兹和玛丽今晚6点左右见面，一起去减肥俱乐部。他们估计吃得太多会被骂。,direct,qwen3.5:27b,1
13,gold_00014,211,"Ellie: hey, are you at the university?\r\nAali...",艾莉询问大家是否在大学，卡米尔表示生病。艾莉随后向阿莉雅确认上课地点，阿莉雅告知在二楼342教室。,Ellie's class is in 342 on the second floor.,艾莉的班级在二楼342教室。,direct,qwen3.5:27b,1
14,gold_00015,212,Nathan: <file_video>\r\nAaron: OMG!!! \r\nAaro...,内森分享了一段视频，亚伦对此大笑不止，并调侃视频中的猫表情滑稽，两人还互相发送表情包进行幽默互动。,Nathan and Aaron are discussing a video which ...,内森和亚伦正在讨论内森发来的视频。,direct,qwen3.5:27b,1
15,gold_00016,215,Freddie: What are you watching on Netflix? I'v...,众人讨论在 Netflix 观看的剧集，包括《广告狂人》、《王冠》、《纸牌屋》等，并互相推荐...,"Freddie, Kelly, Jim, Greg, Bob, Mike, Mary, Al...",弗雷迪、凯利、吉姆、格雷格、鲍勃、迈克、玛丽、艾伦和南希正在netflix上观看不同的节目。,direct,qwen3.5:27b,1
16,gold_00017,244,Jones: Hey.\r\nAngelina: Hey.\r\nAngelina: Lon...,琼斯与安吉丽娜久别重逢，双方确认下午在镇上见面，琼斯稍后将致电确认具体地点。,Jones and Angelina will meet in town in the af...,琼斯和安吉丽娜下午会在城里见面。,direct,qwen3.5:27b,1
17,gold_00018,285,Casey: <file_photo>\r\nAmelia: these are so ni...,凯西展示了自己耗时四小时完成的精美美甲，阿梅莉亚和克里斯滕纷纷赞叹并请求她帮忙，但凯西因过程...,Casey got a new nail polish and did her nails ...,凯西买了新指甲油，自己做了指甲。她花了近4个小时，所以她不会帮朋友做指甲，因为耗时太长了。,direct,qwen3.5:27b,1
18,gold_00019,319,Sue: Call me when you get this.\r\nSue: it's i...,苏要求史蒂夫收到信息后立即回电，称此事重要，史蒂夫随即表示正在回拨。,Steve is calling Sue at her request.,史蒂夫正按照苏的要求给她打电话。,direct,qwen3.5:27b,1
19,gold_00020,346,"Timmy: Who do u wanna invite?\r\nGemma: Well, ...",蒂米和杰玛讨论邀请对象，杰玛承认想参加洛娜和米歇尔的婚礼，但不确定能否改变他们的主意。,"Gemma will invite Timmy and his Date, as well ...",杰玛将邀请蒂米和他的约会对象，以及罗娜和米歇尔参加她的婚礼。,direct,qwen3.5:27b,1
20,gold_00021,355,"Ann: Congratulations!!\r\nAnn: You did great, ...",安祝贺苏和朱莉表现出色，提议当晚庆祝，两人欣然同意。,"Ann, Sue and Julie did a great job and they wi...",安、苏和朱莉做得很好，今晚他们会举行一个小小的庆祝活动。,direct,qwen3.5:27b,1
21,gold_00022,367,Steve: hiya the dishwasher has turned up\r\nMu...,史蒂夫告知母亲洗碗机已安装完毕，运行安静且容量为十二人份。母亲对此表示欣慰，两人确认了使用频...,Steve is happy that he got a new dishwasher in...,史蒂夫很高兴他装了一台新的洗碗机。,direct,qwen3.5:27b,1
22,gold_00023,393,Marika: Are you coming today?\r\nLara: Yes!\r\...,玛莉卡询问拉娜今天是否前来，拉娜确认会到，玛莉卡对此表示高兴。,Marika is coming today.,玛丽卡今天会来。,direct,qwen3.5:27b,1
23,gold_00024,417,"Miranda: Hi S, could we cancel tomorrow's meet...",米拉达因工作繁忙请求取消与斯蒂芬妮的明日会议。斯蒂芬妮调侃其过度劳累，米拉达则戏称年轻医生虽...,Miranda can't make her meeting with Stephanie ...,米兰达不能去见斯蒂芬妮，因为她要工作。,direct,qwen3.5:27b,1
24,gold_00025,432,Javier: Hey do you know any tattoo parlors ove...,哈维尔询问英语纹身店，朱迪推荐华沙墨水。得知价格一千后，哈维尔决定回哥伦比亚纹身。,Javier was initially eager to have a tatoo don...,哈维尔最初很想在warsaw ink纹身，但价格太高了。他决定去哥伦比亚做纹身。,direct,qwen3.5:27b,1
25,gold_00026,433,"Sam: You own a really nice hotel, guys 😊\r\nJe...",山姆将于8月15日下午两点抵达杰西卡和迈克尔经营的酒店，双方对此次重逢及住宿安排均表示期待与满意。,Sam appreciates the hotel owned by Jessica and...,山姆很喜欢杰西卡和迈克尔的酒店。他会在8月15日下午2点左右去那里。,direct,qwen3.5:27b,1
26,gold_00027,442,"Terence: What the hell, Danny. You took my mon...",特伦斯误以为丹尼偷了他的钱并加以指责，后发现自己只是将钱放错地方而道歉。丹尼对此感到愤怒，认...,Terence accused Daniel of taking his money. Te...,特伦斯指控丹尼尔偷了他的钱。后来他找到了钱，就向丹尼尔道歉。但是丹尼尔还在生气。,direct,qwen3.5:27b,1
27,gold_00028,499,"Natacha: hi, i can come and pick you up at the...",纳塔莎将去RER接刚抵达的查尔斯。查尔斯预计下午5:30到达，并会在韦西内站给纳塔莎打电话。,Charles has just landed and he will be at RER ...,查尔斯刚刚落地，他会在下午五点半到达rer，娜塔夏会在那里接他。,direct,qwen3.5:27b,1
28,gold_00029,528,Meg: still at school?\r\nAnn: i have extra mat...,梅格询问安是否还在学校，安表示因有额外的数学课，直到晚上七点才能回家。,Ann is still at school. She will be home at 7 ...,安还在学校，她7点会回家，这样她就可以和麦格见面了。,direct,qwen3.5:27b,1
29,gold_00030,532,Pete: What flavour yogurt did you want again? ...,皮特询问珍妮想要什么口味的酸奶，珍妮表示只要梨味，若没有则不要买。皮特答应去查看。,Pete will get a pear yogurt for Jen if they ha...,如果商店里有梨味酸奶， 皮特会给珍买的。,direct,qwen3.5:27b,1
30,gold_00031,536,Christie: how are you after the party?\r\nKati...,克莉丝蒂和凯蒂在派对后都感到疲惫，但她们一致认为派对非常精彩且玩得开心。,Christie and Katie are tired after the party. ...,克里斯蒂和凯蒂在聚会后累了。他们都玩得很开心。,direct,qwen3.5:27b,1
31,gold_00032,537,"Sam: Are you working tomorrow?\r\nCarla: No, i...",山姆和卡拉约定明天下午两点在米恩伍德的一家蛋糕店见面。,Carla has a day off tomorrow. She will meet Sa...,卡拉明天有一天假。她将在下午两点在meanwood的一个咖啡馆和山姆见面。,direct,qwen3.5:27b,1
32,gold_00033,544,Joana: wana play some games?\r\nSandy: what ga...,Joana 提议与 Sandy 玩 Dixit 或卡卡颂游戏，Sandy 表示同意，Joan...,Joana will bring Sandy some games like dixit a...,琼娜将为桑迪带来一些像迪克西特和卡尔卡松这样的游戏。,direct,qwen3.5:27b,1
33,gold_00034,548,Steve: Bought the new Dream Theater album 5 mi...,史蒂夫和罗布都购买了梦剧院的新专辑，并约定稍后交流各自的听后感。,Steve and Rob will talk about new Dream Theate...,史蒂夫和罗伯将在听完后谈论新的梦剧场专辑。,direct,qwen3.5:27b,1
34,gold_00035,551,Peter: Can you send me the link of your beauty...,彼得请求乔伊发送美容店链接，乔伊随即提供并欢迎提问，彼得表示将查看。,Joy sent Peter the link to her beauty shop.,乔伊把她美容店的链接发给了彼得。,direct,qwen3.5:27b,1
35,gold_00036,590,Ethan: who's going to see solstafir?\r\nNoah: ...,伊森告知诺亚、利奥和阿奇，索尔斯特法尔乐队将于11月21日演出。利奥确认参加，阿奇表示不去，...,Ethan and Leo are going to see Sólstafir on 21...,伊森和里奥要在21点11分去见索斯塔弗。诺亚也想去，但他可能得工作到很晚。,direct,qwen3.5:27b,1
36,gold_00037,598,Bradley: haha look a cat invaded the pitch at ...,布拉德利分享了一只猫闯入古迪逊公园球场的视频，朱莉娅称赞其可爱，布拉德利还附上了解说，称这是...,A sweet little black cat got into the pitch du...,在埃弗顿的足球比赛中，一只可爱的小黑猫钻进了球场。,direct,qwen3.5:27b,1
37,gold_00038,605,"Barbara: I'm home already, you can come over\r...",芭芭拉已到家，邀请肖恩和扎克前来。肖恩确认可以带狗并决定留宿，扎克正在路上。,"Barbara, Sean and Zac are meeting at Barbara's...",芭芭拉、肖恩和扎克今晚在芭芭拉家见面。肖恩会把狗带来的，肖恩和扎克会在这里过夜。,direct,qwen3.5:27b,1
38,gold_00039,616,"Jake: dude, I just pulled a TOTW\nJake: my fir...",杰克今年首次抽到TOTW，计划试用后出售以购买更合适的球员。汤姆今年运气不佳未抽到好球员，但...,Jake has got his first TOTW this year. Tom doe...,杰克今年拿到了第一个totw ，汤姆的团队并不出色。,direct,qwen3.5:27b,1
39,gold_00040,621,Phil: Good evening Deana! Many thanks for this...,菲尔收到迪安娜的卡片后，两人确认一副太阳镜不属于迪安娜、凯瑟琳或阿德里安，最终决定由他们共同保管。,Phil received a card from Deana. Constantine w...,菲尔收到了迪安娜的一张卡片，康斯坦丁很开心。菲尔有副墨镜。蒂娜在后面收音机上面找到的。迪安娜...,direct,qwen3.5:27b,1
40,gold_00041,635,Mell: Hi there! How are you doing?\r\nGloria: ...,梅尔与格洛里亚通话，两人决定本周六在梅尔家举办烧烤聚会，并讨论了梅尔扩建露台的计划。她们还庆...,Gloria and Mell plan to have a barbeque at Mel...,格洛丽亚和梅尔计划星期六在梅尔家吃烧烤。他们很高兴，因为泰德的姐姐搬到了苏格兰。梅尔需要格洛...,direct,qwen3.5:27b,1
41,gold_00042,649,Callan: Something's wrong with my Samsung S8.\...,卡兰的三星 S8 因过热出现黑屏，他计划前往商店保修，并确认已备份文件不会丢失。,"Callan's Samsung S8 overheats, so he's going t...",卡伦的三星s8过热了，所以他要去店里修理。,direct,qwen3.5:27b,1
42,gold_00043,676,"Anna: Mum, I have a awful stomachache.\r\nJoan...",安娜因夜间突发腹痛向母亲乔安娜求助。两人推测可能是早餐中的牛奶或香蕉变质所致，但安娜予以否认...,Anna got an awful stomachache at night but she...,安娜夜里胃疼得厉害，但她不知道其中的原因。她的妈妈乔安娜会用新鲜的薄荷叶为她做热茶。,direct,qwen3.5:27b,1
43,gold_00044,678,Sam: Where are you?\nKate: downstairs\nSam: al...,凯特在楼下接待室旁的小房间，发现一位女士正在制作一个带有巨大阴茎、睾丸和巧克力头发的蛋糕，并...,Kate and Jeff are downstairs in a room next to...,凯特和杰夫在楼下接待处旁边的一个房间里。有位女士正在做杏仁蛋糕。,direct,qwen3.5:27b,1
44,gold_00045,690,"Mia: God, he keeps talking about the stupid wa...",米娅、珍妮弗、卡琳和彼得讨论特朗普的民粹策略及其对世界的破坏，认为他虽愚蠢但自信且危险，并决...,"Mia, Jennifer, Karine and Peter do not like Tr...",米亚、珍妮弗、卡琳和彼得不喜欢特朗普。,direct,qwen3.5:27b,1
45,gold_00046,711,Pedro: batman or superman??\r\nAlex: honestly....,佩德罗询问亚历克斯更喜欢蝙蝠侠还是超人，亚历克斯表示两者都不选，他更推崇闪电侠。亚历克斯解释...,Alex prefers the Flash to Barman and Superman ...,阿莱克斯更喜欢闪电侠，因为他的速度。,direct,qwen3.5:27b,1
46,gold_00047,737,Damian: are you downtown?\r\nEthan: yes\r\nEth...,达米安因饥饿请求伊森在市中心买烤肉，伊森虽抱怨其懒惰，最终仍答应帮忙，达米安承诺会改过。,Ethan will buy Damian a kebab. Damian had a ba...,伊森会请达米安吃烤肉串，达米安今天过得很糟糕。,direct,qwen3.5:27b,1
47,gold_00048,767,"Barry: I'm gonna go march in Women's strike, a...",巴里提议参加妇女罢工游行，杰克和戴夫均表示愿意参加，并约定中午在校园集合。,"Barry, Dave, Kelly, and Jake will meet around ...",巴里、戴夫、凯利和杰克将于12点在校园附近集合，参加妇女罢工。,direct,qwen3.5:27b,1
48,gold_00049,799,"Martha: Hey, can I ask you a question?\r\nOphe...",玛莎询问奥菲莉亚个人资料中隐形眼镜的品牌，奥菲莉亚推荐了价格实惠且发货迅速的疯狂隐形眼镜，玛...,Martha likes Ophelia's lenses and wants to buy...,玛莎喜欢奥菲莉娅的眼镜，想买类似的，奥菲莉娅是从crazy lens上买的。,direct,qwen3.5:27b,1
49,gold_00050,800,"Linda: Hi Dad, I want to buy flowers for mum! ...",琳达想给妈妈买花但记不清喜好，父亲迈克尔建议她发送照片。在排除康乃馨后，迈克尔推荐了百合花，...,Linda wants to buy flowers for her mother and ...,琳达想给她妈妈买花，问迈克尔她喜欢哪种花。迈克尔建议琳达买小苍兰。,direct,qwen3.5:27b,1

In [17]:
# Cell 15: Compare generated Chinese summary with the reference Chinese summary

comparison_columns = [
    "id",
    "final_summary",
    "reference_chinese_summary",
]

comparison_df = df[comparison_columns].copy()

comparison_df

,id,final_summary,reference_chinese_summary
0,gold_00001,安妮发现马克在年龄上欺骗了她，他自称三十岁，实则四十岁。尽管艾琳质疑此事的重要性，安妮仍坚持...,马克向安妮隐瞒了自己的年龄。他40岁了。
1,gold_00002,玛丽因缺钱向卡特借钱，卡特表示自己在火车站，一小时后归还。,玛丽的钱用完了，卡特打算一小时后借给她一点。
2,gold_00003,蒂娜称赞阿联酋航空员工形象出众，并抱怨在机场延误一小时后终于赶上回程航班。阿拉随后告知自己正...,蒂娜将乘晚间航班回家。阿拉正在去开会的路上。她会让蒂娜知道事情的进展。
3,gold_00004,安娜和凯瑟琳约定明天一起探望奶奶，并互道晚安。,安娜明天想去看望奶奶。凯瑟琳会和她一起去。她起床后会给安娜打电话。
4,gold_00005,乔伊斯分享了一个链接，迈克尔认为价格很便宜，埃德森随即决定立即预订机票。,埃德森正在订票。
5,gold_00006,简因担心路况，提议将见面时间提前至 4 点半，史蒂文同意。两人最终确认在正门见面。,简想4点半就走，而不是等到5点，因为谷歌地图提示300公里的车程至少需要3小时，她不想迟到。...
6,gold_00007,菲奥娜想为克里斯准备蒂娜的塔塔，但馅料做成了炒蛋。蒂娜答应帮忙，并解释需持续搅拌才能避免失败。,菲奥娜想为克里斯准备晚餐。她想起了蒂娜做的馅饼。蒂娜会帮她做的。
7,gold_00008,奥拉夫、娜塔莉和佐伊决定新年夜去苏荷区参加蒂凡尼早餐派对，并需尽快购票。,娜塔莉、奥拉维尔和佐伊正在做新年前夜的计划。娜塔莉想要有格调的。但奥拉维尔不喜欢歌剧。他们想...
8,gold_00009,约翰提议周三看电影，琼因忙碌拒绝，但周四有空。两人最终约定周四晚上八点观影，由约翰负责查询场...,琼和约翰星期四晚上8点左右去看《一个明星的诞生》。
9,gold_00010,佩顿催促卡梅伦带回电子游戏，卡梅伦因需在外地多待一周无法回家。佩顿建议通过快递寄送，卡梅伦未...,佩顿希望卡梅隆能带游戏机过来，但是卡梅隆可能还要再缺席一周。
10,gold_00011,保罗回家后发现错过了理疗，决定重新预约。艾玛表示将深夜到家，保罗提议为她准备食物，艾玛欣然接受。,保罗忘记去做理疗了，得重新预约。艾玛午夜后回家，所以保罗会给她准备一些吃的。
11,gold_00012,哈里斯告知莱娜，其好友青木昨日去世，死因尚不明。哈里斯称数月未与身在密歇根的青木见面，随后因...,哈里斯的朋友青木住在密歇根州，昨天去世了。哈里斯有几个月没见她了。
12,gold_00013,雅兹和玛丽今晚将一同前往瘦身俱乐部，尽管她们都因近期饮食放纵而忐忑，但决定面对前烹饪老师的责...,亚兹和玛丽今晚6点左右见面，一起去减肥俱乐部。他们估计吃得太多会被骂。
13,gold_00014,艾莉询问大家是否在大学，卡米尔表示生病。艾莉随后向阿莉雅确认上课地点，阿莉雅告知在二楼342教室。,艾莉的班级在二楼342教室。
14,gold_00015,内森分享了一段视频，亚伦对此大笑不止，并调侃视频中的猫表情滑稽，两人还互相发送表情包进行幽默互动。,内森和亚伦正在讨论内森发来的视频。
15,gold_00016,众人讨论在 Netflix 观看的剧集，包括《广告狂人》、《王冠》、《纸牌屋》等，并互相推荐...,弗雷迪、凯利、吉姆、格雷格、鲍勃、迈克、玛丽、艾伦和南希正在netflix上观看不同的节目。
16,gold_00017,琼斯与安吉丽娜久别重逢，双方确认下午在镇上见面，琼斯稍后将致电确认具体地点。,琼斯和安吉丽娜下午会在城里见面。
17,gold_00018,凯西展示了自己耗时四小时完成的精美美甲，阿梅莉亚和克里斯滕纷纷赞叹并请求她帮忙，但凯西因过程...,凯西买了新指甲油，自己做了指甲。她花了近4个小时，所以她不会帮朋友做指甲，因为耗时太长了。
18,gold_00019,苏要求史蒂夫收到信息后立即回电，称此事重要，史蒂夫随即表示正在回拨。,史蒂夫正按照苏的要求给她打电话。
19,gold_00020,蒂米和杰玛讨论邀请对象，杰玛承认想参加洛娜和米歇尔的婚礼，但不确定能否改变他们的主意。,杰玛将邀请蒂米和他的约会对象，以及罗娜和米歇尔参加她的婚礼。
20,gold_00021,安祝贺苏和朱莉表现出色，提议当晚庆祝，两人欣然同意。,安、苏和朱莉做得很好，今晚他们会举行一个小小的庆祝活动。
21,gold_00022,史蒂夫告知母亲洗碗机已安装完毕，运行安静且容量为十二人份。母亲对此表示欣慰，两人确认了使用频...,史蒂夫很高兴他装了一台新的洗碗机。
22,gold_00023,玛莉卡询问拉娜今天是否前来，拉娜确认会到，玛莉卡对此表示高兴。,玛丽卡今天会来。
23,gold_00024,米拉达因工作繁忙请求取消与斯蒂芬妮的明日会议。斯蒂芬妮调侃其过度劳累，米拉达则戏称年轻医生虽...,米兰达不能去见斯蒂芬妮，因为她要工作。
24,gold_00025,哈维尔询问英语纹身店，朱迪推荐华沙墨水。得知价格一千后，哈维尔决定回哥伦比亚纹身。,哈维尔最初很想在warsaw ink纹身，但价格太高了。他决定去哥伦比亚做纹身。
25,gold_00026,山姆将于8月15日下午两点抵达杰西卡和迈克尔经营的酒店，双方对此次重逢及住宿安排均表示期待与满意。,山姆很喜欢杰西卡和迈克尔的酒店。他会在8月15日下午2点左右去那里。
26,gold_00027,特伦斯误以为丹尼偷了他的钱并加以指责，后发现自己只是将钱放错地方而道歉。丹尼对此感到愤怒，认...,特伦斯指控丹尼尔偷了他的钱。后来他找到了钱，就向丹尼尔道歉。但是丹尼尔还在生气。
27,gold_00028,纳塔莎将去RER接刚抵达的查尔斯。查尔斯预计下午5:30到达，并会在韦西内站给纳塔莎打电话。,查尔斯刚刚落地，他会在下午五点半到达rer，娜塔夏会在那里接他。
28,gold_00029,梅格询问安是否还在学校，安表示因有额外的数学课，直到晚上七点才能回家。,安还在学校，她7点会回家，这样她就可以和麦格见面了。
29,gold_00030,皮特询问珍妮想要什么口味的酸奶，珍妮表示只要梨味，若没有则不要买。皮特答应去查看。,如果商店里有梨味酸奶， 皮特会给珍买的。
30,gold_00031,克莉丝蒂和凯蒂在派对后都感到疲惫，但她们一致认为派对非常精彩且玩得开心。,克里斯蒂和凯蒂在聚会后累了。他们都玩得很开心。
31,gold_00032,山姆和卡拉约定明天下午两点在米恩伍德的一家蛋糕店见面。,卡拉明天有一天假。她将在下午两点在meanwood的一个咖啡馆和山姆见面。
32,gold_00033,Joana 提议与 Sandy 玩 Dixit 或卡卡颂游戏，Sandy 表示同意，Joan...,琼娜将为桑迪带来一些像迪克西特和卡尔卡松这样的游戏。
33,gold_00034,史蒂夫和罗布都购买了梦剧院的新专辑，并约定稍后交流各自的听后感。,史蒂夫和罗伯将在听完后谈论新的梦剧场专辑。
34,gold_00035,彼得请求乔伊发送美容店链接，乔伊随即提供并欢迎提问，彼得表示将查看。,乔伊把她美容店的链接发给了彼得。
35,gold_00036,伊森告知诺亚、利奥和阿奇，索尔斯特法尔乐队将于11月21日演出。利奥确认参加，阿奇表示不去，...,伊森和里奥要在21点11分去见索斯塔弗。诺亚也想去，但他可能得工作到很晚。
36,gold_00037,布拉德利分享了一只猫闯入古迪逊公园球场的视频，朱莉娅称赞其可爱，布拉德利还附上了解说，称这是...,在埃弗顿的足球比赛中，一只可爱的小黑猫钻进了球场。
37,gold_00038,芭芭拉已到家，邀请肖恩和扎克前来。肖恩确认可以带狗并决定留宿，扎克正在路上。,芭芭拉、肖恩和扎克今晚在芭芭拉家见面。肖恩会把狗带来的，肖恩和扎克会在这里过夜。
38,gold_00039,杰克今年首次抽到TOTW，计划试用后出售以购买更合适的球员。汤姆今年运气不佳未抽到好球员，但...,杰克今年拿到了第一个totw ，汤姆的团队并不出色。
39,gold_00040,菲尔收到迪安娜的卡片后，两人确认一副太阳镜不属于迪安娜、凯瑟琳或阿德里安，最终决定由他们共同保管。,菲尔收到了迪安娜的一张卡片，康斯坦丁很开心。菲尔有副墨镜。蒂娜在后面收音机上面找到的。迪安娜...
40,gold_00041,梅尔与格洛里亚通话，两人决定本周六在梅尔家举办烧烤聚会，并讨论了梅尔扩建露台的计划。她们还庆...,格洛丽亚和梅尔计划星期六在梅尔家吃烧烤。他们很高兴，因为泰德的姐姐搬到了苏格兰。梅尔需要格洛...
41,gold_00042,卡兰的三星 S8 因过热出现黑屏，他计划前往商店保修，并确认已备份文件不会丢失。,卡伦的三星s8过热了，所以他要去店里修理。
42,gold_00043,安娜因夜间突发腹痛向母亲乔安娜求助。两人推测可能是早餐中的牛奶或香蕉变质所致，但安娜予以否认...,安娜夜里胃疼得厉害，但她不知道其中的原因。她的妈妈乔安娜会用新鲜的薄荷叶为她做热茶。
43,gold_00044,凯特在楼下接待室旁的小房间，发现一位女士正在制作一个带有巨大阴茎、睾丸和巧克力头发的蛋糕，并...,凯特和杰夫在楼下接待处旁边的一个房间里。有位女士正在做杏仁蛋糕。
44,gold_00045,米娅、珍妮弗、卡琳和彼得讨论特朗普的民粹策略及其对世界的破坏，认为他虽愚蠢但自信且危险，并决...,米亚、珍妮弗、卡琳和彼得不喜欢特朗普。
45,gold_00046,佩德罗询问亚历克斯更喜欢蝙蝠侠还是超人，亚历克斯表示两者都不选，他更推崇闪电侠。亚历克斯解释...,阿莱克斯更喜欢闪电侠，因为他的速度。
46,gold_00047,达米安因饥饿请求伊森在市中心买烤肉，伊森虽抱怨其懒惰，最终仍答应帮忙，达米安承诺会改过。,伊森会请达米安吃烤肉串，达米安今天过得很糟糕。
47,gold_00048,巴里提议参加妇女罢工游行，杰克和戴夫均表示愿意参加，并约定中午在校园集合。,巴里、戴夫、凯利和杰克将于12点在校园附近集合，参加妇女罢工。
48,gold_00049,玛莎询问奥菲莉亚个人资料中隐形眼镜的品牌，奥菲莉亚推荐了价格实惠且发货迅速的疯狂隐形眼镜，玛...,玛莎喜欢奥菲莉娅的眼镜，想买类似的，奥菲莉娅是从crazy lens上买的。
49,gold_00050,琳达想给妈妈买花但记不清喜好，父亲迈克尔建议她发送照片。在排除康乃馨后，迈克尔推荐了百合花，...,琳达想给她妈妈买花，问迈克尔她喜欢哪种花。迈克尔建议琳达买小苍兰。

In [18]:
# Cell 16: Inspect Direct outputs

if not df.empty:
    inspection_columns = [
        "id",
        "test_index",
        "dialogue",
        "final_summary",
        "reference_chinese_summary",
    ]

    inspection_df = df[inspection_columns].copy()
    display(inspection_df)
else:
    print("No results found.")

,id,test_index,dialogue,final_summary,reference_chinese_summary
0,gold_00001,23,"Anne: You were right, he was lying to me :/\nI...",安妮发现马克在年龄上欺骗了她，他自称三十岁，实则四十岁。尽管艾琳质疑此事的重要性，安妮仍坚持...,马克向安妮隐瞒了自己的年龄。他40岁了。
1,gold_00002,30,"Mary: hey, im kinda broke, lend me a few box\r...",玛丽因缺钱向卡特借钱，卡特表示自己在火车站，一小时后归还。,玛丽的钱用完了，卡特打算一小时后借给她一点。
2,gold_00003,39,"Tina: I'll tell you something, this Emirate st...",蒂娜称赞阿联酋航空员工形象出众，并抱怨在机场延误一小时后终于赶上回程航班。阿拉随后告知自己正...,蒂娜将乘晚间航班回家。阿拉正在去开会的路上。她会让蒂娜知道事情的进展。
3,gold_00004,65,Ana: You sleeping?\r\nCatherine: Not yet.\r\nA...,安娜和凯瑟琳约定明天一起探望奶奶，并互道晚安。,安娜明天想去看望奶奶。凯瑟琳会和她一起去。她起床后会给安娜打电话。
4,gold_00005,66,Joyce: Check this out!\r\nJoyce: <link>\r\nMic...,乔伊斯分享了一个链接，迈克尔认为价格很便宜，埃德森随即决定立即预订机票。,埃德森正在订票。
5,gold_00006,67,Jane: google maps says it is at least 3h <file...,简因担心路况，提议将见面时间提前至 4 点半，史蒂文同意。两人最终确认在正门见面。,简想4点半就走，而不是等到5点，因为谷歌地图提示300公里的车程至少需要3小时，她不想迟到。...
6,gold_00007,78,"Fiona: Are you free?\r\nTina: Yes, what's up?\...",菲奥娜想为克里斯准备蒂娜的塔塔，但馅料做成了炒蛋。蒂娜答应帮忙，并解释需持续搅拌才能避免失败。,菲奥娜想为克里斯准备晚餐。她想起了蒂娜做的馅饼。蒂娜会帮她做的。
7,gold_00008,86,Olafur: are we doing anything for New Year's E...,奥拉夫、娜塔莉和佐伊决定新年夜去苏荷区参加蒂凡尼早餐派对，并需尽快购票。,娜塔莉、奥拉维尔和佐伊正在做新年前夜的计划。娜塔莉想要有格调的。但奥拉维尔不喜欢歌剧。他们想...
8,gold_00009,120,"John: wanna go see ""A Star is Born"" on Wed?\r\...",约翰提议周三看电影，琼因忙碌拒绝，但周四有空。两人最终约定周四晚上八点观影，由约翰负责查询场...,琼和约翰星期四晚上8点左右去看《一个明星的诞生》。
9,gold_00010,137,Peyton: I have been asking you to bring that v...,佩顿催促卡梅伦带回电子游戏，卡梅伦因需在外地多待一周无法回家。佩顿建议通过快递寄送，卡梅伦未...,佩顿希望卡梅隆能带游戏机过来，但是卡梅隆可能还要再缺席一周。
10,gold_00011,139,Paul: I just came back home\r\nPaul: What a bu...,保罗回家后发现错过了理疗，决定重新预约。艾玛表示将深夜到家，保罗提议为她准备食物，艾玛欣然接受。,保罗忘记去做理疗了，得重新预约。艾玛午夜后回家，所以保罗会给她准备一些吃的。
11,gold_00012,192,"Harris: How are U?\r\nLena: Fine, U?\r\nHarris...",哈里斯告知莱娜，其好友青木昨日去世，死因尚不明。哈里斯称数月未与身在密歇根的青木见面，随后因...,哈里斯的朋友青木住在密歇根州，昨天去世了。哈里斯有几个月没见她了。
12,gold_00013,210,Yaz: Going to slimming club tonight?\r\nMary: ...,雅兹和玛丽今晚将一同前往瘦身俱乐部，尽管她们都因近期饮食放纵而忐忑，但决定面对前烹饪老师的责...,亚兹和玛丽今晚6点左右见面，一起去减肥俱乐部。他们估计吃得太多会被骂。
13,gold_00014,211,"Ellie: hey, are you at the university?\r\nAali...",艾莉询问大家是否在大学，卡米尔表示生病。艾莉随后向阿莉雅确认上课地点，阿莉雅告知在二楼342教室。,艾莉的班级在二楼342教室。
14,gold_00015,212,Nathan: <file_video>\r\nAaron: OMG!!! \r\nAaro...,内森分享了一段视频，亚伦对此大笑不止，并调侃视频中的猫表情滑稽，两人还互相发送表情包进行幽默互动。,内森和亚伦正在讨论内森发来的视频。
15,gold_00016,215,Freddie: What are you watching on Netflix? I'v...,众人讨论在 Netflix 观看的剧集，包括《广告狂人》、《王冠》、《纸牌屋》等，并互相推荐...,弗雷迪、凯利、吉姆、格雷格、鲍勃、迈克、玛丽、艾伦和南希正在netflix上观看不同的节目。
16,gold_00017,244,Jones: Hey.\r\nAngelina: Hey.\r\nAngelina: Lon...,琼斯与安吉丽娜久别重逢，双方确认下午在镇上见面，琼斯稍后将致电确认具体地点。,琼斯和安吉丽娜下午会在城里见面。
17,gold_00018,285,Casey: <file_photo>\r\nAmelia: these are so ni...,凯西展示了自己耗时四小时完成的精美美甲，阿梅莉亚和克里斯滕纷纷赞叹并请求她帮忙，但凯西因过程...,凯西买了新指甲油，自己做了指甲。她花了近4个小时，所以她不会帮朋友做指甲，因为耗时太长了。
18,gold_00019,319,Sue: Call me when you get this.\r\nSue: it's i...,苏要求史蒂夫收到信息后立即回电，称此事重要，史蒂夫随即表示正在回拨。,史蒂夫正按照苏的要求给她打电话。
19,gold_00020,346,"Timmy: Who do u wanna invite?\r\nGemma: Well, ...",蒂米和杰玛讨论邀请对象，杰玛承认想参加洛娜和米歇尔的婚礼，但不确定能否改变他们的主意。,杰玛将邀请蒂米和他的约会对象，以及罗娜和米歇尔参加她的婚礼。
20,gold_00021,355,"Ann: Congratulations!!\r\nAnn: You did great, ...",安祝贺苏和朱莉表现出色，提议当晚庆祝，两人欣然同意。,安、苏和朱莉做得很好，今晚他们会举行一个小小的庆祝活动。
21,gold_00022,367,Steve: hiya the dishwasher has turned up\r\nMu...,史蒂夫告知母亲洗碗机已安装完毕，运行安静且容量为十二人份。母亲对此表示欣慰，两人确认了使用频...,史蒂夫很高兴他装了一台新的洗碗机。
22,gold_00023,393,Marika: Are you coming today?\r\nLara: Yes!\r\...,玛莉卡询问拉娜今天是否前来，拉娜确认会到，玛莉卡对此表示高兴。,玛丽卡今天会来。
23,gold_00024,417,"Miranda: Hi S, could we cancel tomorrow's meet...",米拉达因工作繁忙请求取消与斯蒂芬妮的明日会议。斯蒂芬妮调侃其过度劳累，米拉达则戏称年轻医生虽...,米兰达不能去见斯蒂芬妮，因为她要工作。
24,gold_00025,432,Javier: Hey do you know any tattoo parlors ove...,哈维尔询问英语纹身店，朱迪推荐华沙墨水。得知价格一千后，哈维尔决定回哥伦比亚纹身。,哈维尔最初很想在warsaw ink纹身，但价格太高了。他决定去哥伦比亚做纹身。
25,gold_00026,433,"Sam: You own a really nice hotel, guys 😊\r\nJe...",山姆将于8月15日下午两点抵达杰西卡和迈克尔经营的酒店，双方对此次重逢及住宿安排均表示期待与满意。,山姆很喜欢杰西卡和迈克尔的酒店。他会在8月15日下午2点左右去那里。
26,gold_00027,442,"Terence: What the hell, Danny. You took my mon...",特伦斯误以为丹尼偷了他的钱并加以指责，后发现自己只是将钱放错地方而道歉。丹尼对此感到愤怒，认...,特伦斯指控丹尼尔偷了他的钱。后来他找到了钱，就向丹尼尔道歉。但是丹尼尔还在生气。
27,gold_00028,499,"Natacha: hi, i can come and pick you up at the...",纳塔莎将去RER接刚抵达的查尔斯。查尔斯预计下午5:30到达，并会在韦西内站给纳塔莎打电话。,查尔斯刚刚落地，他会在下午五点半到达rer，娜塔夏会在那里接他。
28,gold_00029,528,Meg: still at school?\r\nAnn: i have extra mat...,梅格询问安是否还在学校，安表示因有额外的数学课，直到晚上七点才能回家。,安还在学校，她7点会回家，这样她就可以和麦格见面了。
29,gold_00030,532,Pete: What flavour yogurt did you want again? ...,皮特询问珍妮想要什么口味的酸奶，珍妮表示只要梨味，若没有则不要买。皮特答应去查看。,如果商店里有梨味酸奶， 皮特会给珍买的。
30,gold_00031,536,Christie: how are you after the party?\r\nKati...,克莉丝蒂和凯蒂在派对后都感到疲惫，但她们一致认为派对非常精彩且玩得开心。,克里斯蒂和凯蒂在聚会后累了。他们都玩得很开心。
31,gold_00032,537,"Sam: Are you working tomorrow?\r\nCarla: No, i...",山姆和卡拉约定明天下午两点在米恩伍德的一家蛋糕店见面。,卡拉明天有一天假。她将在下午两点在meanwood的一个咖啡馆和山姆见面。
32,gold_00033,544,Joana: wana play some games?\r\nSandy: what ga...,Joana 提议与 Sandy 玩 Dixit 或卡卡颂游戏，Sandy 表示同意，Joan...,琼娜将为桑迪带来一些像迪克西特和卡尔卡松这样的游戏。
33,gold_00034,548,Steve: Bought the new Dream Theater album 5 mi...,史蒂夫和罗布都购买了梦剧院的新专辑，并约定稍后交流各自的听后感。,史蒂夫和罗伯将在听完后谈论新的梦剧场专辑。
34,gold_00035,551,Peter: Can you send me the link of your beauty...,彼得请求乔伊发送美容店链接，乔伊随即提供并欢迎提问，彼得表示将查看。,乔伊把她美容店的链接发给了彼得。
35,gold_00036,590,Ethan: who's going to see solstafir?\r\nNoah: ...,伊森告知诺亚、利奥和阿奇，索尔斯特法尔乐队将于11月21日演出。利奥确认参加，阿奇表示不去，...,伊森和里奥要在21点11分去见索斯塔弗。诺亚也想去，但他可能得工作到很晚。
36,gold_00037,598,Bradley: haha look a cat invaded the pitch at ...,布拉德利分享了一只猫闯入古迪逊公园球场的视频，朱莉娅称赞其可爱，布拉德利还附上了解说，称这是...,在埃弗顿的足球比赛中，一只可爱的小黑猫钻进了球场。
37,gold_00038,605,"Barbara: I'm home already, you can come over\r...",芭芭拉已到家，邀请肖恩和扎克前来。肖恩确认可以带狗并决定留宿，扎克正在路上。,芭芭拉、肖恩和扎克今晚在芭芭拉家见面。肖恩会把狗带来的，肖恩和扎克会在这里过夜。
38,gold_00039,616,"Jake: dude, I just pulled a TOTW\nJake: my fir...",杰克今年首次抽到TOTW，计划试用后出售以购买更合适的球员。汤姆今年运气不佳未抽到好球员，但...,杰克今年拿到了第一个totw ，汤姆的团队并不出色。
39,gold_00040,621,Phil: Good evening Deana! Many thanks for this...,菲尔收到迪安娜的卡片后，两人确认一副太阳镜不属于迪安娜、凯瑟琳或阿德里安，最终决定由他们共同保管。,菲尔收到了迪安娜的一张卡片，康斯坦丁很开心。菲尔有副墨镜。蒂娜在后面收音机上面找到的。迪安娜...
40,gold_00041,635,Mell: Hi there! How are you doing?\r\nGloria: ...,梅尔与格洛里亚通话，两人决定本周六在梅尔家举办烧烤聚会，并讨论了梅尔扩建露台的计划。她们还庆...,格洛丽亚和梅尔计划星期六在梅尔家吃烧烤。他们很高兴，因为泰德的姐姐搬到了苏格兰。梅尔需要格洛...
41,gold_00042,649,Callan: Something's wrong with my Samsung S8.\...,卡兰的三星 S8 因过热出现黑屏，他计划前往商店保修，并确认已备份文件不会丢失。,卡伦的三星s8过热了，所以他要去店里修理。
42,gold_00043,676,"Anna: Mum, I have a awful stomachache.\r\nJoan...",安娜因夜间突发腹痛向母亲乔安娜求助。两人推测可能是早餐中的牛奶或香蕉变质所致，但安娜予以否认...,安娜夜里胃疼得厉害，但她不知道其中的原因。她的妈妈乔安娜会用新鲜的薄荷叶为她做热茶。
43,gold_00044,678,Sam: Where are you?\nKate: downstairs\nSam: al...,凯特在楼下接待室旁的小房间，发现一位女士正在制作一个带有巨大阴茎、睾丸和巧克力头发的蛋糕，并...,凯特和杰夫在楼下接待处旁边的一个房间里。有位女士正在做杏仁蛋糕。
44,gold_00045,690,"Mia: God, he keeps talking about the stupid wa...",米娅、珍妮弗、卡琳和彼得讨论特朗普的民粹策略及其对世界的破坏，认为他虽愚蠢但自信且危险，并决...,米亚、珍妮弗、卡琳和彼得不喜欢特朗普。
45,gold_00046,711,Pedro: batman or superman??\r\nAlex: honestly....,佩德罗询问亚历克斯更喜欢蝙蝠侠还是超人，亚历克斯表示两者都不选，他更推崇闪电侠。亚历克斯解释...,阿莱克斯更喜欢闪电侠，因为他的速度。
46,gold_00047,737,Damian: are you downtown?\r\nEthan: yes\r\nEth...,达米安因饥饿请求伊森在市中心买烤肉，伊森虽抱怨其懒惰，最终仍答应帮忙，达米安承诺会改过。,伊森会请达米安吃烤肉串，达米安今天过得很糟糕。
47,gold_00048,767,"Barry: I'm gonna go march in Women's strike, a...",巴里提议参加妇女罢工游行，杰克和戴夫均表示愿意参加，并约定中午在校园集合。,巴里、戴夫、凯利和杰克将于12点在校园附近集合，参加妇女罢工。
48,gold_00049,799,"Martha: Hey, can I ask you a question?\r\nOphe...",玛莎询问奥菲莉亚个人资料中隐形眼镜的品牌，奥菲莉亚推荐了价格实惠且发货迅速的疯狂隐形眼镜，玛...,玛莎喜欢奥菲莉娅的眼镜，想买类似的，奥菲莉娅是从crazy lens上买的。
49,gold_00050,800,"Linda: Hi Dad, I want to buy flowers for mum! ...",琳达想给妈妈买花但记不清喜好，父亲迈克尔建议她发送照片。在排除康乃馨后，迈克尔推荐了百合花，...,琳达想给她妈妈买花，问迈克尔她喜欢哪种花。迈克尔建议琳达买小苍兰。