# Translate-then-Summarize Pipeline for English-to-Chinese Dialogue Summarization

This notebook implements a local Translate-then-Summarize baseline for English-to-Chinese cross-lingual dialogue summarization.

The TS pipeline uses two local small language model agents. Agent 1 reads the original English dialogue and translates the full dialogue into Chinese while preserving speaker names, turn order, placeholders, and dialogue structure. Agent 2 then reads the translated Chinese dialogue and generates a concise Chinese summary.

```text
English Dialogue
→ Agent 1: Chinese Translation Agent
→ Agent 2: Chinese Summarization Agent
→ Final Chinese Summary
```

The pipeline consists of two agents:

```text
Agent 1: Chinese Translation Agent
Input: original English dialogue
Output: translated Chinese dialogue

Agent 2: Chinese Summarization Agent
Input: translated Chinese dialogue from Agent 1
Output: final Chinese summary
```
This setup is used as a Translate-then-Summarize baseline. Unlike the Direct pipeline, TS explicitly creates an intermediate Chinese dialogue translation before summarization. This allows us to inspect whether errors come from the translation stage or the summarization stage.

The local small language model is served through Ollama. The notebook controls the prompt design, agent workflow, input/output processing, intermediate output inspection, and result saving.

## 0. Local Ollama Setup

Before running this notebook, install Ollama and download the local model used for the Translate-then-Summarize baseline.

### Recommended model setup

This notebook uses one local small language model through Ollama for both agents:

- Agent 1: Chinese Translation Agent
- Agent 2: Chinese Summarization Agent

```bash
ollama pull qwen3.5:27b
```

If qwen3.5:27b is too slow on your machine, you can use a smaller model for testing:

```bash
ollama pull "qwen3.5:9b"
```

Make sure the model names in the notebook match the models installed in Ollama:

```bash
TRANSLATION_MODEL = "qwen3.5:27b"
SUMMARIZATION_MODEL = "qwen3.5:27b"
```

You can check downloaded models with:

```bash
ollama list
```

You can check currently loaded models with:

```bash
ollama ps
```

If the Ollama server is not running, start it with:

```bash
ollama serve
```

On macOS, opening the Ollama app usually starts the local server automatically.

In [1]:
# Cell 1: Install required Python packages.
# Run this only once if the packages are not installed

!pip install requests pandas tqdm

Requirement already satisfied: requests in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (2.33.1)
Requirement already satisfied: pandas in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (2.3.3)
Requirement already satisfied: tqdm in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from requests) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from requests) (2026.4.22)
Requirement already satisfied: numpy>=1.22.4 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: colorama in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
# current working path check
import os
from pathlib import Path

PROJECT_ROOT = Path("/Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization")
os.chdir(PROJECT_ROOT)

print("Current working directory:", Path.cwd())

Current working directory: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization

In [1]:
# Cell 2: Imports and global configuration

import json
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests
import pandas as pd
from tqdm.auto import tqdm

OLLAMA_HOST = "http://localhost:11434"

# TS models
TRANSLATION_MODEL = "qwen3.5:27b"
SUMMARIZATION_MODEL = "qwen3.5:27b"

DEFAULT_TEMPERATURE = 0.2
DEFAULT_NUM_CTX = 8192

# Gold set path
GOLD_SET_PATH = Path(
    "/Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/data/gold_results/gold_set_50_zh_XSAMSum_bart.json"
)

# Output directory
OUTPUT_DIR = Path(
    "/Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results"
)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Output files for TS baseline
FULL_OUTPUT_PATH = OUTPUT_DIR / "ts_qwen27b_50samples.jsonl"
FINAL_CSV_PATH = OUTPUT_DIR / "ts_qwen27b_50samples.csv"
ERROR_OUTPUT_PATH = OUTPUT_DIR / "ts_qwen27b_50samples_errors.jsonl"

print("Gold set path:", GOLD_SET_PATH)
print("Output directory:", OUTPUT_DIR)
print("Full JSONL output path:", FULL_OUTPUT_PATH)
print("Final CSV output path:", FINAL_CSV_PATH)
print("Error output path:", ERROR_OUTPUT_PATH)

Gold set path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/data/gold_results/gold_set_50_zh_XSAMSum_bart.json
Output directory: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results
Full JSONL output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/ts_qwen27b_50samples.jsonl
Final CSV output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/ts_qwen27b_50samples.csv
Error output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/ts_qwen27b_50samples_errors.jsonl

In [3]:
print(GOLD_SET_PATH.exists())

True

In [4]:
# Cell 3: Check whether Ollama is running

def check_ollama_server() -> bool:
    try:
        response = requests.get(f"{OLLAMA_HOST}/api/tags", timeout=10)
        response.raise_for_status()
        models = response.json().get("models", [])

        print("Ollama server is running.")
        print(f"Downloaded models: {[m.get('name') for m in models]}")

        return True

    except Exception as e:
        print("Could not connect to Ollama.")
        print("Make sure Ollama is installed and running.")
        print("Try running this in Terminal:")
        print("  ollama serve")
        print()
        print("Error:", repr(e))

        return False


_ = check_ollama_server()

Ollama server is running.
Downloaded models: ['gemma3:27b', 'qwen3.5:27b']

In [5]:
# Cell 4: Ollama API helper

def call_ollama(
    model: str,
    prompt: str,
    system: Optional[str] = None,
    temperature: float = DEFAULT_TEMPERATURE,
    num_ctx: int = DEFAULT_NUM_CTX,
    timeout: int = 900,
) -> str:
    """Call Ollama's local chat API and return the assistant content."""

    messages = []

    if system:
        messages.append({"role": "system", "content": system})

    messages.append({"role": "user", "content": prompt})

    payload = {
        "model": model,
        "messages": messages,
        "stream": False,
        "options": {
            "temperature": temperature,
            "num_ctx": num_ctx,
            "num_predict": 1024,
        },
        "think": False,
    }

    response = requests.post(
        f"{OLLAMA_HOST}/api/chat",
        json=payload,
        timeout=timeout,
    )
    response.raise_for_status()

    data = response.json()
    content = data.get("message", {}).get("content", "")

    if content is None:
        content = ""

    return content.strip()

## 1. Prompt Templates

Each agent is defined as:

```text
Agent = model + role-specific prompt + input/output format
```

In the first version, we use a fixed workflow rather than a fully autonomous agent system.

In [6]:
# Cell 5: TS prompt templates

CHINESE_TRANSLATION_PROMPT = """You are a dialogue translation agent.

Your task is to translate the following English dialogue into Chinese.

Requirements:
- Translate the full dialogue into Chinese.
- Preserve the speaker names.
- Preserve the dialogue structure and turn order.
- Preserve placeholders such as <file_photo>, <file_other>, <location>, or emojis if they appear.
- Do not summarize the dialogue.
- Do not omit any important information.
- Do not add information that is not in the original dialogue.
- Output only the translated Chinese dialogue.

STRICT TRANSLATION RULE:
- You MUST translate ALL English proper nouns and speaker names into standard Chinese characters.
- ABSOLUTELY NO English letters or names should appear in the final Chinese summary.

English dialogue:
{dialogue}

Chinese translation:
"""


CHINESE_SUMMARIZATION_PROMPT = """You are a Chinese dialogue summarization agent.

Your task is to read the translated Chinese dialogue and generate a concise Chinese summary.

Requirements:
- Summarize the main information in the dialogue.
- Write the summary in Chinese.
- Keep the summary concise and faithful to the dialogue.
- Do not add information that is not stated or clearly implied.
- Do not explain your reasoning.
- Output only the final Chinese summary.

Conciseness: 
- For simple dialogues, prefer 20-50 Chinese characters. 
- For complex dialogues, allow up to 80 Chinese characters.

Chinese dialogue:
{translated_dialogue}

Chinese summary:
"""

In [7]:
# Cell 6: JSONL utility functions

def append_jsonl(record: Dict[str, Any], path: Path) -> None:
    """Append one record to a JSONL file."""
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def load_jsonl(path: Path) -> List[Dict[str, Any]]:
    """Load a JSONL file into a list of dictionaries."""
    if not path.exists():
        return []

    records = []

    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            if line:
                records.append(json.loads(line))

    return records


def load_processed_ids(path: Path) -> set:
    """Return IDs that have already been processed."""
    records = load_jsonl(path)

    return {str(record["id"]) for record in records if "id" in record}

In [8]:
# Cell 7: TS agent functions

def fill_prompt(template: str, replacements: Dict[str, str]) -> str:
    """Replace named placeholders in the prompt."""
    prompt = template

    for key, value in replacements.items():
        prompt = prompt.replace("{" + key + "}", value)

    return prompt


def chinese_translation_agent(dialogue: str) -> str:
    """Agent 1: English dialogue -> translated Chinese dialogue."""
    prompt = fill_prompt(
        CHINESE_TRANSLATION_PROMPT,
        {
            "dialogue": dialogue,
        },
    )

    response = call_ollama(
        model=TRANSLATION_MODEL,
        prompt=prompt,
        temperature=0.2,
    )

    return response.strip()


def chinese_summarization_agent(translated_dialogue: str) -> str:
    """Agent 2: translated Chinese dialogue -> Chinese summary."""
    prompt = fill_prompt(
        CHINESE_SUMMARIZATION_PROMPT,
        {
            "translated_dialogue": translated_dialogue,
        },
    )

    response = call_ollama(
        model=SUMMARIZATION_MODEL,
        prompt=prompt,
        temperature=0.2,
    )

    return response.strip()

## 2. Agent Functions

Each function corresponds to one agent in the pipeline.

In [9]:
# Cell 8: TS pipeline

def run_ts_pipeline(example: Dict[str, Any], verbose: bool = True) -> Dict[str, Any]:
    """Run the Translate-then-Summarize pipeline."""

    sample_id = str(example.get("id", "unknown"))
    dialogue = example["dialogue"]

    reference_english_summary = example.get("reference_english_summary", "")
    reference_chinese_summary = example.get("reference_chinese_summary", "")

    # Agent 1: English dialogue -> translated Chinese dialogue
    translated_dialogue = chinese_translation_agent(dialogue)

    if verbose:
        print("\n" + "=" * 80)
        print(f"Sample ID: {sample_id}")
        print("=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===")
        print(translated_dialogue)
        print("=" * 80 + "\n")

    # Agent 2: translated Chinese dialogue -> Chinese summary
    final_chinese_summary = chinese_summarization_agent(translated_dialogue)

    if verbose:
        print("=== Agent 2 Final Output: Chinese Summary ===")
        print(final_chinese_summary)
        print("=" * 80 + "\n")

    return {
        "id": sample_id,
        "test_index": example.get("test_index", ""),
        "dialogue": dialogue,

        # Intermediate output from Agent 1
        "translated_dialogue": translated_dialogue,

        # Final output from Agent 2
        "final_summary": final_chinese_summary,

        # References
        "reference_english_summary": reference_english_summary,
        "reference_chinese_summary": reference_chinese_summary,

        # Metadata
        "pipeline": "translate_then_summarize",
        "translation_model": TRANSLATION_MODEL,
        "summarization_model": SUMMARIZATION_MODEL,
        "num_model_calls": 2,
    }

## 3. Test with Examples

Start with five examples before running the full dataset.  
This is the best way to inspect whether errors come from the English summarization stage or the Chinese translation stage.

In [10]:
# Cell 9: Load first 5 examples from the gold set

def load_examples_from_gold_set(path: Path, n: int = 5) -> List[Dict[str, Any]]:
    """Load the first n examples from the gold-set JSON file."""
    if not path.exists():
        raise FileNotFoundError(f"Gold set not found: {path}")

    with path.open("r", encoding="utf-8") as f:
        raw_data = json.load(f)

    examples = []

    for i, item in enumerate(raw_data[:n]):
        examples.append({
            "id": f"gold_{i+1:05d}",
            "test_index": item.get("test_index", ""),
            "dialogue": item["dialogue"],
            "reference_english_summary": item.get("summary", ""),
            "reference_chinese_summary": item.get("summary_zh", ""),
        })

    return examples


test_data = load_examples_from_gold_set(GOLD_SET_PATH, n=50)

print(f"Loaded {len(test_data)} examples.")
print("First example:")
print(test_data[0])

Loaded 50 examples.
First example:
{'id': 'gold_00001', 'test_index': 23, 'dialogue': "Anne: You were right, he was lying to me :/\nIrene: Oh no, what happened?\nJane: who? that Mark guy?\nAnne: yeah, he told me he's 30, today I saw his passport - he's 40\nIrene: You sure it's so important?\nAnne: he lied to me Irene", 'reference_english_summary': 'Mark lied to Anne about his age. Mark is 40.', 'reference_chinese_summary': '马克向安妮隐瞒了自己的年龄。他40岁了。'}

In [11]:
# Cell 10: Run the TS pipeline for the first example

result = run_ts_pipeline(test_data[4], verbose=True)
result

================================================================================
Sample ID: gold_00005
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
乔伊斯：快来看这个！
乔伊斯：<link>
迈克尔：太便宜了！
埃德森：不可能！我现在就订票！！
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
乔伊斯分享了一个链接，迈克尔感叹价格太便宜，埃德森则立即决定订票。
================================================================================

{'id': 'gold_00005',
 'test_index': 66,
 'dialogue': "Joyce: Check this out!\r\nJoyce: <link>\r\nMichael: That's cheap!\r\nEdson: No way! I'm booking my ticket now!! ",
 'translated_dialogue': '乔伊斯：快来看这个！\n乔伊斯：<link>\n迈克尔：太便宜了！\n埃德森：不可能！我现在就订票！！',
 'final_summary': '乔伊斯分享了一个链接，迈克尔感叹价格太便宜，埃德森则立即决定订票。',
 'reference_english_summary': 'Edson is booking his ticket now.',
 'reference_chinese_summary': '埃德森正在订票。',
 'pipeline': 'translate_then_summarize',
 'translation_model': 'qwen3.5:27b',
 'summarization_model': 'qwen3.5:27b',
 'num_model_calls': 2}

In [12]:
# Cell 11: Print TS pipeline result clearly

def print_ts_result(result: Dict[str, Any]) -> None:
    print("=== Original Dialogue ===")
    print(result["dialogue"])
    print()

    print("=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===")
    print(result["translated_dialogue"])
    print()

    print("=== Agent 2 Final Output: Chinese Summary ===")
    print(result["final_summary"])
    print()

    print("=== Reference English Summary ===")
    print(result["reference_english_summary"])
    print()

    print("=== Reference Chinese Summary ===")
    print(result["reference_chinese_summary"])
    print()

    print("=== Metadata ===")
    print("Pipeline:", result["pipeline"])
    print("Translation model:", result["translation_model"])
    print("Summarization model:", result["summarization_model"])
    print("Model calls:", result["num_model_calls"])


print_ts_result(result)

=== Original Dialogue ===
Joyce: Check this out!
Joyce: <link>
Michael: That's cheap!
Edson: No way! I'm booking my ticket now!!

=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
乔伊斯：快来看这个！
乔伊斯：<link>
迈克尔：太便宜了！
埃德森：不可能！我现在就订票！！

=== Agent 2 Final Output: Chinese Summary ===
乔伊斯分享了一个链接，迈克尔感叹价格太便宜，埃德森则立即决定订票。

=== Reference English Summary ===
Edson is booking his ticket now.

=== Reference Chinese Summary ===
埃德森正在订票。

=== Metadata ===
Pipeline: translate_then_summarize
Translation model: qwen3.5:27b
Summarization model: qwen3.5:27b
Model calls: 2

## 4. Save Results

This saves the intermediate English summary and the final Chinese summary.

In [13]:
# Cell 12: Reset previous outputs before batch inference

FULL_OUTPUT_PATH.unlink(missing_ok=True)
FINAL_CSV_PATH.unlink(missing_ok=True)
ERROR_OUTPUT_PATH.unlink(missing_ok=True)

print("Previous output files reset.")
print("JSONL output path:", FULL_OUTPUT_PATH)
print("CSV output path:", FINAL_CSV_PATH)
print("Error output path:", ERROR_OUTPUT_PATH)

Previous output files reset.
JSONL output path: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\ts_qwen27b_50samples.jsonl
CSV output path: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\ts_qwen27b_50samples.csv
Error output path: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\ts_qwen27b_50samples_errors.jsonl

## 5. Batch Inference with Checkpointing

This cell processes examples one by one and appends each completed ST result to the JSONL output file.

If the notebook stops, already processed examples remain saved.

In [14]:
# Cell 13: Batch inference with TS pipeline
# Time stamp: 2m 51.7s

MAX_EXAMPLES = 50
SLEEP_SECONDS = 0.2

processed_ids = load_processed_ids(FULL_OUTPUT_PATH)
print(f"Already processed: {len(processed_ids)} examples")

subset = test_data[:MAX_EXAMPLES]

for ex in tqdm(subset, desc="Running TS pipeline"):
    sample_id = str(ex.get("id", "unknown"))

    if sample_id in processed_ids:
        print(f"Skipping already processed sample: {sample_id}")
        continue

    try:
        record = run_ts_pipeline(ex, verbose=True)

        append_jsonl(record, FULL_OUTPUT_PATH)
        processed_ids.add(sample_id)

        time.sleep(SLEEP_SECONDS)

    except Exception as e:
        error_record = {
            "id": sample_id,
            "test_index": ex.get("test_index", ""),
            "error": repr(e),
            "dialogue": ex.get("dialogue", ""),
        }

        append_jsonl(error_record, ERROR_OUTPUT_PATH)
        print(f"Error on {sample_id}: {repr(e)}")

print(f"Finished. Outputs saved to: {FULL_OUTPUT_PATH}")

Already processed: 0 examples

Running TS pipeline:   0%|          | 0/50 [00:00<?, ?it/s]

================================================================================
Sample ID: gold_00001
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
安妮：你是对的，他对我撒谎了 :/
艾琳：哦不，发生什么事了？
简：谁？那个马克吗？
安妮：是的，他告诉我他三十岁，今天我看到了他的护照——他四十岁。
艾琳：你确定这很重要吗？
安妮：他对我撒谎了，艾琳。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
安妮发现马克在年龄上对她撒谎，他自称三十岁，但护照显示实际为四十岁。尽管艾琳质疑此事的重要性，安妮仍坚持认为被欺骗很严重。
================================================================================


================================================================================
Sample ID: gold_00002
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
玛丽：嘿，我手头有点紧，借我几盒吧。
卡特：好的，给我一小时，我在火车站。
玛丽：太好了，谢谢。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
玛丽因手头紧向卡特借几盒，卡特答应一小时后在火车站交付，玛丽表示感谢。
================================================================================


================================================================================
Sample ID: gold_00003
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
蒂娜：我告诉你，这家阿联酋航空的机组人员看起来太棒了，就像电影明星一样。
阿拉：哦，是的，我知道，这是有目的的。
阿拉：本来就应该这样。
阿拉：他们非常注重形象。
蒂娜：看起来不错，看着真让人愉悦。
蒂娜：我在机场可倒霉了，他们在飞机上把我们滞留了一个小时，最后我才赶上回家的晚班航班。
蒂娜：你能想象吗？
蒂娜：而且你知道吗，这次我们遇到了一位特别健谈的飞行员 :-)
阿拉：哦，可怜的你。
阿拉：哼。
阿拉：我现在正要去开会。
蒂娜：就是那个会议吗？
阿拉：是的，祝你好运。
蒂娜：当然，告诉我结果如何。
阿拉：好的，亲爱的，保持联系。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
蒂娜称赞阿联酋航空机组形象，但抱怨机场滞留及航班延误。阿拉表示同情，随后告知要去开会，两人约定保持联系。
================================================================================


================================================================================
Sample ID: gold_00004
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
安娜：你睡着了吗？
凯瑟琳：还没。
安娜：明天想去探望奶奶吗？我想她了。
凯瑟琳：好啊，那太好了 :) 我醒来后给你打电话。
安娜：好的 :) 睡个好觉，晚安。
凯瑟琳：晚安，你也是。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
安娜提议明天探望奶奶，凯瑟琳欣然同意，并约定醒来后联系，随后两人互道晚安。
================================================================================


================================================================================
Sample ID: gold_00005
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
乔伊斯：快看看这个！
乔伊斯：<link>
迈克尔：太便宜了！
埃德森：不可能！我现在就订票！！
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
乔伊斯分享了一个链接，迈克尔感叹价格太便宜，埃德森则决定立即订票。
================================================================================


================================================================================
Sample ID: gold_00006
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
简：谷歌地图显示至少需要 3 小时 <file_other>
史蒂文：我以前 2 小时就到了，相信我 :D
简：但路程快有 300 公里了……
史蒂文：路是新修的，我们肯定能赶上 ^^
简：我不想太紧张，我们改成 4 点半见面，5 点太晚了，好吗？
史蒂文：好吧，如果你真的这么想，我们可以 4 点半见。
简：谢谢！
简：我在主入口等，还是别的地方？
史蒂文：主入口对我来说很好;-)
史蒂文：回头见
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
简提议将见面时间改为 4 点半，史蒂文同意。两人确认将在主入口见面。
================================================================================


================================================================================
Sample ID: gold_00007
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
菲奥娜：你有空吗？
蒂娜：有空，怎么了？
菲奥娜：我正在为克里斯准备一顿丰盛的晚餐，我在想也许可以试试你做的这个挞 :)
蒂娜：我很荣幸！
菲奥娜：嗯，它确实很好吃 :) 能帮我一起做吗？
蒂娜：当然！这并不难。你准备好什么了吗？
菲奥娜：我得承认，我已经买了挞皮……
蒂娜：哦，好吧 :P 有点可惜，不过现在说这些也晚了。
菲奥娜：我试过做一次馅料，结果做成了柠檬炒蛋……
蒂娜：这种事常发生，别担心。关键在于，一旦开始加鸡蛋，就不能停止搅拌，否则最后就会变成炒蛋。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
菲奥娜邀请蒂娜帮忙为克里斯做挞。菲奥娜已买好挞皮，但馅料做成了柠檬炒蛋。蒂娜安慰她，并指出加鸡蛋时需不停搅拌才能避免失败。
================================================================================


================================================================================
Sample ID: gold_00008
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
奥拉夫：我们除夕夜有什么安排吗？
娜塔莉：我在想一些高雅的活动，比如歌剧之类的。
佐伊：要花多少钱？
奥拉夫：歌剧不适合我。
娜塔莉：那你有什么建议？
娜塔莉：票价是一百美元。
奥拉夫：我在想找个地方去派对狂欢。
娜塔莉：派对听起来很有趣，只要够高雅就行。
佐伊：<file_link>
佐伊：《蒂凡尼的早餐》主题派对听起来很高雅。
奥拉夫：<file_link>
奥拉夫：这够高雅吗？
娜塔莉：:O
娜塔莉：这家俱乐部太棒了！
佐伊：哇。
娜塔莉：那我们就去苏荷区吧。
奥拉夫：我们得赶紧去买票了。
佐伊：没问题。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
三人讨论除夕安排，娜塔莉提议高雅活动，奥拉夫建议派对。最终他们选定苏荷区一家俱乐部，并决定立即购票。
================================================================================


================================================================================
Sample ID: gold_00009
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
约翰：周三想看《一个明星的诞生》吗？
琼：抱歉，不行。
琼：超级忙。
琼：没时间做任何事 :(
约翰：真遗憾。
琼：我周四有空。
约翰：我周四也可以。
琼：好的！那大概晚上八点？
约翰：当然，听起来很棒。
约翰：我会查一下在哪里上映，然后把详情发给你。
琼：好的，太好了！
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
约翰邀请琼周三看电影被拒，因琼太忙。两人最终约定周四晚八点观看《一个明星的诞生》，约翰将查询上映信息并发给琼。
================================================================================


================================================================================
Sample ID: gold_00010
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
佩顿：我一直让你帮我带那个电子游戏。
卡梅伦：亲爱的，我实在没有足够的时间回家。
佩顿：那你什么时候能回家？
卡梅伦：我想我大概还得在外地待上一周。
佩顿：难道不能通过快递把游戏寄过来吗？:P
卡梅伦：别这么刻薄嘛。:/
佩顿：先把事情办好，然后尽快回家。越快越好。:P
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
佩顿催促卡梅伦带游戏回家，卡梅伦因在外地需停留一周无法带回。佩顿建议快递，卡梅伦抱怨其刻薄，佩顿要求其尽快处理事务并回家。
================================================================================


================================================================================
Sample ID: gold_00011
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
保罗：我刚回到家。
保罗：真是忙碌的一天。
保罗：我忘了我的物理治疗。
艾玛：哦，不。
保罗：没关系，我会预约一个新的时间。
艾玛：我半夜之后才能到家。
保罗：你想让我为你准备一些食物吗？
艾玛：那真是太好了。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
保罗忙完回家，因错过理疗将改约。艾玛深夜才归，保罗主动提出为她备餐，艾玛欣然接受。
================================================================================


================================================================================
Sample ID: gold_00012
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
哈里斯：你好吗？
莱娜：还好，你呢？
哈里斯：不太行。
莱娜：怎么了？
哈里斯：我的朋友青木昨天去世了。
莱娜：哦，天哪！
哈里斯：是啊。
莱娜：发生什么事了？
哈里斯：还不太清楚。心里正往最坏处想……
莱娜：哦，太可怕了！
哈里斯：是啊。
莱娜：你永远不知道会发生什么。
哈里斯：没错。
莱娜：你最近见过她吗？
哈里斯：好几个月没见了。她住在密歇根州。
莱娜：哦，那很远啊。
哈里斯：不算太远，但也够远了。
莱娜：也是。
哈里斯：我得走了，我妈在叫我。
莱娜：好的，拜拜。保重！
哈里斯：好的，我会的。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
哈里斯告知莱娜，其好友青木昨日去世，死因尚不明。两人谈及青木住在密歇根州，哈里斯已数月未见。随后哈里斯因母亲呼唤而告别。
================================================================================


================================================================================
Sample ID: gold_00013
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
雅兹：今晚要去减肥俱乐部吗？
玛丽：嗯，我其实不想去，但确实应该去。不过我最近实在太放纵了！
雅兹：我也是，巧克力、葡萄酒、蛋糕，你随便说！
玛丽：好吧，我们得硬着头皮去了。她肯定会训斥我们的，我敢肯定。感觉就像又回到了学校！
雅兹：毕竟她确实是我们以前的烹饪老师！大概六点左右见，我去接你？
玛丽：好的！到时候见！
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
雅兹和玛丽虽因近期饮食放纵而不愿去减肥俱乐部，但决定硬着头皮参加。两人约定六点在玛丽家见面，由雅兹接她一同前往。
================================================================================


================================================================================
Sample ID: gold_00014
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
艾莉：嘿，你在大学吗？
阿莉亚：是的
卡米尔：我生病了 :/
艾莉：天哪……这太糟糕了
艾莉：阿莉，我们现在在哪里上课？
阿莉亚：二楼的 342 教室
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
艾莉询问大家是否在大学，阿莉亚确认，卡米尔表示生病。艾莉随后向阿莉亚确认上课地点，得知在二楼 342 教室。
================================================================================


================================================================================
Sample ID: gold_00015
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
内森：<file_video>
亚伦：天哪！！！
亚伦：😂😂😂😂
亚伦：笑死我了
亚伦：伙计，你认识她吗？🤣🤣
亚伦：我家猫拉屎时的表情就跟这个一模一样..🤣🤣🤣
亚伦：<file_gif>
亚伦：天使们一定在哭泣 🤭🤭🤭
亚伦：<file_gif>
亚伦：<file_gif>
内森：哈哈哈哈
内森：她正在经历一个精神时刻 😉
内森：完全不知道，是丹发过来的
内森：至少可以说是一场悲剧 😂😂
亚伦：<file_gif>
亚伦：在寻找耶稣
内森：😂😂😂
亚伦：太搞笑了..哈哈哈哈
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
内森分享了一段搞笑视频，亚伦大笑并调侃视频人物表情像自家猫拉屎。两人互相发送表情包，戏称这是“精神时刻”和“寻找耶稣”，全程充满欢乐。
================================================================================


================================================================================
Sample ID: gold_00016
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
弗雷迪：你在奈飞上看什么？我刚看完《广告狂人》。
凯莉：我刚看完《王冠》。
弗雷迪：应该很快就会有新剧集上线。
凯莉：天哪！我等不及了！:)
弗雷迪：在此期间，你可以试试《古战场传奇》或《都铎王朝》。
吉姆：我正在看《我是僵尸》。
鲍勃：试试《格林》或《萨布丽娜》。这两部都很棒！
凯莉：它们全都糟糕透顶、令人作呕！
鲍勃：我觉得它们很有趣。它们只是电视剧，别太当真。x
格雷格：不过我得承认，我正在看《纸牌屋》，但新系列有点无聊。
迈克：我同意。没有凯文·史派西就不一样了！如果你喜欢政治剧，可以试试《白宫风云》。
格雷格：我听说奈飞原创剧《贴身保镖》很不错。
玛丽：有点不好意思承认，但我喜欢《美少女的谎言》或《绯闻女孩》这类剧 ;)
南希：别不好意思，我也喜欢！而且我最喜欢的是《绝望主妇》！！！
玛丽：我知道！我看了两遍！
艾伦：我正在补看《老友记》。
南希：天哪！我以前超爱《老友记》！
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
众人讨论奈飞剧集，提及《广告狂人》《王冠》等，对《纸牌屋》新季评价不一，并分享了对《老友记》《绝望主妇》等剧的喜爱。
================================================================================


================================================================================
Sample ID: gold_00017
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
琼斯：嘿。
安吉丽娜：嘿。
安吉丽娜：好久不见。你最近怎么样？
琼斯：我很好。
琼斯：你呢？
安吉丽娜：我也挺好的。
琼斯：你觉得我们今天下午晚些时候在城里见面怎么样？
安吉丽娜：当然可以。
琼斯：好的。我会打电话给你确认见面地点。
安吉丽娜：好的。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
琼斯与安吉丽娜寒暄后，约定下午在城里见面，琼斯稍后将致电确认具体地点。
================================================================================


================================================================================
Sample ID: gold_00018
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
凯西：<file_photo>
阿米莉亚：这些太漂亮了！！！是你自己做的吗？
克里斯滕：哇，太棒了！
阿米莉亚：我也想这样美甲！
凯西：是啊，是我自己做的：D 买了新指甲油，但天哪，我花了将近四个小时，哈哈。
阿米莉亚：你也能帮我们做吗？
克里斯滕：拜托拜托！
凯西：抱歉，各位……那简直是一场噩梦：( 说真的，美甲花四个小时太久了。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
凯西展示自制美甲，获阿米莉亚和克里斯滕称赞。因耗时近四小时，凯西婉拒了两人请求其帮忙做美甲的提议。
================================================================================


================================================================================
Sample ID: gold_00019
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
苏：收到这条信息时给我打电话。
苏：这很重要。
史蒂夫：好的，我现在就给你打。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
苏收到重要信息，要求史蒂夫立即回电，史蒂夫答应马上拨打。
================================================================================


================================================================================
Sample ID: gold_00020
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
蒂米：你想邀请谁？
杰玛：嗯，有你和你的约会对象 :)
蒂米：约会对象还不确定，但我会去的 :) 还有谁？
杰玛：我在想洛娜和米歇尔。
蒂米：你还在想着能收到她们的婚礼请柬吗？
杰玛：不是那样的。
蒂米：当然是那样 ;) 只是不想承认罢了 ;)
杰玛：好吧！我就是想去参加她们的婚礼招待会！
蒂米：这就对了 :) 有那么难吗？
杰玛：是的。
蒂米：那你觉得你能改变她们的主意吗？
杰玛：不知道。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
蒂米与杰玛讨论婚礼邀请名单，杰玛想邀请洛娜和米歇尔参加招待会，蒂米调侃她仍期待收到请柬，杰玛承认难以改变对方主意。
================================================================================


================================================================================
Sample ID: gold_00021
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
安：恭喜！！
安：你们俩都表现得非常出色！
苏：谢谢，安。
朱莉：我很高兴终于结束了！
朱莉：你真可爱，姑娘！
安：今晚我们稍微庆祝一下吧！
苏：我参加。
朱莉：我也参加！！！太棒了。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
安祝贺苏和朱莉表现出色，提议当晚庆祝，两人均欣然同意。
================================================================================


================================================================================
Sample ID: gold_00022
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
史蒂夫：嗨，洗碗机已经送来了。
妈妈：太好了，他们帮你安装好了吗？
史蒂夫：是的，他们干得很不错。
史蒂夫：<file_photo>
妈妈：看起来真不错。
史蒂夫：是啊，它既美观又安静。
妈妈：是十二人份的吗？
史蒂夫：我想是吧，反正我吃饭时也没凑过十二个人，哈哈。
妈妈：没错，但你不必每天都用啊。
史蒂夫：不，我是隔一天用一次。
妈妈：是啊，我很高兴你满意，亲亲。
史蒂夫：我也很高兴，谢谢妈妈，亲亲亲亲。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
史蒂夫告知妈妈洗碗机已送达并安装完毕，他称赞其美观安静。妈妈关心容量，史蒂夫表示虽不确定是否十二人份，但隔日使用已足够，两人互致满意与爱意。
================================================================================


================================================================================
Sample ID: gold_00023
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
玛丽卡：你今天来吗？
拉拉：来！
玛丽卡：太好了！
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
玛丽卡询问拉拉今天是否前来，拉拉确认会来，玛丽卡对此表示高兴。
================================================================================


================================================================================
Sample ID: gold_00024
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
米兰达：嗨，斯蒂芬妮，我们能否取消明天的会议？
斯蒂芬妮：又怎么了？发生什么事了？
米兰达：我得工作 :(
斯蒂芬妮：你一天工作二十个小时！
米兰达：年轻医生都是这样做的。
斯蒂芬妮：他们工作到把自己累死。
米兰达：不，他们只是接近死亡却幸存下来，这让他们变得不朽。
斯蒂芬妮：只要你有个解释就行 :D
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
米兰达因工作需取消明日会议，斯蒂芬妮质疑其过度劳累。米兰达辩称年轻医生皆如此，虽接近死亡却能幸存成就不朽，斯蒂芬妮对此表示无奈。
================================================================================


================================================================================
Sample ID: gold_00025
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
哈维尔：嘿，你知道附近有没有员工会说英语的纹身店吗？
朱迪：哦，有华沙墨水纹身店。
哈维尔：这名字听起来挺酷……你在那里纹过身吗？
朱迪：没有，但我女朋友纹过。
哈维尔：有照片吗？
朱迪：<file_photo>
哈维尔：哇，看起来太棒了。
哈维尔：她付了多少钱？
朱迪：一千。
哈维尔：靠。
哈维尔：那我还是回哥伦比亚再纹吧，谢了。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
哈维尔询问附近是否有英语纹身店，朱迪推荐了华沙墨水店并展示其女友的纹身。得知价格为一千后，哈维尔嫌贵，决定回哥伦比亚再纹。
================================================================================


================================================================================
Sample ID: gold_00026
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
山姆：各位，你们拥有一家非常棒的酒店 😊
杰西卡：谢谢山姆 😊
迈克尔：谢谢，老兄
山姆：我们下个月的酒店房间安排得怎么样了？希望经理能为我们安排最好的 😉
迈克尔：你说得对极了，山姆
迈克尔：你们会在 8 月 15 日抵达吗？
山姆：是的！我们大约下午两点到达酒店。
杰西卡：再次见到你们我太高兴了！
山姆：我也是 😊
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
山姆称赞酒店并表示期待下月入住。迈克尔确认他们将于 8 月 15 日下午两点抵达，双方对再次相聚感到高兴。
================================================================================


================================================================================
Sample ID: gold_00027
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
特伦斯：到底怎么回事，丹尼。你拿了我的钱，对吧？:/
丹尼尔：什么，你的钱？我为什么要……
特伦斯：别装傻。
丹尼尔：你是在说我撒谎吗，特里？
特伦斯：我又不是傻瓜，丹尼。
丹尼尔：那我也不是小偷，对吧？这可不地道，伙计。:/
特伦斯：……哦，天哪，对不起，我刚找到了。忘了我上个月把它放在别处了。
丹尼尔：那真是为你高兴。
特伦斯：你生气了吗？
丹尼尔：你觉得呢？当然生气了，他妈的当然生气。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
特伦斯误以为丹尼尔偷了他的钱并加以指责，随后发现钱是自己放错了地方。特伦斯道歉后，丹尼尔表示对此事感到愤怒。
================================================================================


================================================================================
Sample ID: gold_00028
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
娜塔莎：嗨，我可以去 RER 接你。
查尔斯：太好了。我刚落地。我想我大约下午 5 点 30 分到达。我会给你打电话。
娜塔莎：好的，当你到达韦西内站时给我打电话。
查尔斯：谢谢。再见。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
娜塔莎将去 RER 接刚落地的查尔斯。查尔斯预计下午 5 点 30 分到达，并会在抵达韦西内站时致电娜塔莎。
================================================================================


================================================================================
Sample ID: gold_00029
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
梅格：还在学校吗？
安：我有额外的数学课。
梅格：那我什么时候能见到你？
安：我七点到家。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
安因有额外数学课仍在学校，预计七点到家，梅格询问何时能见到她。
================================================================================


================================================================================
Sample ID: gold_00030
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
皮特：你刚才说想要什么口味的酸奶？我今天脑子像漏勺一样。
珍：梨味，但只有他们有货才行。如果没有，就别麻烦了。
皮特：我去看看。如果没有梨味，我可以买其他口味吗？
珍：我不喜欢其他任何口味。如果没有梨味，那就什么都别买了。
皮特：好的。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
皮特询问珍想要什么口味的酸奶，珍表示只要梨味，若无货则不买其他口味。皮特答应去查看。
================================================================================


================================================================================
Sample ID: gold_00031
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
克里斯蒂：派对之后你怎么样？
凯蒂：真的很累……你呢？
克里斯蒂：我也是。
克里斯蒂：派对太棒了！
凯蒂：是啊，我们玩得很开心！:)
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
克里斯蒂和凯蒂在派对后都感到疲惫，但一致认为派对很棒，两人玩得很开心。
================================================================================


================================================================================
Sample ID: gold_00032
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
山姆：你明天工作吗？
卡拉：不，明天是我的休息日。
山姆：我下午有空，你想见面吗？
卡拉：好啊，没问题。
山姆：太好了！我们去米恩伍德怎么样？
卡拉：行，那里有家咖啡馆，蛋糕特别好吃。两点见？
山姆：好——很期待！
卡拉：明天见！亲亲
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
山姆邀请明天休息的卡拉下午见面，两人约定两点在米恩伍德咖啡馆碰面，卡拉还推荐了那里的蛋糕。
================================================================================


================================================================================
Sample ID: gold_00033
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
乔安娜：想玩些游戏吗？
桑迪：玩什么游戏？
乔安娜：也许玩迪克西特？
乔安娜：或者玩卡卡颂？
桑迪：为什么不呢？
乔安娜：好的，我把这两样带给你。
桑迪：太好了 :)
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
乔安娜提议玩迪克西特或卡卡颂，桑迪欣然同意，乔安娜将把这两款游戏带给桑迪。
================================================================================


================================================================================
Sample ID: gold_00034
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
史蒂夫：五分钟前买了梦剧院的新专辑。希望它不错。
罗布：我桌上就有这张，准备第一次听。
史蒂夫：好的，稍后告诉你我的想法。
罗布：我也是。待会儿见！
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
史蒂夫刚买了梦剧院新专辑，罗布桌上也有这张准备首听，两人约定稍后交流听后感。
================================================================================


================================================================================
Sample ID: gold_00035
=== Agent 1 Intermediate Output: Translated Chinese Dialogue ===
彼得：你能把你们美容店的链接发给我吗？
乔伊：当然可以。
乔伊：网址是 https:// *********
乔伊：希望您会喜欢，如有任何问题请随时提问。
彼得：好的，让我看看。
================================================================================

=== Agent 2 Final Output: Chinese Summary ===
彼得向乔伊索要美容店链接，乔伊提供了网址并表示如有问题可随时提问，彼得确认收到并准备查看。
================================================================================



## 6. Export Final Summaries to CSV

This file can be used for ROUGE, BERTScore, OmniScore, or manual analysis.

For the ST pipeline, the CSV also includes the intermediate English summary from Agent 1.

In [15]:
# Cell 14: Export TS summaries to CSV

records = load_jsonl(FULL_OUTPUT_PATH)

rows = []

for record in records:
    if "final_summary" not in record:
        continue

    rows.append({
        "id": record.get("id", ""),
        "test_index": record.get("test_index", ""),
        "dialogue": record.get("dialogue", ""),

        # Intermediate output from Agent 1
        "translated_dialogue": record.get("translated_dialogue", ""),

        # Final output from Agent 2
        "final_summary": record.get("final_summary", ""),

        # References
        "reference_english_summary": record.get("reference_english_summary", ""),
        "reference_chinese_summary": record.get("reference_chinese_summary", ""),

        # Metadata
        "pipeline": record.get("pipeline", "translate_then_summarize"),
        "translation_model": record.get("translation_model", ""),
        "summarization_model": record.get("summarization_model", ""),
        "num_model_calls": record.get("num_model_calls", 2),
    })

df = pd.DataFrame(rows)

if not df.empty:
    df = df.drop_duplicates(subset=["id"], keep="last")

df.to_csv(FINAL_CSV_PATH, index=False, encoding="utf-8-sig")

print(f"Saved final summaries to: {FINAL_CSV_PATH}")
df

Saved final summaries to: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\ts_qwen27b_50samples.csv

,id,test_index,dialogue,translated_dialogue,final_summary,reference_english_summary,reference_chinese_summary,pipeline,translation_model,summarization_model,num_model_calls
0,gold_00001,23,"Anne: You were right, he was lying to me :/\nI...",安妮：你是对的，他对我撒谎了 :/\n艾琳：哦不，发生什么事了？\n简：谁？那个马克吗？\n...,安妮发现马克在年龄上对她撒谎，他自称三十岁，但护照显示实际为四十岁。尽管艾琳质疑此事的重要性...,Mark lied to Anne about his age. Mark is 40.,马克向安妮隐瞒了自己的年龄。他40岁了。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
1,gold_00002,30,"Mary: hey, im kinda broke, lend me a few box\r...",玛丽：嘿，我手头有点紧，借我几盒吧。\n卡特：好的，给我一小时，我在火车站。\n玛丽：太好了...,玛丽因手头紧向卡特借几盒，卡特答应一小时后在火车站交付，玛丽表示感谢。,Mary ran out of money. Carter is going to lend...,玛丽的钱用完了，卡特打算一小时后借给她一点。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
2,gold_00003,39,"Tina: I'll tell you something, this Emirate st...",蒂娜：我告诉你，这家阿联酋航空的机组人员看起来太棒了，就像电影明星一样。\n阿拉：哦，是的，...,蒂娜称赞阿联酋航空机组形象，但抱怨机场滞留及航班延误。阿拉表示同情，随后告知要去开会，两人约...,Tina will catch the evening flight back home. ...,蒂娜将乘晚间航班回家。阿拉正在去开会的路上。她会让蒂娜知道事情的进展。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
3,gold_00004,65,Ana: You sleeping?\r\nCatherine: Not yet.\r\nA...,安娜：你睡着了吗？\n凯瑟琳：还没。\n安娜：明天想去探望奶奶吗？我想她了。\n凯瑟琳：好啊...,安娜提议明天探望奶奶，凯瑟琳欣然同意，并约定醒来后联系，随后两人互道晚安。,Ana wants to visit grandma tomorrow. Catherine...,安娜明天想去看望奶奶。凯瑟琳会和她一起去。她起床后会给安娜打电话。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
4,gold_00005,66,Joyce: Check this out!\r\nJoyce: <link>\r\nMic...,乔伊斯：快看看这个！\n乔伊斯：<link>\n迈克尔：太便宜了！\n埃德森：不可能！我现在...,乔伊斯分享了一个链接，迈克尔感叹价格太便宜，埃德森则决定立即订票。,Edson is booking his ticket now.,埃德森正在订票。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
5,gold_00006,67,Jane: google maps says it is at least 3h <file...,简：谷歌地图显示至少需要 3 小时 <file_other>\n史蒂文：我以前 2 小时就到...,简提议将见面时间改为 4 点半，史蒂文同意。两人确认将在主入口见面。,Jane wants to leave at 4.30 instead of 5 becau...,简想4点半就走，而不是等到5点，因为谷歌地图提示300公里的车程至少需要3小时，她不想迟到。...,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
6,gold_00007,78,"Fiona: Are you free?\r\nTina: Yes, what's up?\...",菲奥娜：你有空吗？\n蒂娜：有空，怎么了？\n菲奥娜：我正在为克里斯准备一顿丰盛的晚餐，我在...,菲奥娜邀请蒂娜帮忙为克里斯做挞。菲奥娜已买好挞皮，但馅料做成了柠檬炒蛋。蒂娜安慰她，并指出加...,Fiona wants to prepare dinner for Chris. She i...,菲奥娜想为克里斯准备晚餐。她想起了蒂娜做的馅饼。蒂娜会帮她做的。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
7,gold_00008,86,Olafur: are we doing anything for New Year's E...,奥拉夫：我们除夕夜有什么安排吗？\n娜塔莉：我在想一些高雅的活动，比如歌剧之类的。\n佐伊：...,三人讨论除夕安排，娜塔莉提议高雅活动，奥拉夫建议派对。最终他们选定苏荷区一家俱乐部，并决定立...,"Nathalie, Olafur and Zoe are planning the New ...",娜塔莉、奥拉维尔和佐伊正在做新年前夜的计划。娜塔莉想要有格调的。但奥拉维尔不喜欢歌剧。他们想...,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
8,gold_00009,120,"John: wanna go see ""A Star is Born"" on Wed?\r\...",约翰：周三想看《一个明星的诞生》吗？\n琼：抱歉，不行。\n琼：超级忙。\n琼：没时间做任何...,约翰邀请琼周三看电影被拒，因琼太忙。两人最终约定周四晚八点观看《一个明星的诞生》，约翰将查询...,"Joan and John are going to watch ""A Star is Bo...",琼和约翰星期四晚上8点左右去看《一个明星的诞生》。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
9,gold_00010,137,Peyton: I have been asking you to bring that v...,佩顿：我一直让你帮我带那个电子游戏。\n卡梅伦：亲爱的，我实在没有足够的时间回家。\n佩顿：...,佩顿催促卡梅伦带游戏回家，卡梅伦因在外地需停留一周无法带回。佩顿建议快递，卡梅伦抱怨其刻薄，...,Peyton is expecting Cameron to bring the video...,佩顿希望卡梅隆能带游戏机过来，但是卡梅隆可能还要再缺席一周。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
10,gold_00011,139,Paul: I just came back home\r\nPaul: What a bu...,保罗：我刚回到家。\n保罗：真是忙碌的一天。\n保罗：我忘了我的物理治疗。\n艾玛：哦，不。...,保罗忙完回家，因错过理疗将改约。艾玛深夜才归，保罗主动提出为她备餐，艾玛欣然接受。,Paul forgot about his physiotherapy and he wil...,保罗忘记去做理疗了，得重新预约。艾玛午夜后回家，所以保罗会给她准备一些吃的。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
11,gold_00012,192,"Harris: How are U?\r\nLena: Fine, U?\r\nHarris...",哈里斯：你好吗？\n莱娜：还好，你呢？\n哈里斯：不太行。\n莱娜：怎么了？\n哈里斯：我的...,哈里斯告知莱娜，其好友青木昨日去世，死因尚不明。两人谈及青木住在密歇根州，哈里斯已数月未见。...,"Harris' friend, Aoki, who lives in Michigan, d...",哈里斯的朋友青木住在密歇根州，昨天去世了。哈里斯有几个月没见她了。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
12,gold_00013,210,Yaz: Going to slimming club tonight?\r\nMary: ...,雅兹：今晚要去减肥俱乐部吗？\n玛丽：嗯，我其实不想去，但确实应该去。不过我最近实在太放纵了...,雅兹和玛丽虽因近期饮食放纵而不愿去减肥俱乐部，但决定硬着头皮参加。两人约定六点在玛丽家见面，...,Yaz and Mary are meeting tonight around 6 and ...,亚兹和玛丽今晚6点左右见面，一起去减肥俱乐部。他们估计吃得太多会被骂。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
13,gold_00014,211,"Ellie: hey, are you at the university?\r\nAali...",艾莉：嘿，你在大学吗？\n阿莉亚：是的\n卡米尔：我生病了 :/\n艾莉：天哪……这太糟糕了...,艾莉询问大家是否在大学，阿莉亚确认，卡米尔表示生病。艾莉随后向阿莉亚确认上课地点，得知在二楼...,Ellie's class is in 342 on the second floor.,艾莉的班级在二楼342教室。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
14,gold_00015,212,Nathan: <file_video>\r\nAaron: OMG!!! \r\nAaro...,内森：<file_video>\n亚伦：天哪！！！\n亚伦：😂😂😂😂\n亚伦：笑死我了\n亚...,内森分享了一段搞笑视频，亚伦大笑并调侃视频人物表情像自家猫拉屎。两人互相发送表情包，戏称这是...,Nathan and Aaron are discussing a video which ...,内森和亚伦正在讨论内森发来的视频。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
15,gold_00016,215,Freddie: What are you watching on Netflix? I'v...,弗雷迪：你在奈飞上看什么？我刚看完《广告狂人》。\n凯莉：我刚看完《王冠》。\n弗雷迪：应该...,众人讨论奈飞剧集，提及《广告狂人》《王冠》等，对《纸牌屋》新季评价不一，并分享了对《老友记》...,"Freddie, Kelly, Jim, Greg, Bob, Mike, Mary, Al...",弗雷迪、凯利、吉姆、格雷格、鲍勃、迈克、玛丽、艾伦和南希正在netflix上观看不同的节目。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
16,gold_00017,244,Jones: Hey.\r\nAngelina: Hey.\r\nAngelina: Lon...,琼斯：嘿。\n安吉丽娜：嘿。\n安吉丽娜：好久不见。你最近怎么样？\n琼斯：我很好。\n琼斯...,琼斯与安吉丽娜寒暄后，约定下午在城里见面，琼斯稍后将致电确认具体地点。,Jones and Angelina will meet in town in the af...,琼斯和安吉丽娜下午会在城里见面。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
17,gold_00018,285,Casey: <file_photo>\r\nAmelia: these are so ni...,凯西：<file_photo>\n阿米莉亚：这些太漂亮了！！！是你自己做的吗？\n克里斯滕：...,凯西展示自制美甲，获阿米莉亚和克里斯滕称赞。因耗时近四小时，凯西婉拒了两人请求其帮忙做美甲的提议。,Casey got a new nail polish and did her nails ...,凯西买了新指甲油，自己做了指甲。她花了近4个小时，所以她不会帮朋友做指甲，因为耗时太长了。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
18,gold_00019,319,Sue: Call me when you get this.\r\nSue: it's i...,苏：收到这条信息时给我打电话。\n苏：这很重要。\n史蒂夫：好的，我现在就给你打。,苏收到重要信息，要求史蒂夫立即回电，史蒂夫答应马上拨打。,Steve is calling Sue at her request.,史蒂夫正按照苏的要求给她打电话。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
19,gold_00020,346,"Timmy: Who do u wanna invite?\r\nGemma: Well, ...",蒂米：你想邀请谁？\n杰玛：嗯，有你和你的约会对象 :)\n蒂米：约会对象还不确定，但我会去...,蒂米与杰玛讨论婚礼邀请名单，杰玛想邀请洛娜和米歇尔参加招待会，蒂米调侃她仍期待收到请柬，杰玛...,"Gemma will invite Timmy and his Date, as well ...",杰玛将邀请蒂米和他的约会对象，以及罗娜和米歇尔参加她的婚礼。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
20,gold_00021,355,"Ann: Congratulations!!\r\nAnn: You did great, ...",安：恭喜！！\n安：你们俩都表现得非常出色！\n苏：谢谢，安。\n朱莉：我很高兴终于结束了！...,安祝贺苏和朱莉表现出色，提议当晚庆祝，两人均欣然同意。,"Ann, Sue and Julie did a great job and they wi...",安、苏和朱莉做得很好，今晚他们会举行一个小小的庆祝活动。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
21,gold_00022,367,Steve: hiya the dishwasher has turned up\r\nMu...,史蒂夫：嗨，洗碗机已经送来了。\n妈妈：太好了，他们帮你安装好了吗？\n史蒂夫：是的，他们干...,史蒂夫告知妈妈洗碗机已送达并安装完毕，他称赞其美观安静。妈妈关心容量，史蒂夫表示虽不确定是否...,Steve is happy that he got a new dishwasher in...,史蒂夫很高兴他装了一台新的洗碗机。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
22,gold_00023,393,Marika: Are you coming today?\r\nLara: Yes!\r\...,玛丽卡：你今天来吗？\n拉拉：来！\n玛丽卡：太好了！,玛丽卡询问拉拉今天是否前来，拉拉确认会来，玛丽卡对此表示高兴。,Marika is coming today.,玛丽卡今天会来。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
23,gold_00024,417,"Miranda: Hi S, could we cancel tomorrow's meet...",米兰达：嗨，斯蒂芬妮，我们能否取消明天的会议？\n斯蒂芬妮：又怎么了？发生什么事了？\n米兰...,米兰达因工作需取消明日会议，斯蒂芬妮质疑其过度劳累。米兰达辩称年轻医生皆如此，虽接近死亡却能...,Miranda can't make her meeting with Stephanie ...,米兰达不能去见斯蒂芬妮，因为她要工作。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
24,gold_00025,432,Javier: Hey do you know any tattoo parlors ove...,哈维尔：嘿，你知道附近有没有员工会说英语的纹身店吗？\n朱迪：哦，有华沙墨水纹身店。\n哈维...,哈维尔询问附近是否有英语纹身店，朱迪推荐了华沙墨水店并展示其女友的纹身。得知价格为一千后，哈...,Javier was initially eager to have a tatoo don...,哈维尔最初很想在warsaw ink纹身，但价格太高了。他决定去哥伦比亚做纹身。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
25,gold_00026,433,"Sam: You own a really nice hotel, guys 😊\r\nJe...",山姆：各位，你们拥有一家非常棒的酒店 😊\n杰西卡：谢谢山姆 😊\n迈克尔：谢谢，老兄\n山...,山姆称赞酒店并表示期待下月入住。迈克尔确认他们将于 8 月 15 日下午两点抵达，双方对再次...,Sam appreciates the hotel owned by Jessica and...,山姆很喜欢杰西卡和迈克尔的酒店。他会在8月15日下午2点左右去那里。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
26,gold_00027,442,"Terence: What the hell, Danny. You took my mon...",特伦斯：到底怎么回事，丹尼。你拿了我的钱，对吧？:/\n丹尼尔：什么，你的钱？我为什么要……...,特伦斯误以为丹尼尔偷了他的钱并加以指责，随后发现钱是自己放错了地方。特伦斯道歉后，丹尼尔表示...,Terence accused Daniel of taking his money. Te...,特伦斯指控丹尼尔偷了他的钱。后来他找到了钱，就向丹尼尔道歉。但是丹尼尔还在生气。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
27,gold_00028,499,"Natacha: hi, i can come and pick you up at the...",娜塔莎：嗨，我可以去 RER 接你。\n查尔斯：太好了。我刚落地。我想我大约下午 5 点 3...,娜塔莎将去 RER 接刚落地的查尔斯。查尔斯预计下午 5 点 30 分到达，并会在抵达韦西内...,Charles has just landed and he will be at RER ...,查尔斯刚刚落地，他会在下午五点半到达rer，娜塔夏会在那里接他。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
28,gold_00029,528,Meg: still at school?\r\nAnn: i have extra mat...,梅格：还在学校吗？\n安：我有额外的数学课。\n梅格：那我什么时候能见到你？\n安：我七点到家。,安因有额外数学课仍在学校，预计七点到家，梅格询问何时能见到她。,Ann is still at school. She will be home at 7 ...,安还在学校，她7点会回家，这样她就可以和麦格见面了。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
29,gold_00030,532,Pete: What flavour yogurt did you want again? ...,皮特：你刚才说想要什么口味的酸奶？我今天脑子像漏勺一样。\n珍：梨味，但只有他们有货才行。如...,皮特询问珍想要什么口味的酸奶，珍表示只要梨味，若无货则不买其他口味。皮特答应去查看。,Pete will get a pear yogurt for Jen if they ha...,如果商店里有梨味酸奶， 皮特会给珍买的。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
30,gold_00031,536,Christie: how are you after the party?\r\nKati...,克里斯蒂：派对之后你怎么样？\n凯蒂：真的很累……你呢？\n克里斯蒂：我也是。\n克里斯蒂：...,克里斯蒂和凯蒂在派对后都感到疲惫，但一致认为派对很棒，两人玩得很开心。,Christie and Katie are tired after the party. ...,克里斯蒂和凯蒂在聚会后累了。他们都玩得很开心。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
31,gold_00032,537,"Sam: Are you working tomorrow?\r\nCarla: No, i...",山姆：你明天工作吗？\n卡拉：不，明天是我的休息日。\n山姆：我下午有空，你想见面吗？\n卡...,山姆邀请明天休息的卡拉下午见面，两人约定两点在米恩伍德咖啡馆碰面，卡拉还推荐了那里的蛋糕。,Carla has a day off tomorrow. She will meet Sa...,卡拉明天有一天假。她将在下午两点在meanwood的一个咖啡馆和山姆见面。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
32,gold_00033,544,Joana: wana play some games?\r\nSandy: what ga...,乔安娜：想玩些游戏吗？\n桑迪：玩什么游戏？\n乔安娜：也许玩迪克西特？\n乔安娜：或者玩卡...,乔安娜提议玩迪克西特或卡卡颂，桑迪欣然同意，乔安娜将把这两款游戏带给桑迪。,Joana will bring Sandy some games like dixit a...,琼娜将为桑迪带来一些像迪克西特和卡尔卡松这样的游戏。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
33,gold_00034,548,Steve: Bought the new Dream Theater album 5 mi...,史蒂夫：五分钟前买了梦剧院的新专辑。希望它不错。\n罗布：我桌上就有这张，准备第一次听。\n...,史蒂夫刚买了梦剧院新专辑，罗布桌上也有这张准备首听，两人约定稍后交流听后感。,Steve and Rob will talk about new Dream Theate...,史蒂夫和罗伯将在听完后谈论新的梦剧场专辑。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
34,gold_00035,551,Peter: Can you send me the link of your beauty...,彼得：你能把你们美容店的链接发给我吗？\n乔伊：当然可以。\n乔伊：网址是 https://...,彼得向乔伊索要美容店链接，乔伊提供了网址并表示如有问题可随时提问，彼得确认收到并准备查看。,Joy sent Peter the link to her beauty shop.,乔伊把她美容店的链接发给了彼得。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
35,gold_00036,590,Ethan: who's going to see solstafir?\r\nNoah: ...,伊森：谁要去听索尔斯塔菲尔的演出？\n诺亚：索尔斯塔菲尔！什么时候？\n诺亚：我完全不知道他...,伊森提议 11 月 21 日观看索尔斯塔菲尔演出，利奥极力邀请，阿奇拒绝。诺亚因工作不确定能...,Ethan and Leo are going to see Sólstafir on 21...,伊森和里奥要在21点11分去见索斯塔弗。诺亚也想去，但他可能得工作到很晚。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
36,gold_00037,598,Bradley: haha look a cat invaded the pitch at ...,布拉德利：哈哈，看，一只猫闯入了古迪逊公园球场 <file_other>\n吉尔：哈哈哈哈\...,布拉德利分享了一只猫闯入古迪逊公园球场的视频，朱莉娅和吉尔觉得非常可爱，布拉德利称这是埃弗顿...,A sweet little black cat got into the pitch du...,在埃弗顿的足球比赛中，一只可爱的小黑猫钻进了球场。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
37,gold_00038,605,"Barbara: I'm home already, you can come over\r...",芭芭拉：我已经到家了，你可以过来。\n肖恩：我可以带狗来吗？\n扎克：我正在路上。\n芭芭拉...,芭芭拉告知已到家，肖恩询问能否带狗并获准，随后提出留宿过夜，芭芭拉欣然同意。,"Barbara, Sean and Zac are meeting at Barbara's...",芭芭拉、肖恩和扎克今晚在芭芭拉家见面。肖恩会把狗带来的，肖恩和扎克会在这里过夜。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
38,gold_00039,616,"Jake: dude, I just pulled a TOTW\nJake: my fir...",杰克：伙计，我刚刚抽到了一张TOTW卡！\n杰克：这是我今年第一张！\n汤姆：恭喜！\n汤姆...,杰克抽到今年首张 TOTW 卡，因阵容不合计划试用后出售。汤姆抽卡运气不佳，杰克安慰他游戏水...,Jake has got his first TOTW this year. Tom doe...,杰克今年拿到了第一个totw ，汤姆的团队并不出色。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
39,gold_00040,621,Phil: Good evening Deana! Many thanks for this...,菲尔：晚上好，迪安娜！非常感谢你寄来的这张漂亮卡片，康斯坦丁非常高兴！\n菲尔：这副太阳镜也...,菲尔感谢迪安娜的卡片，并确认太阳镜非凯瑟琳或迪安娜所有。两人推测可能是阿德里安的，决定代为保管。,Phil received a card from Deana. Constantine w...,菲尔收到了迪安娜的一张卡片，康斯坦丁很开心。菲尔有副墨镜。蒂娜在后面收音机上面找到的。迪安娜...,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
40,gold_00041,635,Mell: Hi there! How are you doing?\r\nGloria: ...,梅尔：你好！最近怎么样？ \n格洛丽亚：嗨，梅尔！我们挺好的，就是日复一日的忙碌；) 你们...,梅尔与格洛丽亚通话，两人聊起孩子离家后的生活，并约定本周末在梅尔家举办烧烤。她们还讨论了梅尔...,Gloria and Mell plan to have a barbeque at Mel...,格洛丽亚和梅尔计划星期六在梅尔家吃烧烤。他们很高兴，因为泰德的姐姐搬到了苏格兰。梅尔需要格洛...,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
41,gold_00042,649,Callan: Something's wrong with my Samsung S8.\...,卡兰：我的三星 S8 出问题了。\n韦德：具体是什么问题？\n卡兰：我只能看到黑屏。\n韦德...,卡兰的三星 S8 出现黑屏且曾过热，韦德提醒电池危险。卡兰因手机在保修期内，计划送店检查，并...,"Callan's Samsung S8 overheats, so he's going t...",卡伦的三星s8过热了，所以他要去店里修理。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
42,gold_00043,676,"Anna: Mum, I have a awful stomachache.\r\nJoan...",安娜：妈妈，我肚子疼得厉害。\n乔安娜：哦，天哪，你什么时候开始疼的？\n安娜：晚上开始的，...,安娜因腹痛向母亲求助，两人排查饮食原因未果。母亲建议观察或就医，安娜决定为其冲泡薄荷茶缓解，...,Anna got an awful stomachache at night but she...,安娜夜里胃疼得厉害，但她不知道其中的原因。她的妈妈乔安娜会用新鲜的薄荷叶为她做热茶。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
43,gold_00044,678,Sam: Where are you?\nKate: downstairs\nSam: al...,山姆：你在哪儿？\n凯特：楼下。\n山姆：这么快？\n凯特：当然，下来吧。\n杰夫：我们在接...,凯特告知山姆和杰夫，接待处旁小房间内有一位女士正在制作一个带有巨大阴茎、睾丸和巧克力头发的定...,Kate and Jeff are downstairs in a room next to...,凯特和杰夫在楼下接待处旁边的一个房间里。有位女士正在做杏仁蛋糕。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
44,gold_00045,690,"Mia: God, he keeps talking about the stupid wa...",米娅：天哪，他一直在谈论那堵愚蠢的墙。\n珍妮弗：我觉得他只是老糊涂了。\n卡琳：不幸的是，...,众人认为特朗普并非老糊涂，而是利用民粹策略破坏世界秩序。尽管他愚蠢且固执，但大家决心不惜一切...,"Mia, Jennifer, Karine and Peter do not like Tr...",米亚、珍妮弗、卡琳和彼得不喜欢特朗普。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
45,gold_00046,711,Pedro: batman or superman??\r\nAlex: honestly....,佩德罗：蝙蝠侠还是超人？\n亚历克斯：说实话……两个都不行。\n佩德罗：什么？\n亚历克斯：...,佩德罗询问亚历克斯更喜欢蝙蝠侠还是超人，亚历克斯表示更偏爱闪电侠。他解释闪电侠速度极快，甚至...,Alex prefers the Flash to Barman and Superman ...,阿莱克斯更喜欢闪电侠，因为他的速度。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
46,gold_00047,737,Damian: are you downtown?\r\nEthan: yes\r\nEth...,达米安：你在市中心吗？\n伊森：是的。\n伊森：怎么了？\n达米安：你能帮我买个烤肉串吗？\...,达米安因疲惫请求在市中心的朋友伊森帮忙买烤肉串。伊森虽不满其依赖行为，最终仍答应帮忙，达米安...,Ethan will buy Damian a kebab. Damian had a ba...,伊森会请达米安吃烤肉串，达米安今天过得很糟糕。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
47,gold_00048,767,"Barry: I'm gonna go march in Women's strike, a...",巴里：我打算去参加女性罢工游行，有人感兴趣吗？\n杰克：我有兴趣，已经和一些朋友做好了计划，...,巴里提议参加女性罢工游行，杰克和戴夫均表示参加并邀请同伴，众人约定中午在校园里碰头。,"Barry, Dave, Kelly, and Jake will meet around ...",巴里、戴夫、凯利和杰克将于12点在校园附近集合，参加妇女罢工。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
48,gold_00049,799,"Martha: Hey, can I ask you a question?\r\nOphe...",玛莎：嘿，我能问你一个问题吗？\n奥菲莉亚：我们认识吗？\n玛莎：我们不认识，但你不介意我问...,玛莎询问奥菲莉亚个人资料中佩戴的美瞳品牌，奥菲莉亚推荐了“疯狂美瞳”，并称赞其价格合理、发货...,Martha likes Ophelia's lenses and wants to buy...,玛莎喜欢奥菲莉娅的眼镜，想买类似的，奥菲莉娅是从crazy lens上买的。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2
49,gold_00050,800,"Linda: Hi Dad, I want to buy flowers for mum! ...",琳达：嗨，爸爸，我想给妈妈买花！但我记不起她喜欢哪一种了 :(\n迈克尔：嗯，我相信她喜欢所...,琳达在花卉市场想给妈妈买花，因记不清喜好向父亲求助。经父亲建议并查看图片，最终决定购买妈妈喜...,Linda wants to buy flowers for her mother and ...,琳达想给她妈妈买花，问迈克尔她喜欢哪种花。迈克尔建议琳达买小苍兰。,translate_then_summarize,qwen3.5:27b,qwen3.5:27b,2

In [16]:
# Cell 15: Compare TS outputs with references

comparison_columns = [
    "id",
    "test_index",
    "translated_dialogue",
    "final_summary",
    "reference_chinese_summary",
]

comparison_df = df[comparison_columns].copy()

comparison_df

,id,test_index,translated_dialogue,final_summary,reference_chinese_summary
0,gold_00001,23,安妮：你是对的，他对我撒谎了 :/\n艾琳：哦不，发生什么事了？\n简：谁？那个马克吗？\n...,安妮发现马克在年龄上对她撒谎，他自称三十岁，但护照显示实际为四十岁。尽管艾琳质疑此事的重要性...,马克向安妮隐瞒了自己的年龄。他40岁了。
1,gold_00002,30,玛丽：嘿，我手头有点紧，借我几盒吧。\n卡特：好的，给我一小时，我在火车站。\n玛丽：太好了...,玛丽因手头紧向卡特借几盒，卡特答应一小时后在火车站交付，玛丽表示感谢。,玛丽的钱用完了，卡特打算一小时后借给她一点。
2,gold_00003,39,蒂娜：我告诉你，这家阿联酋航空的机组人员看起来太棒了，就像电影明星一样。\n阿拉：哦，是的，...,蒂娜称赞阿联酋航空机组形象，但抱怨机场滞留及航班延误。阿拉表示同情，随后告知要去开会，两人约...,蒂娜将乘晚间航班回家。阿拉正在去开会的路上。她会让蒂娜知道事情的进展。
3,gold_00004,65,安娜：你睡着了吗？\n凯瑟琳：还没。\n安娜：明天想去探望奶奶吗？我想她了。\n凯瑟琳：好啊...,安娜提议明天探望奶奶，凯瑟琳欣然同意，并约定醒来后联系，随后两人互道晚安。,安娜明天想去看望奶奶。凯瑟琳会和她一起去。她起床后会给安娜打电话。
4,gold_00005,66,乔伊斯：快看看这个！\n乔伊斯：<link>\n迈克尔：太便宜了！\n埃德森：不可能！我现在...,乔伊斯分享了一个链接，迈克尔感叹价格太便宜，埃德森则决定立即订票。,埃德森正在订票。
5,gold_00006,67,简：谷歌地图显示至少需要 3 小时 <file_other>\n史蒂文：我以前 2 小时就到...,简提议将见面时间改为 4 点半，史蒂文同意。两人确认将在主入口见面。,简想4点半就走，而不是等到5点，因为谷歌地图提示300公里的车程至少需要3小时，她不想迟到。...
6,gold_00007,78,菲奥娜：你有空吗？\n蒂娜：有空，怎么了？\n菲奥娜：我正在为克里斯准备一顿丰盛的晚餐，我在...,菲奥娜邀请蒂娜帮忙为克里斯做挞。菲奥娜已买好挞皮，但馅料做成了柠檬炒蛋。蒂娜安慰她，并指出加...,菲奥娜想为克里斯准备晚餐。她想起了蒂娜做的馅饼。蒂娜会帮她做的。
7,gold_00008,86,奥拉夫：我们除夕夜有什么安排吗？\n娜塔莉：我在想一些高雅的活动，比如歌剧之类的。\n佐伊：...,三人讨论除夕安排，娜塔莉提议高雅活动，奥拉夫建议派对。最终他们选定苏荷区一家俱乐部，并决定立...,娜塔莉、奥拉维尔和佐伊正在做新年前夜的计划。娜塔莉想要有格调的。但奥拉维尔不喜欢歌剧。他们想...
8,gold_00009,120,约翰：周三想看《一个明星的诞生》吗？\n琼：抱歉，不行。\n琼：超级忙。\n琼：没时间做任何...,约翰邀请琼周三看电影被拒，因琼太忙。两人最终约定周四晚八点观看《一个明星的诞生》，约翰将查询...,琼和约翰星期四晚上8点左右去看《一个明星的诞生》。
9,gold_00010,137,佩顿：我一直让你帮我带那个电子游戏。\n卡梅伦：亲爱的，我实在没有足够的时间回家。\n佩顿：...,佩顿催促卡梅伦带游戏回家，卡梅伦因在外地需停留一周无法带回。佩顿建议快递，卡梅伦抱怨其刻薄，...,佩顿希望卡梅隆能带游戏机过来，但是卡梅隆可能还要再缺席一周。
10,gold_00011,139,保罗：我刚回到家。\n保罗：真是忙碌的一天。\n保罗：我忘了我的物理治疗。\n艾玛：哦，不。...,保罗忙完回家，因错过理疗将改约。艾玛深夜才归，保罗主动提出为她备餐，艾玛欣然接受。,保罗忘记去做理疗了，得重新预约。艾玛午夜后回家，所以保罗会给她准备一些吃的。
11,gold_00012,192,哈里斯：你好吗？\n莱娜：还好，你呢？\n哈里斯：不太行。\n莱娜：怎么了？\n哈里斯：我的...,哈里斯告知莱娜，其好友青木昨日去世，死因尚不明。两人谈及青木住在密歇根州，哈里斯已数月未见。...,哈里斯的朋友青木住在密歇根州，昨天去世了。哈里斯有几个月没见她了。
12,gold_00013,210,雅兹：今晚要去减肥俱乐部吗？\n玛丽：嗯，我其实不想去，但确实应该去。不过我最近实在太放纵了...,雅兹和玛丽虽因近期饮食放纵而不愿去减肥俱乐部，但决定硬着头皮参加。两人约定六点在玛丽家见面，...,亚兹和玛丽今晚6点左右见面，一起去减肥俱乐部。他们估计吃得太多会被骂。
13,gold_00014,211,艾莉：嘿，你在大学吗？\n阿莉亚：是的\n卡米尔：我生病了 :/\n艾莉：天哪……这太糟糕了...,艾莉询问大家是否在大学，阿莉亚确认，卡米尔表示生病。艾莉随后向阿莉亚确认上课地点，得知在二楼...,艾莉的班级在二楼342教室。
14,gold_00015,212,内森：<file_video>\n亚伦：天哪！！！\n亚伦：😂😂😂😂\n亚伦：笑死我了\n亚...,内森分享了一段搞笑视频，亚伦大笑并调侃视频人物表情像自家猫拉屎。两人互相发送表情包，戏称这是...,内森和亚伦正在讨论内森发来的视频。
15,gold_00016,215,弗雷迪：你在奈飞上看什么？我刚看完《广告狂人》。\n凯莉：我刚看完《王冠》。\n弗雷迪：应该...,众人讨论奈飞剧集，提及《广告狂人》《王冠》等，对《纸牌屋》新季评价不一，并分享了对《老友记》...,弗雷迪、凯利、吉姆、格雷格、鲍勃、迈克、玛丽、艾伦和南希正在netflix上观看不同的节目。
16,gold_00017,244,琼斯：嘿。\n安吉丽娜：嘿。\n安吉丽娜：好久不见。你最近怎么样？\n琼斯：我很好。\n琼斯...,琼斯与安吉丽娜寒暄后，约定下午在城里见面，琼斯稍后将致电确认具体地点。,琼斯和安吉丽娜下午会在城里见面。
17,gold_00018,285,凯西：<file_photo>\n阿米莉亚：这些太漂亮了！！！是你自己做的吗？\n克里斯滕：...,凯西展示自制美甲，获阿米莉亚和克里斯滕称赞。因耗时近四小时，凯西婉拒了两人请求其帮忙做美甲的提议。,凯西买了新指甲油，自己做了指甲。她花了近4个小时，所以她不会帮朋友做指甲，因为耗时太长了。
18,gold_00019,319,苏：收到这条信息时给我打电话。\n苏：这很重要。\n史蒂夫：好的，我现在就给你打。,苏收到重要信息，要求史蒂夫立即回电，史蒂夫答应马上拨打。,史蒂夫正按照苏的要求给她打电话。
19,gold_00020,346,蒂米：你想邀请谁？\n杰玛：嗯，有你和你的约会对象 :)\n蒂米：约会对象还不确定，但我会去...,蒂米与杰玛讨论婚礼邀请名单，杰玛想邀请洛娜和米歇尔参加招待会，蒂米调侃她仍期待收到请柬，杰玛...,杰玛将邀请蒂米和他的约会对象，以及罗娜和米歇尔参加她的婚礼。
20,gold_00021,355,安：恭喜！！\n安：你们俩都表现得非常出色！\n苏：谢谢，安。\n朱莉：我很高兴终于结束了！...,安祝贺苏和朱莉表现出色，提议当晚庆祝，两人均欣然同意。,安、苏和朱莉做得很好，今晚他们会举行一个小小的庆祝活动。
21,gold_00022,367,史蒂夫：嗨，洗碗机已经送来了。\n妈妈：太好了，他们帮你安装好了吗？\n史蒂夫：是的，他们干...,史蒂夫告知妈妈洗碗机已送达并安装完毕，他称赞其美观安静。妈妈关心容量，史蒂夫表示虽不确定是否...,史蒂夫很高兴他装了一台新的洗碗机。
22,gold_00023,393,玛丽卡：你今天来吗？\n拉拉：来！\n玛丽卡：太好了！,玛丽卡询问拉拉今天是否前来，拉拉确认会来，玛丽卡对此表示高兴。,玛丽卡今天会来。
23,gold_00024,417,米兰达：嗨，斯蒂芬妮，我们能否取消明天的会议？\n斯蒂芬妮：又怎么了？发生什么事了？\n米兰...,米兰达因工作需取消明日会议，斯蒂芬妮质疑其过度劳累。米兰达辩称年轻医生皆如此，虽接近死亡却能...,米兰达不能去见斯蒂芬妮，因为她要工作。
24,gold_00025,432,哈维尔：嘿，你知道附近有没有员工会说英语的纹身店吗？\n朱迪：哦，有华沙墨水纹身店。\n哈维...,哈维尔询问附近是否有英语纹身店，朱迪推荐了华沙墨水店并展示其女友的纹身。得知价格为一千后，哈...,哈维尔最初很想在warsaw ink纹身，但价格太高了。他决定去哥伦比亚做纹身。
25,gold_00026,433,山姆：各位，你们拥有一家非常棒的酒店 😊\n杰西卡：谢谢山姆 😊\n迈克尔：谢谢，老兄\n山...,山姆称赞酒店并表示期待下月入住。迈克尔确认他们将于 8 月 15 日下午两点抵达，双方对再次...,山姆很喜欢杰西卡和迈克尔的酒店。他会在8月15日下午2点左右去那里。
26,gold_00027,442,特伦斯：到底怎么回事，丹尼。你拿了我的钱，对吧？:/\n丹尼尔：什么，你的钱？我为什么要……...,特伦斯误以为丹尼尔偷了他的钱并加以指责，随后发现钱是自己放错了地方。特伦斯道歉后，丹尼尔表示...,特伦斯指控丹尼尔偷了他的钱。后来他找到了钱，就向丹尼尔道歉。但是丹尼尔还在生气。
27,gold_00028,499,娜塔莎：嗨，我可以去 RER 接你。\n查尔斯：太好了。我刚落地。我想我大约下午 5 点 3...,娜塔莎将去 RER 接刚落地的查尔斯。查尔斯预计下午 5 点 30 分到达，并会在抵达韦西内...,查尔斯刚刚落地，他会在下午五点半到达rer，娜塔夏会在那里接他。
28,gold_00029,528,梅格：还在学校吗？\n安：我有额外的数学课。\n梅格：那我什么时候能见到你？\n安：我七点到家。,安因有额外数学课仍在学校，预计七点到家，梅格询问何时能见到她。,安还在学校，她7点会回家，这样她就可以和麦格见面了。
29,gold_00030,532,皮特：你刚才说想要什么口味的酸奶？我今天脑子像漏勺一样。\n珍：梨味，但只有他们有货才行。如...,皮特询问珍想要什么口味的酸奶，珍表示只要梨味，若无货则不买其他口味。皮特答应去查看。,如果商店里有梨味酸奶， 皮特会给珍买的。
30,gold_00031,536,克里斯蒂：派对之后你怎么样？\n凯蒂：真的很累……你呢？\n克里斯蒂：我也是。\n克里斯蒂：...,克里斯蒂和凯蒂在派对后都感到疲惫，但一致认为派对很棒，两人玩得很开心。,克里斯蒂和凯蒂在聚会后累了。他们都玩得很开心。
31,gold_00032,537,山姆：你明天工作吗？\n卡拉：不，明天是我的休息日。\n山姆：我下午有空，你想见面吗？\n卡...,山姆邀请明天休息的卡拉下午见面，两人约定两点在米恩伍德咖啡馆碰面，卡拉还推荐了那里的蛋糕。,卡拉明天有一天假。她将在下午两点在meanwood的一个咖啡馆和山姆见面。
32,gold_00033,544,乔安娜：想玩些游戏吗？\n桑迪：玩什么游戏？\n乔安娜：也许玩迪克西特？\n乔安娜：或者玩卡...,乔安娜提议玩迪克西特或卡卡颂，桑迪欣然同意，乔安娜将把这两款游戏带给桑迪。,琼娜将为桑迪带来一些像迪克西特和卡尔卡松这样的游戏。
33,gold_00034,548,史蒂夫：五分钟前买了梦剧院的新专辑。希望它不错。\n罗布：我桌上就有这张，准备第一次听。\n...,史蒂夫刚买了梦剧院新专辑，罗布桌上也有这张准备首听，两人约定稍后交流听后感。,史蒂夫和罗伯将在听完后谈论新的梦剧场专辑。
34,gold_00035,551,彼得：你能把你们美容店的链接发给我吗？\n乔伊：当然可以。\n乔伊：网址是 https://...,彼得向乔伊索要美容店链接，乔伊提供了网址并表示如有问题可随时提问，彼得确认收到并准备查看。,乔伊把她美容店的链接发给了彼得。
35,gold_00036,590,伊森：谁要去听索尔斯塔菲尔的演出？\n诺亚：索尔斯塔菲尔！什么时候？\n诺亚：我完全不知道他...,伊森提议 11 月 21 日观看索尔斯塔菲尔演出，利奥极力邀请，阿奇拒绝。诺亚因工作不确定能...,伊森和里奥要在21点11分去见索斯塔弗。诺亚也想去，但他可能得工作到很晚。
36,gold_00037,598,布拉德利：哈哈，看，一只猫闯入了古迪逊公园球场 <file_other>\n吉尔：哈哈哈哈\...,布拉德利分享了一只猫闯入古迪逊公园球场的视频，朱莉娅和吉尔觉得非常可爱，布拉德利称这是埃弗顿...,在埃弗顿的足球比赛中，一只可爱的小黑猫钻进了球场。
37,gold_00038,605,芭芭拉：我已经到家了，你可以过来。\n肖恩：我可以带狗来吗？\n扎克：我正在路上。\n芭芭拉...,芭芭拉告知已到家，肖恩询问能否带狗并获准，随后提出留宿过夜，芭芭拉欣然同意。,芭芭拉、肖恩和扎克今晚在芭芭拉家见面。肖恩会把狗带来的，肖恩和扎克会在这里过夜。
38,gold_00039,616,杰克：伙计，我刚刚抽到了一张TOTW卡！\n杰克：这是我今年第一张！\n汤姆：恭喜！\n汤姆...,杰克抽到今年首张 TOTW 卡，因阵容不合计划试用后出售。汤姆抽卡运气不佳，杰克安慰他游戏水...,杰克今年拿到了第一个totw ，汤姆的团队并不出色。
39,gold_00040,621,菲尔：晚上好，迪安娜！非常感谢你寄来的这张漂亮卡片，康斯坦丁非常高兴！\n菲尔：这副太阳镜也...,菲尔感谢迪安娜的卡片，并确认太阳镜非凯瑟琳或迪安娜所有。两人推测可能是阿德里安的，决定代为保管。,菲尔收到了迪安娜的一张卡片，康斯坦丁很开心。菲尔有副墨镜。蒂娜在后面收音机上面找到的。迪安娜...
40,gold_00041,635,梅尔：你好！最近怎么样？ \n格洛丽亚：嗨，梅尔！我们挺好的，就是日复一日的忙碌；) 你们...,梅尔与格洛丽亚通话，两人聊起孩子离家后的生活，并约定本周末在梅尔家举办烧烤。她们还讨论了梅尔...,格洛丽亚和梅尔计划星期六在梅尔家吃烧烤。他们很高兴，因为泰德的姐姐搬到了苏格兰。梅尔需要格洛...
41,gold_00042,649,卡兰：我的三星 S8 出问题了。\n韦德：具体是什么问题？\n卡兰：我只能看到黑屏。\n韦德...,卡兰的三星 S8 出现黑屏且曾过热，韦德提醒电池危险。卡兰因手机在保修期内，计划送店检查，并...,卡伦的三星s8过热了，所以他要去店里修理。
42,gold_00043,676,安娜：妈妈，我肚子疼得厉害。\n乔安娜：哦，天哪，你什么时候开始疼的？\n安娜：晚上开始的，...,安娜因腹痛向母亲求助，两人排查饮食原因未果。母亲建议观察或就医，安娜决定为其冲泡薄荷茶缓解，...,安娜夜里胃疼得厉害，但她不知道其中的原因。她的妈妈乔安娜会用新鲜的薄荷叶为她做热茶。
43,gold_00044,678,山姆：你在哪儿？\n凯特：楼下。\n山姆：这么快？\n凯特：当然，下来吧。\n杰夫：我们在接...,凯特告知山姆和杰夫，接待处旁小房间内有一位女士正在制作一个带有巨大阴茎、睾丸和巧克力头发的定...,凯特和杰夫在楼下接待处旁边的一个房间里。有位女士正在做杏仁蛋糕。
44,gold_00045,690,米娅：天哪，他一直在谈论那堵愚蠢的墙。\n珍妮弗：我觉得他只是老糊涂了。\n卡琳：不幸的是，...,众人认为特朗普并非老糊涂，而是利用民粹策略破坏世界秩序。尽管他愚蠢且固执，但大家决心不惜一切...,米亚、珍妮弗、卡琳和彼得不喜欢特朗普。
45,gold_00046,711,佩德罗：蝙蝠侠还是超人？\n亚历克斯：说实话……两个都不行。\n佩德罗：什么？\n亚历克斯：...,佩德罗询问亚历克斯更喜欢蝙蝠侠还是超人，亚历克斯表示更偏爱闪电侠。他解释闪电侠速度极快，甚至...,阿莱克斯更喜欢闪电侠，因为他的速度。
46,gold_00047,737,达米安：你在市中心吗？\n伊森：是的。\n伊森：怎么了？\n达米安：你能帮我买个烤肉串吗？\...,达米安因疲惫请求在市中心的朋友伊森帮忙买烤肉串。伊森虽不满其依赖行为，最终仍答应帮忙，达米安...,伊森会请达米安吃烤肉串，达米安今天过得很糟糕。
47,gold_00048,767,巴里：我打算去参加女性罢工游行，有人感兴趣吗？\n杰克：我有兴趣，已经和一些朋友做好了计划，...,巴里提议参加女性罢工游行，杰克和戴夫均表示参加并邀请同伴，众人约定中午在校园里碰头。,巴里、戴夫、凯利和杰克将于12点在校园附近集合，参加妇女罢工。
48,gold_00049,799,玛莎：嘿，我能问你一个问题吗？\n奥菲莉亚：我们认识吗？\n玛莎：我们不认识，但你不介意我问...,玛莎询问奥菲莉亚个人资料中佩戴的美瞳品牌，奥菲莉亚推荐了“疯狂美瞳”，并称赞其价格合理、发货...,玛莎喜欢奥菲莉娅的眼镜，想买类似的，奥菲莉娅是从crazy lens上买的。
49,gold_00050,800,琳达：嗨，爸爸，我想给妈妈买花！但我记不起她喜欢哪一种了 :(\n迈克尔：嗯，我相信她喜欢所...,琳达在花卉市场想给妈妈买花，因记不清喜好向父亲求助。经父亲建议并查看图片，最终决定购买妈妈喜...,琳达想给她妈妈买花，问迈克尔她喜欢哪种花。迈克尔建议琳达买小苍兰。

In [17]:
# Cell 16: Inspect TS outputs

if not df.empty:
    inspection_columns = [
        "id",
        "test_index",
        "dialogue",
        "translated_dialogue",
        "final_summary",
        "reference_english_summary",
        "reference_chinese_summary",
    ]

    inspection_df = df[inspection_columns].copy()
    display(inspection_df)
else:
    print("No results found.")

,id,test_index,dialogue,translated_dialogue,final_summary,reference_english_summary,reference_chinese_summary
0,gold_00001,23,"Anne: You were right, he was lying to me :/\nI...",安妮：你是对的，他对我撒谎了 :/\n艾琳：哦不，发生什么事了？\n简：谁？那个马克吗？\n...,安妮发现马克在年龄上对她撒谎，他自称三十岁，但护照显示实际为四十岁。尽管艾琳质疑此事的重要性...,Mark lied to Anne about his age. Mark is 40.,马克向安妮隐瞒了自己的年龄。他40岁了。
1,gold_00002,30,"Mary: hey, im kinda broke, lend me a few box\r...",玛丽：嘿，我手头有点紧，借我几盒吧。\n卡特：好的，给我一小时，我在火车站。\n玛丽：太好了...,玛丽因手头紧向卡特借几盒，卡特答应一小时后在火车站交付，玛丽表示感谢。,Mary ran out of money. Carter is going to lend...,玛丽的钱用完了，卡特打算一小时后借给她一点。
2,gold_00003,39,"Tina: I'll tell you something, this Emirate st...",蒂娜：我告诉你，这家阿联酋航空的机组人员看起来太棒了，就像电影明星一样。\n阿拉：哦，是的，...,蒂娜称赞阿联酋航空机组形象，但抱怨机场滞留及航班延误。阿拉表示同情，随后告知要去开会，两人约...,Tina will catch the evening flight back home. ...,蒂娜将乘晚间航班回家。阿拉正在去开会的路上。她会让蒂娜知道事情的进展。
3,gold_00004,65,Ana: You sleeping?\r\nCatherine: Not yet.\r\nA...,安娜：你睡着了吗？\n凯瑟琳：还没。\n安娜：明天想去探望奶奶吗？我想她了。\n凯瑟琳：好啊...,安娜提议明天探望奶奶，凯瑟琳欣然同意，并约定醒来后联系，随后两人互道晚安。,Ana wants to visit grandma tomorrow. Catherine...,安娜明天想去看望奶奶。凯瑟琳会和她一起去。她起床后会给安娜打电话。
4,gold_00005,66,Joyce: Check this out!\r\nJoyce: <link>\r\nMic...,乔伊斯：快看看这个！\n乔伊斯：<link>\n迈克尔：太便宜了！\n埃德森：不可能！我现在...,乔伊斯分享了一个链接，迈克尔感叹价格太便宜，埃德森则决定立即订票。,Edson is booking his ticket now.,埃德森正在订票。
5,gold_00006,67,Jane: google maps says it is at least 3h <file...,简：谷歌地图显示至少需要 3 小时 <file_other>\n史蒂文：我以前 2 小时就到...,简提议将见面时间改为 4 点半，史蒂文同意。两人确认将在主入口见面。,Jane wants to leave at 4.30 instead of 5 becau...,简想4点半就走，而不是等到5点，因为谷歌地图提示300公里的车程至少需要3小时，她不想迟到。...
6,gold_00007,78,"Fiona: Are you free?\r\nTina: Yes, what's up?\...",菲奥娜：你有空吗？\n蒂娜：有空，怎么了？\n菲奥娜：我正在为克里斯准备一顿丰盛的晚餐，我在...,菲奥娜邀请蒂娜帮忙为克里斯做挞。菲奥娜已买好挞皮，但馅料做成了柠檬炒蛋。蒂娜安慰她，并指出加...,Fiona wants to prepare dinner for Chris. She i...,菲奥娜想为克里斯准备晚餐。她想起了蒂娜做的馅饼。蒂娜会帮她做的。
7,gold_00008,86,Olafur: are we doing anything for New Year's E...,奥拉夫：我们除夕夜有什么安排吗？\n娜塔莉：我在想一些高雅的活动，比如歌剧之类的。\n佐伊：...,三人讨论除夕安排，娜塔莉提议高雅活动，奥拉夫建议派对。最终他们选定苏荷区一家俱乐部，并决定立...,"Nathalie, Olafur and Zoe are planning the New ...",娜塔莉、奥拉维尔和佐伊正在做新年前夜的计划。娜塔莉想要有格调的。但奥拉维尔不喜欢歌剧。他们想...
8,gold_00009,120,"John: wanna go see ""A Star is Born"" on Wed?\r\...",约翰：周三想看《一个明星的诞生》吗？\n琼：抱歉，不行。\n琼：超级忙。\n琼：没时间做任何...,约翰邀请琼周三看电影被拒，因琼太忙。两人最终约定周四晚八点观看《一个明星的诞生》，约翰将查询...,"Joan and John are going to watch ""A Star is Bo...",琼和约翰星期四晚上8点左右去看《一个明星的诞生》。
9,gold_00010,137,Peyton: I have been asking you to bring that v...,佩顿：我一直让你帮我带那个电子游戏。\n卡梅伦：亲爱的，我实在没有足够的时间回家。\n佩顿：...,佩顿催促卡梅伦带游戏回家，卡梅伦因在外地需停留一周无法带回。佩顿建议快递，卡梅伦抱怨其刻薄，...,Peyton is expecting Cameron to bring the video...,佩顿希望卡梅隆能带游戏机过来，但是卡梅隆可能还要再缺席一周。
10,gold_00011,139,Paul: I just came back home\r\nPaul: What a bu...,保罗：我刚回到家。\n保罗：真是忙碌的一天。\n保罗：我忘了我的物理治疗。\n艾玛：哦，不。...,保罗忙完回家，因错过理疗将改约。艾玛深夜才归，保罗主动提出为她备餐，艾玛欣然接受。,Paul forgot about his physiotherapy and he wil...,保罗忘记去做理疗了，得重新预约。艾玛午夜后回家，所以保罗会给她准备一些吃的。
11,gold_00012,192,"Harris: How are U?\r\nLena: Fine, U?\r\nHarris...",哈里斯：你好吗？\n莱娜：还好，你呢？\n哈里斯：不太行。\n莱娜：怎么了？\n哈里斯：我的...,哈里斯告知莱娜，其好友青木昨日去世，死因尚不明。两人谈及青木住在密歇根州，哈里斯已数月未见。...,"Harris' friend, Aoki, who lives in Michigan, d...",哈里斯的朋友青木住在密歇根州，昨天去世了。哈里斯有几个月没见她了。
12,gold_00013,210,Yaz: Going to slimming club tonight?\r\nMary: ...,雅兹：今晚要去减肥俱乐部吗？\n玛丽：嗯，我其实不想去，但确实应该去。不过我最近实在太放纵了...,雅兹和玛丽虽因近期饮食放纵而不愿去减肥俱乐部，但决定硬着头皮参加。两人约定六点在玛丽家见面，...,Yaz and Mary are meeting tonight around 6 and ...,亚兹和玛丽今晚6点左右见面，一起去减肥俱乐部。他们估计吃得太多会被骂。
13,gold_00014,211,"Ellie: hey, are you at the university?\r\nAali...",艾莉：嘿，你在大学吗？\n阿莉亚：是的\n卡米尔：我生病了 :/\n艾莉：天哪……这太糟糕了...,艾莉询问大家是否在大学，阿莉亚确认，卡米尔表示生病。艾莉随后向阿莉亚确认上课地点，得知在二楼...,Ellie's class is in 342 on the second floor.,艾莉的班级在二楼342教室。
14,gold_00015,212,Nathan: <file_video>\r\nAaron: OMG!!! \r\nAaro...,内森：<file_video>\n亚伦：天哪！！！\n亚伦：😂😂😂😂\n亚伦：笑死我了\n亚...,内森分享了一段搞笑视频，亚伦大笑并调侃视频人物表情像自家猫拉屎。两人互相发送表情包，戏称这是...,Nathan and Aaron are discussing a video which ...,内森和亚伦正在讨论内森发来的视频。
15,gold_00016,215,Freddie: What are you watching on Netflix? I'v...,弗雷迪：你在奈飞上看什么？我刚看完《广告狂人》。\n凯莉：我刚看完《王冠》。\n弗雷迪：应该...,众人讨论奈飞剧集，提及《广告狂人》《王冠》等，对《纸牌屋》新季评价不一，并分享了对《老友记》...,"Freddie, Kelly, Jim, Greg, Bob, Mike, Mary, Al...",弗雷迪、凯利、吉姆、格雷格、鲍勃、迈克、玛丽、艾伦和南希正在netflix上观看不同的节目。
16,gold_00017,244,Jones: Hey.\r\nAngelina: Hey.\r\nAngelina: Lon...,琼斯：嘿。\n安吉丽娜：嘿。\n安吉丽娜：好久不见。你最近怎么样？\n琼斯：我很好。\n琼斯...,琼斯与安吉丽娜寒暄后，约定下午在城里见面，琼斯稍后将致电确认具体地点。,Jones and Angelina will meet in town in the af...,琼斯和安吉丽娜下午会在城里见面。
17,gold_00018,285,Casey: <file_photo>\r\nAmelia: these are so ni...,凯西：<file_photo>\n阿米莉亚：这些太漂亮了！！！是你自己做的吗？\n克里斯滕：...,凯西展示自制美甲，获阿米莉亚和克里斯滕称赞。因耗时近四小时，凯西婉拒了两人请求其帮忙做美甲的提议。,Casey got a new nail polish and did her nails ...,凯西买了新指甲油，自己做了指甲。她花了近4个小时，所以她不会帮朋友做指甲，因为耗时太长了。
18,gold_00019,319,Sue: Call me when you get this.\r\nSue: it's i...,苏：收到这条信息时给我打电话。\n苏：这很重要。\n史蒂夫：好的，我现在就给你打。,苏收到重要信息，要求史蒂夫立即回电，史蒂夫答应马上拨打。,Steve is calling Sue at her request.,史蒂夫正按照苏的要求给她打电话。
19,gold_00020,346,"Timmy: Who do u wanna invite?\r\nGemma: Well, ...",蒂米：你想邀请谁？\n杰玛：嗯，有你和你的约会对象 :)\n蒂米：约会对象还不确定，但我会去...,蒂米与杰玛讨论婚礼邀请名单，杰玛想邀请洛娜和米歇尔参加招待会，蒂米调侃她仍期待收到请柬，杰玛...,"Gemma will invite Timmy and his Date, as well ...",杰玛将邀请蒂米和他的约会对象，以及罗娜和米歇尔参加她的婚礼。
20,gold_00021,355,"Ann: Congratulations!!\r\nAnn: You did great, ...",安：恭喜！！\n安：你们俩都表现得非常出色！\n苏：谢谢，安。\n朱莉：我很高兴终于结束了！...,安祝贺苏和朱莉表现出色，提议当晚庆祝，两人均欣然同意。,"Ann, Sue and Julie did a great job and they wi...",安、苏和朱莉做得很好，今晚他们会举行一个小小的庆祝活动。
21,gold_00022,367,Steve: hiya the dishwasher has turned up\r\nMu...,史蒂夫：嗨，洗碗机已经送来了。\n妈妈：太好了，他们帮你安装好了吗？\n史蒂夫：是的，他们干...,史蒂夫告知妈妈洗碗机已送达并安装完毕，他称赞其美观安静。妈妈关心容量，史蒂夫表示虽不确定是否...,Steve is happy that he got a new dishwasher in...,史蒂夫很高兴他装了一台新的洗碗机。
22,gold_00023,393,Marika: Are you coming today?\r\nLara: Yes!\r\...,玛丽卡：你今天来吗？\n拉拉：来！\n玛丽卡：太好了！,玛丽卡询问拉拉今天是否前来，拉拉确认会来，玛丽卡对此表示高兴。,Marika is coming today.,玛丽卡今天会来。
23,gold_00024,417,"Miranda: Hi S, could we cancel tomorrow's meet...",米兰达：嗨，斯蒂芬妮，我们能否取消明天的会议？\n斯蒂芬妮：又怎么了？发生什么事了？\n米兰...,米兰达因工作需取消明日会议，斯蒂芬妮质疑其过度劳累。米兰达辩称年轻医生皆如此，虽接近死亡却能...,Miranda can't make her meeting with Stephanie ...,米兰达不能去见斯蒂芬妮，因为她要工作。
24,gold_00025,432,Javier: Hey do you know any tattoo parlors ove...,哈维尔：嘿，你知道附近有没有员工会说英语的纹身店吗？\n朱迪：哦，有华沙墨水纹身店。\n哈维...,哈维尔询问附近是否有英语纹身店，朱迪推荐了华沙墨水店并展示其女友的纹身。得知价格为一千后，哈...,Javier was initially eager to have a tatoo don...,哈维尔最初很想在warsaw ink纹身，但价格太高了。他决定去哥伦比亚做纹身。
25,gold_00026,433,"Sam: You own a really nice hotel, guys 😊\r\nJe...",山姆：各位，你们拥有一家非常棒的酒店 😊\n杰西卡：谢谢山姆 😊\n迈克尔：谢谢，老兄\n山...,山姆称赞酒店并表示期待下月入住。迈克尔确认他们将于 8 月 15 日下午两点抵达，双方对再次...,Sam appreciates the hotel owned by Jessica and...,山姆很喜欢杰西卡和迈克尔的酒店。他会在8月15日下午2点左右去那里。
26,gold_00027,442,"Terence: What the hell, Danny. You took my mon...",特伦斯：到底怎么回事，丹尼。你拿了我的钱，对吧？:/\n丹尼尔：什么，你的钱？我为什么要……...,特伦斯误以为丹尼尔偷了他的钱并加以指责，随后发现钱是自己放错了地方。特伦斯道歉后，丹尼尔表示...,Terence accused Daniel of taking his money. Te...,特伦斯指控丹尼尔偷了他的钱。后来他找到了钱，就向丹尼尔道歉。但是丹尼尔还在生气。
27,gold_00028,499,"Natacha: hi, i can come and pick you up at the...",娜塔莎：嗨，我可以去 RER 接你。\n查尔斯：太好了。我刚落地。我想我大约下午 5 点 3...,娜塔莎将去 RER 接刚落地的查尔斯。查尔斯预计下午 5 点 30 分到达，并会在抵达韦西内...,Charles has just landed and he will be at RER ...,查尔斯刚刚落地，他会在下午五点半到达rer，娜塔夏会在那里接他。
28,gold_00029,528,Meg: still at school?\r\nAnn: i have extra mat...,梅格：还在学校吗？\n安：我有额外的数学课。\n梅格：那我什么时候能见到你？\n安：我七点到家。,安因有额外数学课仍在学校，预计七点到家，梅格询问何时能见到她。,Ann is still at school. She will be home at 7 ...,安还在学校，她7点会回家，这样她就可以和麦格见面了。
29,gold_00030,532,Pete: What flavour yogurt did you want again? ...,皮特：你刚才说想要什么口味的酸奶？我今天脑子像漏勺一样。\n珍：梨味，但只有他们有货才行。如...,皮特询问珍想要什么口味的酸奶，珍表示只要梨味，若无货则不买其他口味。皮特答应去查看。,Pete will get a pear yogurt for Jen if they ha...,如果商店里有梨味酸奶， 皮特会给珍买的。
30,gold_00031,536,Christie: how are you after the party?\r\nKati...,克里斯蒂：派对之后你怎么样？\n凯蒂：真的很累……你呢？\n克里斯蒂：我也是。\n克里斯蒂：...,克里斯蒂和凯蒂在派对后都感到疲惫，但一致认为派对很棒，两人玩得很开心。,Christie and Katie are tired after the party. ...,克里斯蒂和凯蒂在聚会后累了。他们都玩得很开心。
31,gold_00032,537,"Sam: Are you working tomorrow?\r\nCarla: No, i...",山姆：你明天工作吗？\n卡拉：不，明天是我的休息日。\n山姆：我下午有空，你想见面吗？\n卡...,山姆邀请明天休息的卡拉下午见面，两人约定两点在米恩伍德咖啡馆碰面，卡拉还推荐了那里的蛋糕。,Carla has a day off tomorrow. She will meet Sa...,卡拉明天有一天假。她将在下午两点在meanwood的一个咖啡馆和山姆见面。
32,gold_00033,544,Joana: wana play some games?\r\nSandy: what ga...,乔安娜：想玩些游戏吗？\n桑迪：玩什么游戏？\n乔安娜：也许玩迪克西特？\n乔安娜：或者玩卡...,乔安娜提议玩迪克西特或卡卡颂，桑迪欣然同意，乔安娜将把这两款游戏带给桑迪。,Joana will bring Sandy some games like dixit a...,琼娜将为桑迪带来一些像迪克西特和卡尔卡松这样的游戏。
33,gold_00034,548,Steve: Bought the new Dream Theater album 5 mi...,史蒂夫：五分钟前买了梦剧院的新专辑。希望它不错。\n罗布：我桌上就有这张，准备第一次听。\n...,史蒂夫刚买了梦剧院新专辑，罗布桌上也有这张准备首听，两人约定稍后交流听后感。,Steve and Rob will talk about new Dream Theate...,史蒂夫和罗伯将在听完后谈论新的梦剧场专辑。
34,gold_00035,551,Peter: Can you send me the link of your beauty...,彼得：你能把你们美容店的链接发给我吗？\n乔伊：当然可以。\n乔伊：网址是 https://...,彼得向乔伊索要美容店链接，乔伊提供了网址并表示如有问题可随时提问，彼得确认收到并准备查看。,Joy sent Peter the link to her beauty shop.,乔伊把她美容店的链接发给了彼得。
35,gold_00036,590,Ethan: who's going to see solstafir?\r\nNoah: ...,伊森：谁要去听索尔斯塔菲尔的演出？\n诺亚：索尔斯塔菲尔！什么时候？\n诺亚：我完全不知道他...,伊森提议 11 月 21 日观看索尔斯塔菲尔演出，利奥极力邀请，阿奇拒绝。诺亚因工作不确定能...,Ethan and Leo are going to see Sólstafir on 21...,伊森和里奥要在21点11分去见索斯塔弗。诺亚也想去，但他可能得工作到很晚。
36,gold_00037,598,Bradley: haha look a cat invaded the pitch at ...,布拉德利：哈哈，看，一只猫闯入了古迪逊公园球场 <file_other>\n吉尔：哈哈哈哈\...,布拉德利分享了一只猫闯入古迪逊公园球场的视频，朱莉娅和吉尔觉得非常可爱，布拉德利称这是埃弗顿...,A sweet little black cat got into the pitch du...,在埃弗顿的足球比赛中，一只可爱的小黑猫钻进了球场。
37,gold_00038,605,"Barbara: I'm home already, you can come over\r...",芭芭拉：我已经到家了，你可以过来。\n肖恩：我可以带狗来吗？\n扎克：我正在路上。\n芭芭拉...,芭芭拉告知已到家，肖恩询问能否带狗并获准，随后提出留宿过夜，芭芭拉欣然同意。,"Barbara, Sean and Zac are meeting at Barbara's...",芭芭拉、肖恩和扎克今晚在芭芭拉家见面。肖恩会把狗带来的，肖恩和扎克会在这里过夜。
38,gold_00039,616,"Jake: dude, I just pulled a TOTW\nJake: my fir...",杰克：伙计，我刚刚抽到了一张TOTW卡！\n杰克：这是我今年第一张！\n汤姆：恭喜！\n汤姆...,杰克抽到今年首张 TOTW 卡，因阵容不合计划试用后出售。汤姆抽卡运气不佳，杰克安慰他游戏水...,Jake has got his first TOTW this year. Tom doe...,杰克今年拿到了第一个totw ，汤姆的团队并不出色。
39,gold_00040,621,Phil: Good evening Deana! Many thanks for this...,菲尔：晚上好，迪安娜！非常感谢你寄来的这张漂亮卡片，康斯坦丁非常高兴！\n菲尔：这副太阳镜也...,菲尔感谢迪安娜的卡片，并确认太阳镜非凯瑟琳或迪安娜所有。两人推测可能是阿德里安的，决定代为保管。,Phil received a card from Deana. Constantine w...,菲尔收到了迪安娜的一张卡片，康斯坦丁很开心。菲尔有副墨镜。蒂娜在后面收音机上面找到的。迪安娜...
40,gold_00041,635,Mell: Hi there! How are you doing?\r\nGloria: ...,梅尔：你好！最近怎么样？ \n格洛丽亚：嗨，梅尔！我们挺好的，就是日复一日的忙碌；) 你们...,梅尔与格洛丽亚通话，两人聊起孩子离家后的生活，并约定本周末在梅尔家举办烧烤。她们还讨论了梅尔...,Gloria and Mell plan to have a barbeque at Mel...,格洛丽亚和梅尔计划星期六在梅尔家吃烧烤。他们很高兴，因为泰德的姐姐搬到了苏格兰。梅尔需要格洛...
41,gold_00042,649,Callan: Something's wrong with my Samsung S8.\...,卡兰：我的三星 S8 出问题了。\n韦德：具体是什么问题？\n卡兰：我只能看到黑屏。\n韦德...,卡兰的三星 S8 出现黑屏且曾过热，韦德提醒电池危险。卡兰因手机在保修期内，计划送店检查，并...,"Callan's Samsung S8 overheats, so he's going t...",卡伦的三星s8过热了，所以他要去店里修理。
42,gold_00043,676,"Anna: Mum, I have a awful stomachache.\r\nJoan...",安娜：妈妈，我肚子疼得厉害。\n乔安娜：哦，天哪，你什么时候开始疼的？\n安娜：晚上开始的，...,安娜因腹痛向母亲求助，两人排查饮食原因未果。母亲建议观察或就医，安娜决定为其冲泡薄荷茶缓解，...,Anna got an awful stomachache at night but she...,安娜夜里胃疼得厉害，但她不知道其中的原因。她的妈妈乔安娜会用新鲜的薄荷叶为她做热茶。
43,gold_00044,678,Sam: Where are you?\nKate: downstairs\nSam: al...,山姆：你在哪儿？\n凯特：楼下。\n山姆：这么快？\n凯特：当然，下来吧。\n杰夫：我们在接...,凯特告知山姆和杰夫，接待处旁小房间内有一位女士正在制作一个带有巨大阴茎、睾丸和巧克力头发的定...,Kate and Jeff are downstairs in a room next to...,凯特和杰夫在楼下接待处旁边的一个房间里。有位女士正在做杏仁蛋糕。
44,gold_00045,690,"Mia: God, he keeps talking about the stupid wa...",米娅：天哪，他一直在谈论那堵愚蠢的墙。\n珍妮弗：我觉得他只是老糊涂了。\n卡琳：不幸的是，...,众人认为特朗普并非老糊涂，而是利用民粹策略破坏世界秩序。尽管他愚蠢且固执，但大家决心不惜一切...,"Mia, Jennifer, Karine and Peter do not like Tr...",米亚、珍妮弗、卡琳和彼得不喜欢特朗普。
45,gold_00046,711,Pedro: batman or superman??\r\nAlex: honestly....,佩德罗：蝙蝠侠还是超人？\n亚历克斯：说实话……两个都不行。\n佩德罗：什么？\n亚历克斯：...,佩德罗询问亚历克斯更喜欢蝙蝠侠还是超人，亚历克斯表示更偏爱闪电侠。他解释闪电侠速度极快，甚至...,Alex prefers the Flash to Barman and Superman ...,阿莱克斯更喜欢闪电侠，因为他的速度。
46,gold_00047,737,Damian: are you downtown?\r\nEthan: yes\r\nEth...,达米安：你在市中心吗？\n伊森：是的。\n伊森：怎么了？\n达米安：你能帮我买个烤肉串吗？\...,达米安因疲惫请求在市中心的朋友伊森帮忙买烤肉串。伊森虽不满其依赖行为，最终仍答应帮忙，达米安...,Ethan will buy Damian a kebab. Damian had a ba...,伊森会请达米安吃烤肉串，达米安今天过得很糟糕。
47,gold_00048,767,"Barry: I'm gonna go march in Women's strike, a...",巴里：我打算去参加女性罢工游行，有人感兴趣吗？\n杰克：我有兴趣，已经和一些朋友做好了计划，...,巴里提议参加女性罢工游行，杰克和戴夫均表示参加并邀请同伴，众人约定中午在校园里碰头。,"Barry, Dave, Kelly, and Jake will meet around ...",巴里、戴夫、凯利和杰克将于12点在校园附近集合，参加妇女罢工。
48,gold_00049,799,"Martha: Hey, can I ask you a question?\r\nOphe...",玛莎：嘿，我能问你一个问题吗？\n奥菲莉亚：我们认识吗？\n玛莎：我们不认识，但你不介意我问...,玛莎询问奥菲莉亚个人资料中佩戴的美瞳品牌，奥菲莉亚推荐了“疯狂美瞳”，并称赞其价格合理、发货...,Martha likes Ophelia's lenses and wants to buy...,玛莎喜欢奥菲莉娅的眼镜，想买类似的，奥菲莉娅是从crazy lens上买的。
49,gold_00050,800,"Linda: Hi Dad, I want to buy flowers for mum! ...",琳达：嗨，爸爸，我想给妈妈买花！但我记不起她喜欢哪一种了 :(\n迈克尔：嗯，我相信她喜欢所...,琳达在花卉市场想给妈妈买花，因记不清喜好向父亲求助。经父亲建议并查看图片，最终决定购买妈妈喜...,Linda wants to buy flowers for her mother and ...,琳达想给她妈妈买花，问迈克尔她喜欢哪种花。迈克尔建议琳达买小苍兰。