# Summarize-then-Translate Pipeline for English-to-Chinese Dialogue Summarization

This notebook implements a local Summarize-then-Translate baseline for English-to-Chinese cross-lingual dialogue summarization.

The ST pipeline uses two local small language model agents. Agent 1 reads the original English dialogue and generates a concise English summary. Agent 2 then translates the English summary into Chinese. The final output is a concise Chinese summary.

```text
English Dialogue
→ Agent 1: English Summarization Agent
→ Agent 2: Chinese Translation Agent
→ Final Chinese Summary
```

The pipeline consists of two agents:

```text
Agent 1: English Summarization Agent
Input: original English dialogue
Output: concise English summary

Agent 2: Chinese Translation Agent
Input: English summary from Agent 1
Output: final Chinese summary
```
This setup is used as a Summarize-then-Translate baseline. Unlike the Direct pipeline, ST explicitly creates an intermediate English summary before producing the Chinese summary. This allows us to inspect whether errors come from the summarization stage or the translation stage.

The local small language model is served through Ollama. The notebook controls the prompt design, agent workflow, input/output processing, intermediate output inspection, and result saving.

## 0. Local Ollama Setup

Before running this notebook, install Ollama and download the local model used for the Summarize-then-Translate baseline.

### Recommended model setup

This notebook uses one local small language model through Ollama for both agents:

- Agent 1: English Summarization Agent
- Agent 2: Chinese Translation Agent

```bash
ollama pull qwen3.5:27b
```

If qwen3.5:27b is too slow on your machine, you can use a smaller model for testing:

```bash
ollama pull "qwen3.5:9b"
```

Make sure the model names in the notebook match the models installed in Ollama:

```bash
SUMMARIZATION_MODEL = "qwen3.5:27b"
TRANSLATION_MODEL = "qwen3.5:27b"
```

You can check downloaded models with:

```bash
ollama list
```

You can check currently loaded models with:

```bash
ollama ps
```

If the Ollama server is not running, start it with:

```bash
ollama serve
```

On macOS, opening the Ollama app usually starts the local server automatically.

In [1]:
# Cell 1: Install required Python packages.
# Run this only once if the packages are not installed

!pip install requests pandas tqdm

Requirement already satisfied: requests in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (2.33.1)
Requirement already satisfied: pandas in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (2.3.3)
Requirement already satisfied: tqdm in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from requests) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from requests) (2026.4.22)
Requirement already satisfied: numpy>=1.22.4 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: colorama in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\flexboy\anaconda3\envs\yunu\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
# Cell 2: Imports and global configuration

import json
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests
import pandas as pd
from tqdm.auto import tqdm

OLLAMA_HOST = "http://localhost:11434"

# ST models
SUMMARIZATION_MODEL = "gemma3:27b"
TRANSLATION_MODEL = "gemma3:27b"

DEFAULT_TEMPERATURE = 0.2
DEFAULT_NUM_CTX = 8192

# window project path
PROJECT_ROOT = Path(
    r"C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu"
)

# Gold set path
GOLD_SET_PATH = PROJECT_ROOT / "gold_set_50_zh_XSAMSum_bart.json"

# Output directory
OUTPUT_DIR = PROJECT_ROOT
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Output files for ST baseline
FULL_OUTPUT_PATH = OUTPUT_DIR / "st_gemma27b_50samples.jsonl"
FINAL_CSV_PATH = OUTPUT_DIR / "st_gemma27b_50samples.csv"
ERROR_OUTPUT_PATH = OUTPUT_DIR / "st_gemma27b_50samples_errors.jsonl"

print("Gold set path:", GOLD_SET_PATH)
print("Output directory:", OUTPUT_DIR)
print("Full JSONL output path:", FULL_OUTPUT_PATH)
print("Final CSV output path:", FINAL_CSV_PATH)
print("Error output path:", ERROR_OUTPUT_PATH)

Gold set path: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\gold_set_50_zh_XSAMSum_bart.json
Output directory: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu
Full JSONL output path: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\st_gemma27b_50samples.jsonl
Final CSV output path: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\st_gemma27b_50samples.csv
Error output path: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\st_gemma27b_50samples_errors.jsonl

In [3]:
print(GOLD_SET_PATH.exists())

True

In [4]:
# Cell 3: Check whether Ollama is running

def check_ollama_server() -> bool:
    try:
        response = requests.get(f"{OLLAMA_HOST}/api/tags", timeout=10)
        response.raise_for_status()
        models = response.json().get("models", [])

        print("Ollama server is running.")
        print(f"Downloaded models: {[m.get('name') for m in models]}")

        return True

    except Exception as e:
        print("Could not connect to Ollama.")
        print("Make sure Ollama is installed and running.")
        print("Try running this in Terminal:")
        print("  ollama serve")
        print()
        print("Error:", repr(e))

        return False


_ = check_ollama_server()

Ollama server is running.
Downloaded models: ['gemma3:27b', 'qwen3.5:27b']

In [5]:
# Cell 4: Ollama API helper

def call_ollama(
    model: str,
    prompt: str,
    system: Optional[str] = None,
    temperature: float = DEFAULT_TEMPERATURE,
    num_ctx: int = DEFAULT_NUM_CTX,
    timeout: int = 900,
) -> str:
    """Call Ollama's local chat API and return the assistant content."""

    messages = []

    if system:
        messages.append({"role": "system", "content": system})

    messages.append({"role": "user", "content": prompt})

    payload = {
        "model": model,
        "messages": messages,
        "stream": False,
        "options": {
            "temperature": temperature,
            "num_ctx": num_ctx,
            "num_predict": 1024,
        },
        "think": False,
    }

    response = requests.post(
        f"{OLLAMA_HOST}/api/chat",
        json=payload,
        timeout=timeout,
    )
    response.raise_for_status()

    data = response.json()
    content = data.get("message", {}).get("content", "")

    if content is None:
        content = ""

    return content.strip()

## 1. Prompt Templates

Each agent is defined as:

```text
Agent = model + role-specific prompt + input/output format
```

In the first version, we use a fixed workflow rather than a fully autonomous agent system.

In [6]:
# Cell 5: ST prompt templates

ENGLISH_SUMMARIZATION_PROMPT = """You are an English dialogue summarization agent.

Your task is to read the following English dialogue and generate a concise English summary.

Requirements:
- Summarize the main information in the dialogue.
- Write the summary in English.
- Keep the summary concise and faithful to the dialogue.
- Do not translate into Chinese.
- Do not add information that is not stated or clearly implied.
- Do not explain your reasoning.
- Output only the English summary.

Conciseness: 
- For simple dialogues, write one short English sentence.
- For complex dialogues, write at most two short English sentences.

English dialogue:
{dialogue}

English summary:
"""


CHINESE_TRANSLATION_PROMPT = """You are a Chinese translation agent.

Your task is to translate the English summary into Chinese.

Requirements:
- Translate the English summary into natural Chinese.
- Preserve the meaning of the English summary.
- Do not add new information.
- Do not remove important information.
- Do not explain your reasoning.
- Output only the final Chinese summary.
- Translate all English proper nouns, including speaker names, into standard Chinese transliteration.

STRICT TRANSLATION RULE:
- You MUST translate ALL English proper nouns and speaker names into standard Chinese characters.
- ABSOLUTELY NO English letters or names should appear in the final Chinese summary.

English summary:
{english_summary}

Chinese summary:
"""

In [7]:
# Cell 6: JSONL utility functions

def append_jsonl(record: Dict[str, Any], path: Path) -> None:
    """Append one record to a JSONL file."""
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def load_jsonl(path: Path) -> List[Dict[str, Any]]:
    """Load a JSONL file into a list of dictionaries."""
    if not path.exists():
        return []

    records = []

    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            if line:
                records.append(json.loads(line))

    return records


def load_processed_ids(path: Path) -> set:
    """Return IDs that have already been processed."""
    records = load_jsonl(path)

    return {str(record["id"]) for record in records if "id" in record}

In [8]:
# Cell 7: ST agent functions

def fill_prompt(template: str, replacements: Dict[str, str]) -> str:
    """Replace named placeholders in the prompt."""
    prompt = template

    for key, value in replacements.items():
        prompt = prompt.replace("{" + key + "}", value)

    return prompt


def english_summarization_agent(dialogue: str) -> str:
    """Agent 1: English dialogue -> English summary."""
    prompt = fill_prompt(
        ENGLISH_SUMMARIZATION_PROMPT,
        {
            "dialogue": dialogue,
        },
    )

    response = call_ollama(
        model=SUMMARIZATION_MODEL,
        prompt=prompt,
        temperature=0.2,
    )

    return response.strip()


def chinese_translation_agent(english_summary: str) -> str:
    """Agent 2: English summary -> Chinese summary."""
    prompt = fill_prompt(
        CHINESE_TRANSLATION_PROMPT,
        {
            "english_summary": english_summary,
        },
    )

    response = call_ollama(
        model=TRANSLATION_MODEL,
        prompt=prompt,
        temperature=0.2,
    )

    return response.strip()

## 2. Agent Functions

Each function corresponds to one agent in the pipeline.

In [9]:
# Cell 8: ST pipeline

def run_st_pipeline(example: Dict[str, Any], verbose: bool = True) -> Dict[str, Any]:
    """Run the Summarize-then-Translate pipeline."""

    sample_id = str(example.get("id", "unknown"))
    dialogue = example["dialogue"]

    reference_english_summary = example.get("reference_english_summary", "")
    reference_chinese_summary = example.get("reference_chinese_summary", "")

    # Agent 1: English dialogue -> English summary
    english_summary = english_summarization_agent(dialogue)

    if verbose:
        print("\n" + "=" * 80)
        print(f"Sample ID: {sample_id}")
        print("=== Agent 1 Output: English Summary ===")
        print(english_summary)
        print("=" * 80 + "\n")

    # Agent 2: English summary -> Chinese summary
    final_chinese_summary = chinese_translation_agent(english_summary)

    if verbose:
        print("=== Agent 2 Output: Chinese Summary ===")
        print(final_chinese_summary)
        print("=" * 80 + "\n")

    return {
        "id": sample_id,
        "test_index": example.get("test_index", ""),
        "dialogue": dialogue,

        # Intermediate output from Agent 1
        "english_summary": english_summary,

        # Final output from Agent 2
        "final_summary": final_chinese_summary,

        # References
        "reference_english_summary": reference_english_summary,
        "reference_chinese_summary": reference_chinese_summary,

        # Metadata
        "pipeline": "summarize_then_translate",
        "summarization_model": SUMMARIZATION_MODEL,
        "translation_model": TRANSLATION_MODEL,
        "num_model_calls": 2,
    }

## 3. Test with Examples

Start with five examples before running the full dataset.  
This is the best way to inspect whether errors come from the English summarization stage or the Chinese translation stage.

In [10]:
# Cell 9: Load first 5 examples from the gold set

def load_examples_from_gold_set(path: Path, n: int = 5) -> List[Dict[str, Any]]:
    """Load the first n examples from the gold-set JSON file."""
    if not path.exists():
        raise FileNotFoundError(f"Gold set not found: {path}")

    with path.open("r", encoding="utf-8") as f:
        raw_data = json.load(f)

    examples = []

    for i, item in enumerate(raw_data[:n]):
        examples.append({
            "id": f"gold_{i+1:05d}",
            "test_index": item.get("test_index", ""),
            "dialogue": item["dialogue"],
            "reference_english_summary": item.get("summary", ""),
            "reference_chinese_summary": item.get("summary_zh", ""),
        })

    return examples


test_data = load_examples_from_gold_set(GOLD_SET_PATH, n=50)

print(f"Loaded {len(test_data)} examples.")
print("First example:")
print(test_data[0])

Loaded 50 examples.
First example:
{'id': 'gold_00001', 'test_index': 23, 'dialogue': "Anne: You were right, he was lying to me :/\nIrene: Oh no, what happened?\nJane: who? that Mark guy?\nAnne: yeah, he told me he's 30, today I saw his passport - he's 40\nIrene: You sure it's so important?\nAnne: he lied to me Irene", 'reference_english_summary': 'Mark lied to Anne about his age. Mark is 40.', 'reference_chinese_summary': '马克向安妮隐瞒了自己的年龄。他40岁了。'}

In [11]:
# Cell 10: Run the ST pipeline for the first example

result = run_st_pipeline(test_data[4], verbose=True)
result

================================================================================
Sample ID: gold_00005
=== Agent 1 Output: English Summary ===
Joyce shared a link for a cheap ticket, and both Michael and Edson expressed excitement about it, with Edson immediately planning to book.
================================================================================

=== Agent 2 Output: Chinese Summary ===
乔伊斯分享了一个廉价机票的链接，迈克尔和埃德森都表达了兴奋之情，埃德森立刻开始计划预订。
================================================================================

{'id': 'gold_00005',
 'test_index': 66,
 'dialogue': "Joyce: Check this out!\r\nJoyce: <link>\r\nMichael: That's cheap!\r\nEdson: No way! I'm booking my ticket now!! ",
 'english_summary': 'Joyce shared a link for a cheap ticket, and both Michael and Edson expressed excitement about it, with Edson immediately planning to book.',
 'final_summary': '乔伊斯分享了一个廉价机票的链接，迈克尔和埃德森都表达了兴奋之情，埃德森立刻开始计划预订。',
 'reference_english_summary': 'Edson is booking his ticket now.',
 'reference_chinese_summary': '埃德森正在订票。',
 'pipeline': 'summarize_then_translate',
 'summarization_model': 'gemma3:27b',
 'translation_model': 'gemma3:27b',
 'num_model_calls': 2}

In [12]:
# Cell 11: Print ST pipeline result clearly

def print_st_result(result: Dict[str, Any]) -> None:
    print("=== Original Dialogue ===")
    print(result["dialogue"])
    print()

    print("=== Agent 1 Intermediate Output: English Summary ===")
    print(result["english_summary"])
    print()

    print("=== Agent 2 Final Output: Chinese Summary ===")
    print(result["final_summary"])
    print()

    print("=== Reference English Summary ===")
    print(result["reference_english_summary"])
    print()

    print("=== Reference Chinese Summary ===")
    print(result["reference_chinese_summary"])
    print()

    print("=== Metadata ===")
    print("Pipeline:", result["pipeline"])
    print("Summarization model:", result["summarization_model"])
    print("Translation model:", result["translation_model"])
    print("Model calls:", result["num_model_calls"])


print_st_result(result)

=== Original Dialogue ===
Joyce: Check this out!
Joyce: <link>
Michael: That's cheap!
Edson: No way! I'm booking my ticket now!!

=== Agent 1 Intermediate Output: English Summary ===
Joyce shared a link for a cheap ticket, and both Michael and Edson expressed excitement about it, with Edson immediately planning to book.

=== Agent 2 Final Output: Chinese Summary ===
乔伊斯分享了一个廉价机票的链接，迈克尔和埃德森都表达了兴奋之情，埃德森立刻开始计划预订。

=== Reference English Summary ===
Edson is booking his ticket now.

=== Reference Chinese Summary ===
埃德森正在订票。

=== Metadata ===
Pipeline: summarize_then_translate
Summarization model: gemma3:27b
Translation model: gemma3:27b
Model calls: 2

## 4. Save Results

This saves the intermediate English summary and the final Chinese summary.

In [13]:
# Cell 12: Reset previous outputs before batch inference

FULL_OUTPUT_PATH.unlink(missing_ok=True)
FINAL_CSV_PATH.unlink(missing_ok=True)
ERROR_OUTPUT_PATH.unlink(missing_ok=True)

print("Previous output files reset.")
print("JSONL output path:", FULL_OUTPUT_PATH)
print("CSV output path:", FINAL_CSV_PATH)
print("Error output path:", ERROR_OUTPUT_PATH)

Previous output files reset.
JSONL output path: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\st_gemma27b_50samples.jsonl
CSV output path: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\st_gemma27b_50samples.csv
Error output path: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\st_gemma27b_50samples_errors.jsonl

## 5. Batch Inference with Checkpointing

This cell processes examples one by one and appends each completed ST result to the JSONL output file.

If the notebook stops, already processed examples remain saved.

In [14]:
# Cell 13: Batch inference with ST pipeline
# Time stamp: 1m 29.8s

MAX_EXAMPLES = 50
SLEEP_SECONDS = 0.2

processed_ids = load_processed_ids(FULL_OUTPUT_PATH)
print(f"Already processed: {len(processed_ids)} examples")

subset = test_data[:MAX_EXAMPLES]

for ex in tqdm(subset, desc="Running ST pipeline"):
    sample_id = str(ex.get("id", "unknown"))

    if sample_id in processed_ids:
        print(f"Skipping already processed sample: {sample_id}")
        continue

    try:
        record = run_st_pipeline(ex, verbose=True)

        append_jsonl(record, FULL_OUTPUT_PATH)
        processed_ids.add(sample_id)

        time.sleep(SLEEP_SECONDS)

    except Exception as e:
        error_record = {
            "id": sample_id,
            "test_index": ex.get("test_index", ""),
            "error": repr(e),
            "dialogue": ex.get("dialogue", ""),
        }

        append_jsonl(error_record, ERROR_OUTPUT_PATH)
        print(f"Error on {sample_id}: {repr(e)}")

print(f"Finished. Outputs saved to: {FULL_OUTPUT_PATH}")

Already processed: 0 examples

Running ST pipeline:   0%|          | 0/50 [00:00<?, ?it/s]

================================================================================
Sample ID: gold_00001
=== Agent 1 Output: English Summary ===
Anne discovered Mark lied about his age, telling her he was 30 when his passport revealed he is 40, which upset her. Irene acknowledged Anne's disappointment with the deception.
================================================================================

=== Agent 2 Output: Chinese Summary ===
安妮发现马克对自己的年龄说了谎，他告诉她自己30岁，但他的护照显示他实际年龄是40岁，这让她感到难过。艾琳承认安妮对这次欺骗感到失望。
================================================================================


================================================================================
Sample ID: gold_00002
=== Agent 1 Output: English Summary ===
Mary asked Carter for some money, and Carter said he could lend it to her in an hour as he is currently at the train station.
================================================================================

=== Agent 2 Output: Chinese Summary ===
玛丽向卡特请求了一些钱，卡特说他可以在一个小时后借给她，因为他现在在火车站。
================================================================================


================================================================================
Sample ID: gold_00003
=== Agent 1 Output: English Summary ===
Tina was delayed at the airport and had a talkative pilot on her flight home, while Ala is going to an important meeting and asked Tina to wish her luck. Tina agreed to hear how the meeting went.
================================================================================

=== Agent 2 Output: Chinese Summary ===
蒂娜在机场延误，并且在回家的航班上遇到了一位健谈的飞行员。艾拉将要参加一个重要的会议，并请蒂娜为她祝好运。蒂娜同意听她讲述会议的情况。
================================================================================


================================================================================
Sample ID: gold_00004
=== Agent 1 Output: English Summary ===
Ana and Catherine plan to visit their grandma tomorrow, and Catherine will call Ana when she wakes up. They then said good night to each other.
================================================================================

=== Agent 2 Output: Chinese Summary ===
安娜和凯瑟琳计划明天去看望她们的奶奶，凯瑟琳会在她醒来后给安娜打电话。然后她们互相道了晚安。
================================================================================


================================================================================
Sample ID: gold_00005
=== Agent 1 Output: English Summary ===
Joyce shared a link for a cheap ticket, prompting Michael to acknowledge the price and Edson to immediately book a ticket.
================================================================================

=== Agent 2 Output: Chinese Summary ===
乔伊斯分享了一个廉价机票的链接，促使迈克尔承认价格，而埃德森立即预订了一张机票。
================================================================================


================================================================================
Sample ID: gold_00006
=== Agent 1 Output: English Summary ===
Jane and Steven are planning to meet, and Jane wants to meet at 4:30 PM instead of 5:00 PM due to the long drive, which Steven agrees to; they will meet at the main entrance.
================================================================================

=== Agent 2 Output: Chinese Summary ===
简和史蒂文计划见面，简希望因为路途遥远而将见面时间提前到下午4点30分，而不是5点，史蒂文同意了；他们将在主入口见面。
================================================================================


================================================================================
Sample ID: gold_00007
=== Agent 1 Output: English Summary ===
Fiona wants to make Tina’s tart for dinner with Chris and asks for Tina’s help, admitting she bought the crust and previously failed at making the filling due to overmixing the eggs. Tina agrees to help and explains the key to avoiding scrambled eggs is continuous mixing once eggs are added.
================================================================================

=== Agent 2 Output: Chinese Summary ===
菲奥娜想为克里斯做晚餐，想做蒂娜的馅饼，于是向蒂娜寻求帮助，并承认她买好了派皮，之前因为过度搅拌鸡蛋而导致馅料失败。蒂娜同意帮忙，并解释了避免鸡蛋凝固的关键在于鸡蛋加入后要持续搅拌。
================================================================================


================================================================================
Sample ID: gold_00008
=== Agent 1 Output: English Summary ===
The group is planning to go to a classy New Year's Eve party at a club in Soho, potentially "Breakfast at Tiffany's," and they need to buy tickets soon. The opera was considered but rejected by Olafur.
================================================================================

=== Agent 2 Output: Chinese Summary ===
该团队计划前往苏荷区的一家俱乐部参加一场高档的新年晚会，可能是在“蒂芙尼的早餐”俱乐部，他们需要尽快购买门票。奥拉夫考虑过观看歌剧，但最终放弃了。
================================================================================


================================================================================
Sample ID: gold_00009
=== Agent 1 Output: English Summary ===
John and Joan agreed to see "A Star is Born" on Thursday around 8pm, after Joan said she was busy on Wednesday. John will send Joan the movie details and location.
================================================================================

=== Agent 2 Output: Chinese Summary ===
约翰和琼同意在周四晚上8点左右观看电影《一个明星的诞生》，此前琼表示周三她很忙。约翰会把电影详情和地点发给琼。
================================================================================


================================================================================
Sample ID: gold_00010
=== Agent 1 Output: English Summary ===
Cameron is unable to bring Peyton a video game because he has to stay out of town for another week, prompting Peyton to suggest sending it via courier. Peyton then asks Cameron to hurry home and complete the task.
================================================================================

=== Agent 2 Output: Chinese Summary ===
卡梅隆无法给佩顿送游戏机，因为他需要出城另待一周，这促使佩顿建议通过快递寄送。佩顿随后要求卡梅隆尽快回家完成任务。
================================================================================


================================================================================
Sample ID: gold_00011
=== Agent 1 Output: English Summary ===
Paul returned home after a busy day and realized he missed his physiotherapy appointment, but he will reschedule it. Emma will be home late and Paul offered to prepare food for her, which she accepted.
================================================================================

=== Agent 2 Output: Chinese Summary ===
保罗忙碌了一天后回到家，意识到他错过了物理治疗预约，但他会重新安排。艾玛会晚点回家，保罗提出为她准备食物，她接受了。
================================================================================


================================================================================
Sample ID: gold_00012
=== Agent 1 Output: English Summary ===
Harris informed Lena that his friend Aoki passed away yesterday, and he is upset about it. He last saw Aoki a few months ago, as she lived in Michigan, and he had to end the conversation due to his mother calling.
================================================================================

=== Agent 2 Output: Chinese Summary ===
哈里斯告知莉娜，他的朋友青木昨天去世了，他对此感到难过。他几个月前见过青木一次，因为她住在密歇根州，而且他的母亲打电话了，所以他不得不结束对话。
================================================================================


================================================================================
Sample ID: gold_00013
=== Agent 1 Output: English Summary ===
Yaz and Mary both admit to overindulging but agree to attend their slimming club meeting tonight, anticipating a scolding from their former cookery teacher. Yaz will pick Mary up around 6 PM.
================================================================================

=== Agent 2 Output: Chinese Summary ===
雅兹和玛丽都承认自己暴饮暴食，但同意今晚参加她们的减肥俱乐部会议，预计会受到她们以前的烹饪老师的训斥。雅兹将在下午6点左右接玛丽。
================================================================================


================================================================================
Sample ID: gold_00014
=== Agent 1 Output: English Summary ===
Camille is sick, and Ellie and Aaliyah are at the university, where their class will be held in room 342 on the second floor.
================================================================================

=== Agent 2 Output: Chinese Summary ===
卡米尔生病了，埃莉和阿利亚在大学，她们的课程将在二楼342教室举行。
================================================================================


================================================================================
Sample ID: gold_00015
=== Agent 1 Output: English Summary ===
Nathan and Aaron found a funny video of a woman making a strange face, with Aaron comparing it to his cat and joking about a spiritual or tragic moment. They both laughed and shared several GIFs reacting to the video.
================================================================================

=== Agent 2 Output: Chinese Summary ===
内森和亚伦发现了一个关于一位女士做出奇怪表情的搞笑视频，亚伦将其比作他的猫，并开玩笑说这可能是一个精神或悲剧时刻。他们都笑了，并分享了几个GIF动图来表达对该视频的反应。
================================================================================


================================================================================
Sample ID: gold_00016
=== Agent 1 Output: English Summary ===
Several people discussed what they are watching on Netflix, including shows like Mad Men, The Crown, Outlander, I, Zombie, and House of Cards, with recommendations ranging from political dramas to lighter series like Friends and Pretty Little Liars. Some disagreed on the quality of certain shows, while others shared their enjoyment of guilty pleasures like Desperate Housewives.
================================================================================

=== Agent 2 Output: Chinese Summary ===
几个人讨论了他们在观看的奈飞剧集，包括《广告狂人》、《王冠》、《异星出lander》、《僵尸肖恩》、《纸牌屋》等，推荐涵盖了政治剧到《老友记》、《美少女谎言》等轻松剧集。有些人对某些剧集的质量存在分歧，而另一些人则分享了他们对《绝望主妇》等“罪恶快感”的喜爱。
================================================================================


================================================================================
Sample ID: gold_00017
=== Agent 1 Output: English Summary ===
Jones and Angelina reconnected and agreed to meet in town later that afternoon, with Jones promising to confirm the exact location.
================================================================================

=== Agent 2 Output: Chinese Summary ===
琼斯和安吉丽娜重逢并同意当天下午在镇上见面，琼斯承诺确认具体地点。
================================================================================


================================================================================
Sample ID: gold_00018
=== Agent 1 Output: English Summary ===
Casey did her own nails, which Amelia and Kristen loved and asked her to replicate, but Casey declined as it took her four hours and was too difficult.
================================================================================

=== Agent 2 Output: Chinese Summary ===
凯西自己做了美甲，阿米莉亚和克里斯汀非常喜欢，并要求她复制，但凯西拒绝了，因为这花费了她四个小时，而且太困难了。
================================================================================


================================================================================
Sample ID: gold_00019
=== Agent 1 Output: English Summary ===
Sue asked Steve to call her upon receiving the message because it was important, and Steve confirmed he was calling.
================================================================================

=== Agent 2 Output: Chinese Summary ===
苏请史蒂夫收到消息后给她打电话，因为这很重要，史蒂夫确认他正在打电话。
================================================================================


================================================================================
Sample ID: gold_00020
=== Agent 1 Output: English Summary ===
Gemma is inviting Timmy and potentially his date, along with Lona and Michelle, to a gathering, and she admits she hopes to be invited to Lona and Michelle’s wedding receptions. Timmy playfully teases Gemma about wanting to attend their weddings, and she acknowledges she’s unsure if she can convince them to invite her.
================================================================================

=== Agent 2 Output: Chinese Summary ===
杰玛正在邀请蒂米和他的潜在约会对象，以及洛娜和米歇尔参加聚会，她承认她希望被邀请参加洛娜和米歇尔的婚礼招待会。蒂米调侃杰玛想参加他们的婚礼，她承认她不确定是否能说服她们邀请她。
================================================================================


================================================================================
Sample ID: gold_00021
=== Agent 1 Output: English Summary ===
Ann congratulated Sue and Julie on a job well done, and they all agreed to celebrate that night.
================================================================================

=== Agent 2 Output: Chinese Summary ===
安妮祝贺苏和朱莉工作完成得很好，她们都同意那天晚上庆祝。
================================================================================


================================================================================
Sample ID: gold_00022
=== Agent 1 Output: English Summary ===
Steve informed his mum that the dishwasher was installed and working well, noting it was quiet and likely a 12-place setting. His mum expressed her happiness that he was pleased with it.
================================================================================

=== Agent 2 Output: Chinese Summary ===
史蒂夫告知他的母亲洗碗机已经安装完毕，并且运行良好，他指出洗碗机运行安静，而且可能是12套餐具的容量。他的母亲表达了她很高兴他对此感到满意。
================================================================================


================================================================================
Sample ID: gold_00023
=== Agent 1 Output: English Summary ===
Lara confirmed to Marika that she is coming today.
================================================================================

=== Agent 2 Output: Chinese Summary ===
拉拉向玛丽卡确认她今天会来。
================================================================================


================================================================================
Sample ID: gold_00024
=== Agent 1 Output: English Summary ===
Miranda requested to cancel their meeting due to work, explaining that it's common for young doctors to work long hours, which Stephanie jokingly countered with concerns about burnout. Miranda then playfully responded with a hyperbolic statement about doctors nearing death but becoming immortal.
================================================================================

=== Agent 2 Output: Chinese Summary ===
米兰达因工作原因请求取消他们的会议，解释说年轻医生长时间工作是很常见的现象，对此斯蒂芬妮开玩笑地表示担心职业倦怠。米兰达随后以一种夸张的方式回应说医生们接近死亡却能变得不朽。
================================================================================


================================================================================
Sample ID: gold_00025
=== Agent 1 Output: English Summary ===
Javier asked Judie for English-speaking tattoo parlors, and Judie recommended Warsaw Ink where her girlfriend got a tattoo for 1000. Javier decided it was too expensive and will get a tattoo in Colombia instead.
================================================================================

=== Agent 2 Output: Chinese Summary ===
哈维尔向朱迪询问会说英语的纹身店，朱迪推荐了华沙印克，她的女朋友在那里花了一千元做了纹身。哈维尔觉得太贵了，决定改在哥伦比亚做纹身。
================================================================================


================================================================================
Sample ID: gold_00026
=== Agent 1 Output: English Summary ===
Sam complimented Jessica and Michael on their hotel and confirmed his arrival on August 15th around 2 p.m., expressing excitement to see them again. Jessica and Michael acknowledged Sam’s compliment and confirmed they would arrange a good room for him.
================================================================================

=== Agent 2 Output: Chinese Summary ===
萨姆赞美了杰西卡和迈克尔的酒店，并确认他将于8月15日下午2点左右到达，表达了再次见到他们的喜悦。杰西卡和迈克尔感谢了萨姆的赞美，并确认他们会为他安排一间好房间。
================================================================================


================================================================================
Sample ID: gold_00027
=== Agent 1 Output: English Summary ===
Terence accused Daniel of stealing his money, but later apologized after finding it himself. Daniel expressed his anger at the false accusation.
================================================================================

=== Agent 2 Output: Chinese Summary ===
特伦斯指责丹尼尔偷了他的钱，但后来在找到钱后道歉。丹尼尔表达了他对这虚假指控的愤怒。
================================================================================


================================================================================
Sample ID: gold_00028
=== Agent 1 Output: English Summary ===
Natacha offered to pick Charles up at the RER station, and he will arrive around 5:30pm and call her when he’s at the Vesinet station.
================================================================================

=== Agent 2 Output: Chinese Summary ===
娜塔莎提出要从火车站接查尔斯，他大约在下午5点30分到达，并在韦西内站时给她打电话。
================================================================================


================================================================================
Sample ID: gold_00029
=== Agent 1 Output: English Summary ===
Ann is at school for extra math classes and will be home at 7 PM, allowing Meg to meet her then.
================================================================================

=== Agent 2 Output: Chinese Summary ===
安妮在学校上额外的数学课，晚上7点会回家，梅格那时可以和她见面。
================================================================================


================================================================================
Sample ID: gold_00030
=== Agent 1 Output: English Summary ===
Pete is going to check if the store has pear yogurt for Jen, and if not, he shouldn't get any yogurt at all, as Jen doesn't like other flavors.
================================================================================

=== Agent 2 Output: Chinese Summary ===
皮特将去查看商店是否有梨味酸奶给珍，如果没有，他就不要购买任何酸奶，因为珍不喜欢其他口味。
================================================================================


================================================================================
Sample ID: gold_00031
=== Agent 1 Output: English Summary ===
Christie and Katie both feel tired after attending a great party that they both enjoyed.
================================================================================

=== Agent 2 Output: Chinese Summary ===
克里斯蒂和凯蒂在参加了一个她们都很喜欢的精彩派对后，都感到疲惫。
================================================================================


================================================================================
Sample ID: gold_00032
=== Agent 1 Output: English Summary ===
Sam and Carla arranged to meet at a cafe in Meanwood at 2 PM tomorrow, as it is Carla’s day off. They both expressed excitement about the meetup.
================================================================================

=== Agent 2 Output: Chinese Summary ===
萨姆和卡拉约定明天下午两点在米恩伍德的一家咖啡馆见面，因为那天是卡拉的休息日。他们都表达了对这次见面的兴奋之情。
================================================================================


================================================================================
Sample ID: gold_00033
=== Agent 1 Output: English Summary ===
Joana and Sandy decided to play either Dixit or Carcassonne, and Joana will bring the games to Sandy.
================================================================================

=== Agent 2 Output: Chinese Summary ===
约阿娜和桑迪决定玩《迪克西特》或《卡卡颂》，约阿娜会把游戏带给桑迪。
================================================================================


================================================================================
Sample ID: gold_00034
=== Agent 1 Output: English Summary ===
Steve and Rob both recently acquired Dream Theater’s new album and plan to share their opinions on it later. They will discuss the album after both have had a chance to listen.
================================================================================

=== Agent 2 Output: Chinese Summary ===
史蒂夫和罗伯最近都获得了梦剧场的新专辑，并计划稍后分享他们对它的看法。他们将在两人都听过专辑后讨论它。
================================================================================


================================================================================
Sample ID: gold_00035
=== Agent 1 Output: English Summary ===

## 6. Export Final Summaries to CSV

This file can be used for ROUGE, BERTScore, OmniScore, or manual analysis.

For the ST pipeline, the CSV also includes the intermediate English summary from Agent 1.

In [15]:
# Cell 14: Export ST summaries to CSV

records = load_jsonl(FULL_OUTPUT_PATH)

rows = []

for record in records:
    if "final_summary" not in record:
        continue

    rows.append({
        "id": record.get("id", ""),
        "test_index": record.get("test_index", ""),
        "dialogue": record.get("dialogue", ""),

        # Intermediate output from Agent 1
        "english_summary": record.get("english_summary", ""),

        # Final output from Agent 2
        "final_summary": record.get("final_summary", ""),

        # References
        "reference_english_summary": record.get("reference_english_summary", ""),
        "reference_chinese_summary": record.get("reference_chinese_summary", ""),

        # Metadata
        "pipeline": record.get("pipeline", "summarize_then_translate"),
        "summarization_model": record.get("summarization_model", ""),
        "translation_model": record.get("translation_model", ""),
        "num_model_calls": record.get("num_model_calls", 2),
    })

df = pd.DataFrame(rows)

if not df.empty:
    df = df.drop_duplicates(subset=["id"], keep="last")

df.to_csv(FINAL_CSV_PATH, index=False, encoding="utf-8-sig")

print(f"Saved final summaries to: {FINAL_CSV_PATH}")
df

Saved final summaries to: C:\Users\FLEXBOY\OneDrive\바탕 화면\yunu\st_gemma27b_50samples.csv

,id,test_index,dialogue,english_summary,final_summary,reference_english_summary,reference_chinese_summary,pipeline,summarization_model,translation_model,num_model_calls
0,gold_00001,23,"Anne: You were right, he was lying to me :/\nI...","Anne discovered Mark lied about his age, telli...",安妮发现马克对自己的年龄说了谎，他告诉她自己30岁，但他的护照显示他实际年龄是40岁，这让她...,Mark lied to Anne about his age. Mark is 40.,马克向安妮隐瞒了自己的年龄。他40岁了。,summarize_then_translate,gemma3:27b,gemma3:27b,2
1,gold_00002,30,"Mary: hey, im kinda broke, lend me a few box\r...","Mary asked Carter for some money, and Carter s...",玛丽向卡特请求了一些钱，卡特说他可以在一个小时后借给她，因为他现在在火车站。,Mary ran out of money. Carter is going to lend...,玛丽的钱用完了，卡特打算一小时后借给她一点。,summarize_then_translate,gemma3:27b,gemma3:27b,2
2,gold_00003,39,"Tina: I'll tell you something, this Emirate st...",Tina was delayed at the airport and had a talk...,蒂娜在机场延误，并且在回家的航班上遇到了一位健谈的飞行员。艾拉将要参加一个重要的会议，并请蒂...,Tina will catch the evening flight back home. ...,蒂娜将乘晚间航班回家。阿拉正在去开会的路上。她会让蒂娜知道事情的进展。,summarize_then_translate,gemma3:27b,gemma3:27b,2
3,gold_00004,65,Ana: You sleeping?\r\nCatherine: Not yet.\r\nA...,Ana and Catherine plan to visit their grandma ...,安娜和凯瑟琳计划明天去看望她们的奶奶，凯瑟琳会在她醒来后给安娜打电话。然后她们互相道了晚安。,Ana wants to visit grandma tomorrow. Catherine...,安娜明天想去看望奶奶。凯瑟琳会和她一起去。她起床后会给安娜打电话。,summarize_then_translate,gemma3:27b,gemma3:27b,2
4,gold_00005,66,Joyce: Check this out!\r\nJoyce: <link>\r\nMic...,"Joyce shared a link for a cheap ticket, prompt...",乔伊斯分享了一个廉价机票的链接，促使迈克尔承认价格，而埃德森立即预订了一张机票。,Edson is booking his ticket now.,埃德森正在订票。,summarize_then_translate,gemma3:27b,gemma3:27b,2
5,gold_00006,67,Jane: google maps says it is at least 3h <file...,"Jane and Steven are planning to meet, and Jane...",简和史蒂文计划见面，简希望因为路途遥远而将见面时间提前到下午4点30分，而不是5点，史蒂文同...,Jane wants to leave at 4.30 instead of 5 becau...,简想4点半就走，而不是等到5点，因为谷歌地图提示300公里的车程至少需要3小时，她不想迟到。...,summarize_then_translate,gemma3:27b,gemma3:27b,2
6,gold_00007,78,"Fiona: Are you free?\r\nTina: Yes, what's up?\...",Fiona wants to make Tina’s tart for dinner wit...,菲奥娜想为克里斯做晚餐，想做蒂娜的馅饼，于是向蒂娜寻求帮助，并承认她买好了派皮，之前因为过度...,Fiona wants to prepare dinner for Chris. She i...,菲奥娜想为克里斯准备晚餐。她想起了蒂娜做的馅饼。蒂娜会帮她做的。,summarize_then_translate,gemma3:27b,gemma3:27b,2
7,gold_00008,86,Olafur: are we doing anything for New Year's E...,The group is planning to go to a classy New Ye...,该团队计划前往苏荷区的一家俱乐部参加一场高档的新年晚会，可能是在“蒂芙尼的早餐”俱乐部，他们...,"Nathalie, Olafur and Zoe are planning the New ...",娜塔莉、奥拉维尔和佐伊正在做新年前夜的计划。娜塔莉想要有格调的。但奥拉维尔不喜欢歌剧。他们想...,summarize_then_translate,gemma3:27b,gemma3:27b,2
8,gold_00009,120,"John: wanna go see ""A Star is Born"" on Wed?\r\...","John and Joan agreed to see ""A Star is Born"" o...",约翰和琼同意在周四晚上8点左右观看电影《一个明星的诞生》，此前琼表示周三她很忙。约翰会把电影...,"Joan and John are going to watch ""A Star is Bo...",琼和约翰星期四晚上8点左右去看《一个明星的诞生》。,summarize_then_translate,gemma3:27b,gemma3:27b,2
9,gold_00010,137,Peyton: I have been asking you to bring that v...,Cameron is unable to bring Peyton a video game...,卡梅隆无法给佩顿送游戏机，因为他需要出城另待一周，这促使佩顿建议通过快递寄送。佩顿随后要求卡...,Peyton is expecting Cameron to bring the video...,佩顿希望卡梅隆能带游戏机过来，但是卡梅隆可能还要再缺席一周。,summarize_then_translate,gemma3:27b,gemma3:27b,2
10,gold_00011,139,Paul: I just came back home\r\nPaul: What a bu...,Paul returned home after a busy day and realiz...,保罗忙碌了一天后回到家，意识到他错过了物理治疗预约，但他会重新安排。艾玛会晚点回家，保罗提出...,Paul forgot about his physiotherapy and he wil...,保罗忘记去做理疗了，得重新预约。艾玛午夜后回家，所以保罗会给她准备一些吃的。,summarize_then_translate,gemma3:27b,gemma3:27b,2
11,gold_00012,192,"Harris: How are U?\r\nLena: Fine, U?\r\nHarris...",Harris informed Lena that his friend Aoki pass...,哈里斯告知莉娜，他的朋友青木昨天去世了，他对此感到难过。他几个月前见过青木一次，因为她住在密...,"Harris' friend, Aoki, who lives in Michigan, d...",哈里斯的朋友青木住在密歇根州，昨天去世了。哈里斯有几个月没见她了。,summarize_then_translate,gemma3:27b,gemma3:27b,2
12,gold_00013,210,Yaz: Going to slimming club tonight?\r\nMary: ...,Yaz and Mary both admit to overindulging but a...,雅兹和玛丽都承认自己暴饮暴食，但同意今晚参加她们的减肥俱乐部会议，预计会受到她们以前的烹饪老...,Yaz and Mary are meeting tonight around 6 and ...,亚兹和玛丽今晚6点左右见面，一起去减肥俱乐部。他们估计吃得太多会被骂。,summarize_then_translate,gemma3:27b,gemma3:27b,2
13,gold_00014,211,"Ellie: hey, are you at the university?\r\nAali...","Camille is sick, and Ellie and Aaliyah are at ...",卡米尔生病了，埃莉和阿利亚在大学，她们的课程将在二楼342教室举行。,Ellie's class is in 342 on the second floor.,艾莉的班级在二楼342教室。,summarize_then_translate,gemma3:27b,gemma3:27b,2
14,gold_00015,212,Nathan: <file_video>\r\nAaron: OMG!!! \r\nAaro...,Nathan and Aaron found a funny video of a woma...,内森和亚伦发现了一个关于一位女士做出奇怪表情的搞笑视频，亚伦将其比作他的猫，并开玩笑说这可能...,Nathan and Aaron are discussing a video which ...,内森和亚伦正在讨论内森发来的视频。,summarize_then_translate,gemma3:27b,gemma3:27b,2
15,gold_00016,215,Freddie: What are you watching on Netflix? I'v...,Several people discussed what they are watchin...,几个人讨论了他们在观看的奈飞剧集，包括《广告狂人》、《王冠》、《异星出lander》、《僵尸...,"Freddie, Kelly, Jim, Greg, Bob, Mike, Mary, Al...",弗雷迪、凯利、吉姆、格雷格、鲍勃、迈克、玛丽、艾伦和南希正在netflix上观看不同的节目。,summarize_then_translate,gemma3:27b,gemma3:27b,2
16,gold_00017,244,Jones: Hey.\r\nAngelina: Hey.\r\nAngelina: Lon...,Jones and Angelina reconnected and agreed to m...,琼斯和安吉丽娜重逢并同意当天下午在镇上见面，琼斯承诺确认具体地点。,Jones and Angelina will meet in town in the af...,琼斯和安吉丽娜下午会在城里见面。,summarize_then_translate,gemma3:27b,gemma3:27b,2
17,gold_00018,285,Casey: <file_photo>\r\nAmelia: these are so ni...,"Casey did her own nails, which Amelia and Kris...",凯西自己做了美甲，阿米莉亚和克里斯汀非常喜欢，并要求她复制，但凯西拒绝了，因为这花费了她四个...,Casey got a new nail polish and did her nails ...,凯西买了新指甲油，自己做了指甲。她花了近4个小时，所以她不会帮朋友做指甲，因为耗时太长了。,summarize_then_translate,gemma3:27b,gemma3:27b,2
18,gold_00019,319,Sue: Call me when you get this.\r\nSue: it's i...,Sue asked Steve to call her upon receiving the...,苏请史蒂夫收到消息后给她打电话，因为这很重要，史蒂夫确认他正在打电话。,Steve is calling Sue at her request.,史蒂夫正按照苏的要求给她打电话。,summarize_then_translate,gemma3:27b,gemma3:27b,2
19,gold_00020,346,"Timmy: Who do u wanna invite?\r\nGemma: Well, ...",Gemma is inviting Timmy and potentially his da...,杰玛正在邀请蒂米和他的潜在约会对象，以及洛娜和米歇尔参加聚会，她承认她希望被邀请参加洛娜和米...,"Gemma will invite Timmy and his Date, as well ...",杰玛将邀请蒂米和他的约会对象，以及罗娜和米歇尔参加她的婚礼。,summarize_then_translate,gemma3:27b,gemma3:27b,2
20,gold_00021,355,"Ann: Congratulations!!\r\nAnn: You did great, ...",Ann congratulated Sue and Julie on a job well ...,安妮祝贺苏和朱莉工作完成得很好，她们都同意那天晚上庆祝。,"Ann, Sue and Julie did a great job and they wi...",安、苏和朱莉做得很好，今晚他们会举行一个小小的庆祝活动。,summarize_then_translate,gemma3:27b,gemma3:27b,2
21,gold_00022,367,Steve: hiya the dishwasher has turned up\r\nMu...,Steve informed his mum that the dishwasher was...,史蒂夫告知他的母亲洗碗机已经安装完毕，并且运行良好，他指出洗碗机运行安静，而且可能是12套餐...,Steve is happy that he got a new dishwasher in...,史蒂夫很高兴他装了一台新的洗碗机。,summarize_then_translate,gemma3:27b,gemma3:27b,2
22,gold_00023,393,Marika: Are you coming today?\r\nLara: Yes!\r\...,Lara confirmed to Marika that she is coming to...,拉拉向玛丽卡确认她今天会来。,Marika is coming today.,玛丽卡今天会来。,summarize_then_translate,gemma3:27b,gemma3:27b,2
23,gold_00024,417,"Miranda: Hi S, could we cancel tomorrow's meet...",Miranda requested to cancel their meeting due ...,米兰达因工作原因请求取消他们的会议，解释说年轻医生长时间工作是很常见的现象，对此斯蒂芬妮开玩...,Miranda can't make her meeting with Stephanie ...,米兰达不能去见斯蒂芬妮，因为她要工作。,summarize_then_translate,gemma3:27b,gemma3:27b,2
24,gold_00025,432,Javier: Hey do you know any tattoo parlors ove...,Javier asked Judie for English-speaking tattoo...,哈维尔向朱迪询问会说英语的纹身店，朱迪推荐了华沙印克，她的女朋友在那里花了一千元做了纹身。哈...,Javier was initially eager to have a tatoo don...,哈维尔最初很想在warsaw ink纹身，但价格太高了。他决定去哥伦比亚做纹身。,summarize_then_translate,gemma3:27b,gemma3:27b,2
25,gold_00026,433,"Sam: You own a really nice hotel, guys 😊\r\nJe...",Sam complimented Jessica and Michael on their ...,萨姆赞美了杰西卡和迈克尔的酒店，并确认他将于8月15日下午2点左右到达，表达了再次见到他们的...,Sam appreciates the hotel owned by Jessica and...,山姆很喜欢杰西卡和迈克尔的酒店。他会在8月15日下午2点左右去那里。,summarize_then_translate,gemma3:27b,gemma3:27b,2
26,gold_00027,442,"Terence: What the hell, Danny. You took my mon...","Terence accused Daniel of stealing his money, ...",特伦斯指责丹尼尔偷了他的钱，但后来在找到钱后道歉。丹尼尔表达了他对这虚假指控的愤怒。,Terence accused Daniel of taking his money. Te...,特伦斯指控丹尼尔偷了他的钱。后来他找到了钱，就向丹尼尔道歉。但是丹尼尔还在生气。,summarize_then_translate,gemma3:27b,gemma3:27b,2
27,gold_00028,499,"Natacha: hi, i can come and pick you up at the...",Natacha offered to pick Charles up at the RER ...,娜塔莎提出要从火车站接查尔斯，他大约在下午5点30分到达，并在韦西内站时给她打电话。,Charles has just landed and he will be at RER ...,查尔斯刚刚落地，他会在下午五点半到达rer，娜塔夏会在那里接他。,summarize_then_translate,gemma3:27b,gemma3:27b,2
28,gold_00029,528,Meg: still at school?\r\nAnn: i have extra mat...,Ann is at school for extra math classes and wi...,安妮在学校上额外的数学课，晚上7点会回家，梅格那时可以和她见面。,Ann is still at school. She will be home at 7 ...,安还在学校，她7点会回家，这样她就可以和麦格见面了。,summarize_then_translate,gemma3:27b,gemma3:27b,2
29,gold_00030,532,Pete: What flavour yogurt did you want again? ...,Pete is going to check if the store has pear y...,皮特将去查看商店是否有梨味酸奶给珍，如果没有，他就不要购买任何酸奶，因为珍不喜欢其他口味。,Pete will get a pear yogurt for Jen if they ha...,如果商店里有梨味酸奶， 皮特会给珍买的。,summarize_then_translate,gemma3:27b,gemma3:27b,2
30,gold_00031,536,Christie: how are you after the party?\r\nKati...,Christie and Katie both feel tired after atten...,克里斯蒂和凯蒂在参加了一个她们都很喜欢的精彩派对后，都感到疲惫。,Christie and Katie are tired after the party. ...,克里斯蒂和凯蒂在聚会后累了。他们都玩得很开心。,summarize_then_translate,gemma3:27b,gemma3:27b,2
31,gold_00032,537,"Sam: Are you working tomorrow?\r\nCarla: No, i...",Sam and Carla arranged to meet at a cafe in Me...,萨姆和卡拉约定明天下午两点在米恩伍德的一家咖啡馆见面，因为那天是卡拉的休息日。他们都表达了对...,Carla has a day off tomorrow. She will meet Sa...,卡拉明天有一天假。她将在下午两点在meanwood的一个咖啡馆和山姆见面。,summarize_then_translate,gemma3:27b,gemma3:27b,2
32,gold_00033,544,Joana: wana play some games?\r\nSandy: what ga...,Joana and Sandy decided to play either Dixit o...,约阿娜和桑迪决定玩《迪克西特》或《卡卡颂》，约阿娜会把游戏带给桑迪。,Joana will bring Sandy some games like dixit a...,琼娜将为桑迪带来一些像迪克西特和卡尔卡松这样的游戏。,summarize_then_translate,gemma3:27b,gemma3:27b,2
33,gold_00034,548,Steve: Bought the new Dream Theater album 5 mi...,Steve and Rob both recently acquired Dream The...,史蒂夫和罗伯最近都获得了梦剧场的新专辑，并计划稍后分享他们对它的看法。他们将在两人都听过专辑...,Steve and Rob will talk about new Dream Theate...,史蒂夫和罗伯将在听完后谈论新的梦剧场专辑。,summarize_then_translate,gemma3:27b,gemma3:27b,2
34,gold_00035,551,Peter: Can you send me the link of your beauty...,Joy sent Peter the link to her beauty shop and...,乔伊将她的美容店链接发送给彼得，并邀请他提出任何问题。彼得确认已收到链接，并表示他会查看。,Joy sent Peter the link to her beauty shop.,乔伊把她美容店的链接发给了彼得。,summarize_then_translate,gemma3:27b,gemma3:27b,2
35,gold_00036,590,Ethan: who's going to see solstafir?\r\nNoah: ...,"Ethan, Leo, and Noah are discussing the Solsta...",伊森、里奥和诺亚正在讨论索尔斯塔菲尔乐队11月21日的演唱会，里奥和伊森鼓励诺亚参加，尽管可...,Ethan and Leo are going to see Sólstafir on 21...,伊森和里奥要在21点11分去见索斯塔弗。诺亚也想去，但他可能得工作到很晚。,summarize_then_translate,gemma3:27b,gemma3:27b,2
36,gold_00037,598,Bradley: haha look a cat invaded the pitch at ...,A cat ran onto the pitch at Goodison Park duri...,在一场比赛中，一只猫跑进了古迪逊公园球场，引得包括布拉德利、吉尔和茱莉亚在内的球迷们感到有趣...,A sweet little black cat got into the pitch du...,在埃弗顿的足球比赛中，一只可爱的小黑猫钻进了球场。,summarize_then_translate,gemma3:27b,gemma3:27b,2
37,gold_00038,605,"Barbara: I'm home already, you can come over\r...",Sean is coming over to Barbara's place with hi...,肖恩将带着他的狗去芭芭拉家，并且计划过夜。扎克也在路上。,"Barbara, Sean and Zac are meeting at Barbara's...",芭芭拉、肖恩和扎克今晚在芭芭拉家见面。肖恩会把狗带来的，肖恩和扎克会在这里过夜。,summarize_then_translate,gemma3:27b,gemma3:27b,2
38,gold_00039,616,"Jake: dude, I just pulled a TOTW\nJake: my fir...",Jake received a Team of the Week player card a...,杰克获得了一张本周最佳球员卡，并计划出售因为它不适合他的球队，而汤姆今年尽管游戏技术精湛，但...,Jake has got his first TOTW this year. Tom doe...,杰克今年拿到了第一个totw ，汤姆的团队并不出色。,summarize_then_translate,gemma3:27b,gemma3:27b,2
39,gold_00040,621,Phil: Good evening Deana! Many thanks for this...,Phil and Deana are trying to figure out who th...,菲尔和迪安娜正在试图弄清楚在迪安娜的车里发现的太阳镜属于谁，但他们俩都不认识这副太阳镜，艾德...,Phil received a card from Deana. Constantine w...,菲尔收到了迪安娜的一张卡片，康斯坦丁很开心。菲尔有副墨镜。蒂娜在后面收音机上面找到的。迪安娜...,summarize_then_translate,gemma3:27b,gemma3:27b,2
40,gold_00041,635,Mell: Hi there! How are you doing?\r\nGloria: ...,Mell and Gloria agreed to have a BBQ at Mell’s...,梅尔和格洛丽亚同意本周六在梅尔家举行烧烤，她们都表示对塔德的姐姐搬到苏格兰感到欣慰。梅尔承认...,Gloria and Mell plan to have a barbeque at Mel...,格洛丽亚和梅尔计划星期六在梅尔家吃烧烤。他们很高兴，因为泰德的姐姐搬到了苏格兰。梅尔需要格洛...,summarize_then_translate,gemma3:27b,gemma3:27b,2
41,gold_00042,649,Callan: Something's wrong with my Samsung S8.\...,Callan’s Samsung S8 has a black screen and is ...,卡兰的三星S8屏幕变黑并过热，之前也出现过类似问题，但他将前往商店进行保修维修，因为他会定期...,"Callan's Samsung S8 overheats, so he's going t...",卡伦的三星s8过热了，所以他要去店里修理。,summarize_then_translate,gemma3:27b,gemma3:27b,2
42,gold_00043,676,"Anna: Mum, I have a awful stomachache.\r\nJoan...",Anna has a stomachache and isn't sure what cau...,安娜感到胃痛，她不确定是什么原因引起的，但她的妈妈建议可能是她吃的东西。如果情况没有好转，她...,Anna got an awful stomachache at night but she...,安娜夜里胃疼得厉害，但她不知道其中的原因。她的妈妈乔安娜会用新鲜的薄荷叶为她做热茶。,summarize_then_translate,gemma3:27b,gemma3:27b,2
43,gold_00044,678,Sam: Where are you?\nKate: downstairs\nSam: al...,Kate and Sam are downstairs near reception and...,凯特和萨姆在接待区楼下发现一个蛋糕正在被一位女士装饰，蛋糕上有一个用杏仁糖制作的大型男性生殖...,Kate and Jeff are downstairs in a room next to...,凯特和杰夫在楼下接待处旁边的一个房间里。有位女士正在做杏仁蛋糕。,summarize_then_translate,gemma3:27b,gemma3:27b,2
44,gold_00045,690,"Mia: God, he keeps talking about the stupid wa...",The group discusses a politician—likely Trump—...,该群体讨论了一位政客——很可能是 特朗普 —并一致认为他并非仅仅是老年痴呆，而是故意利用恐惧...,"Mia, Jennifer, Karine and Peter do not like Tr...",米亚、珍妮弗、卡琳和彼得不喜欢特朗普。,summarize_then_translate,gemma3:27b,gemma3:27b,2
45,gold_00046,711,Pedro: batman or superman??\r\nAlex: honestly....,Alex prefers The Flash over Batman and Superma...,艾力克斯更喜欢闪电侠，而不是蝙蝠侠和超人，他认为闪电侠拥有超人的速度以及穿梭多元宇宙的能力，...,Alex prefers the Flash to Barman and Superman ...,阿莱克斯更喜欢闪电侠，因为他的速度。,summarize_then_translate,gemma3:27b,gemma3:27b,2
46,gold_00047,737,Damian: are you downtown?\r\nEthan: yes\r\nEth...,"Damian asked Ethan, who is downtown, to buy hi...",达米安请求身处市中心的伊森帮他买烤肉串，因为他非常饥饿并且今天过得很糟糕。伊森勉强同意，但表...,Ethan will buy Damian a kebab. Damian had a ba...,伊森会请达米安吃烤肉串，达米安今天过得很糟糕。,summarize_then_translate,gemma3:27b,gemma3:27b,2
47,gold_00048,767,"Barry: I'm gonna go march in Women's strike, a...","Barry, Jake, and Dave are planning to attend t...",巴里、杰克和戴夫计划参加妇女罢工活动，并将于中午在校园附近集合。凯莉将与戴夫一同前往。,"Barry, Dave, Kelly, and Jake will meet around ...",巴里、戴夫、凯利和杰克将于12点在校园附近集合，参加妇女罢工。,summarize_then_translate,gemma3:27b,gemma3:27b,2
48,gold_00049,799,"Martha: Hey, can I ask you a question?\r\nOphe...",Martha asked Ophelia about the lenses she was ...,玛莎询问奥菲莉亚个人资料照片中佩戴的隐形眼镜，奥菲莉亚推荐了“疯狂眼镜”品牌，因为它价格合理...,Martha likes Ophelia's lenses and wants to buy...,玛莎喜欢奥菲莉娅的眼镜，想买类似的，奥菲莉娅是从crazy lens上买的。,summarize_then_translate,gemma3:27b,gemma3:27b,2
49,gold_00050,800,"Linda: Hi Dad, I want to buy flowers for mum! ...",Linda wants to buy flowers for her mum and ask...,琳达想为她的妈妈买花，并向她的爸爸迈克尔寻求建议。在琳达发送了可选花卉的照片后，迈克尔建议郁...,Linda wants to buy flowers for her mother and ...,琳达想给她妈妈买花，问迈克尔她喜欢哪种花。迈克尔建议琳达买小苍兰。,summarize_then_translate,gemma3:27b,gemma3:27b,2

In [16]:
# Cell 15: Compare ST outputs with references

comparison_columns = [
    "id",
    "test_index",
    "english_summary",
    "reference_english_summary",
    "final_summary",
    "reference_chinese_summary",
]

comparison_df = df[comparison_columns].copy()

comparison_df

,id,test_index,english_summary,reference_english_summary,final_summary,reference_chinese_summary
0,gold_00001,23,"Anne discovered Mark lied about his age, telli...",Mark lied to Anne about his age. Mark is 40.,安妮发现马克对自己的年龄说了谎，他告诉她自己30岁，但他的护照显示他实际年龄是40岁，这让她...,马克向安妮隐瞒了自己的年龄。他40岁了。
1,gold_00002,30,"Mary asked Carter for some money, and Carter s...",Mary ran out of money. Carter is going to lend...,玛丽向卡特请求了一些钱，卡特说他可以在一个小时后借给她，因为他现在在火车站。,玛丽的钱用完了，卡特打算一小时后借给她一点。
2,gold_00003,39,Tina was delayed at the airport and had a talk...,Tina will catch the evening flight back home. ...,蒂娜在机场延误，并且在回家的航班上遇到了一位健谈的飞行员。艾拉将要参加一个重要的会议，并请蒂...,蒂娜将乘晚间航班回家。阿拉正在去开会的路上。她会让蒂娜知道事情的进展。
3,gold_00004,65,Ana and Catherine plan to visit their grandma ...,Ana wants to visit grandma tomorrow. Catherine...,安娜和凯瑟琳计划明天去看望她们的奶奶，凯瑟琳会在她醒来后给安娜打电话。然后她们互相道了晚安。,安娜明天想去看望奶奶。凯瑟琳会和她一起去。她起床后会给安娜打电话。
4,gold_00005,66,"Joyce shared a link for a cheap ticket, prompt...",Edson is booking his ticket now.,乔伊斯分享了一个廉价机票的链接，促使迈克尔承认价格，而埃德森立即预订了一张机票。,埃德森正在订票。
5,gold_00006,67,"Jane and Steven are planning to meet, and Jane...",Jane wants to leave at 4.30 instead of 5 becau...,简和史蒂文计划见面，简希望因为路途遥远而将见面时间提前到下午4点30分，而不是5点，史蒂文同...,简想4点半就走，而不是等到5点，因为谷歌地图提示300公里的车程至少需要3小时，她不想迟到。...
6,gold_00007,78,Fiona wants to make Tina’s tart for dinner wit...,Fiona wants to prepare dinner for Chris. She i...,菲奥娜想为克里斯做晚餐，想做蒂娜的馅饼，于是向蒂娜寻求帮助，并承认她买好了派皮，之前因为过度...,菲奥娜想为克里斯准备晚餐。她想起了蒂娜做的馅饼。蒂娜会帮她做的。
7,gold_00008,86,The group is planning to go to a classy New Ye...,"Nathalie, Olafur and Zoe are planning the New ...",该团队计划前往苏荷区的一家俱乐部参加一场高档的新年晚会，可能是在“蒂芙尼的早餐”俱乐部，他们...,娜塔莉、奥拉维尔和佐伊正在做新年前夜的计划。娜塔莉想要有格调的。但奥拉维尔不喜欢歌剧。他们想...
8,gold_00009,120,"John and Joan agreed to see ""A Star is Born"" o...","Joan and John are going to watch ""A Star is Bo...",约翰和琼同意在周四晚上8点左右观看电影《一个明星的诞生》，此前琼表示周三她很忙。约翰会把电影...,琼和约翰星期四晚上8点左右去看《一个明星的诞生》。
9,gold_00010,137,Cameron is unable to bring Peyton a video game...,Peyton is expecting Cameron to bring the video...,卡梅隆无法给佩顿送游戏机，因为他需要出城另待一周，这促使佩顿建议通过快递寄送。佩顿随后要求卡...,佩顿希望卡梅隆能带游戏机过来，但是卡梅隆可能还要再缺席一周。
10,gold_00011,139,Paul returned home after a busy day and realiz...,Paul forgot about his physiotherapy and he wil...,保罗忙碌了一天后回到家，意识到他错过了物理治疗预约，但他会重新安排。艾玛会晚点回家，保罗提出...,保罗忘记去做理疗了，得重新预约。艾玛午夜后回家，所以保罗会给她准备一些吃的。
11,gold_00012,192,Harris informed Lena that his friend Aoki pass...,"Harris' friend, Aoki, who lives in Michigan, d...",哈里斯告知莉娜，他的朋友青木昨天去世了，他对此感到难过。他几个月前见过青木一次，因为她住在密...,哈里斯的朋友青木住在密歇根州，昨天去世了。哈里斯有几个月没见她了。
12,gold_00013,210,Yaz and Mary both admit to overindulging but a...,Yaz and Mary are meeting tonight around 6 and ...,雅兹和玛丽都承认自己暴饮暴食，但同意今晚参加她们的减肥俱乐部会议，预计会受到她们以前的烹饪老...,亚兹和玛丽今晚6点左右见面，一起去减肥俱乐部。他们估计吃得太多会被骂。
13,gold_00014,211,"Camille is sick, and Ellie and Aaliyah are at ...",Ellie's class is in 342 on the second floor.,卡米尔生病了，埃莉和阿利亚在大学，她们的课程将在二楼342教室举行。,艾莉的班级在二楼342教室。
14,gold_00015,212,Nathan and Aaron found a funny video of a woma...,Nathan and Aaron are discussing a video which ...,内森和亚伦发现了一个关于一位女士做出奇怪表情的搞笑视频，亚伦将其比作他的猫，并开玩笑说这可能...,内森和亚伦正在讨论内森发来的视频。
15,gold_00016,215,Several people discussed what they are watchin...,"Freddie, Kelly, Jim, Greg, Bob, Mike, Mary, Al...",几个人讨论了他们在观看的奈飞剧集，包括《广告狂人》、《王冠》、《异星出lander》、《僵尸...,弗雷迪、凯利、吉姆、格雷格、鲍勃、迈克、玛丽、艾伦和南希正在netflix上观看不同的节目。
16,gold_00017,244,Jones and Angelina reconnected and agreed to m...,Jones and Angelina will meet in town in the af...,琼斯和安吉丽娜重逢并同意当天下午在镇上见面，琼斯承诺确认具体地点。,琼斯和安吉丽娜下午会在城里见面。
17,gold_00018,285,"Casey did her own nails, which Amelia and Kris...",Casey got a new nail polish and did her nails ...,凯西自己做了美甲，阿米莉亚和克里斯汀非常喜欢，并要求她复制，但凯西拒绝了，因为这花费了她四个...,凯西买了新指甲油，自己做了指甲。她花了近4个小时，所以她不会帮朋友做指甲，因为耗时太长了。
18,gold_00019,319,Sue asked Steve to call her upon receiving the...,Steve is calling Sue at her request.,苏请史蒂夫收到消息后给她打电话，因为这很重要，史蒂夫确认他正在打电话。,史蒂夫正按照苏的要求给她打电话。
19,gold_00020,346,Gemma is inviting Timmy and potentially his da...,"Gemma will invite Timmy and his Date, as well ...",杰玛正在邀请蒂米和他的潜在约会对象，以及洛娜和米歇尔参加聚会，她承认她希望被邀请参加洛娜和米...,杰玛将邀请蒂米和他的约会对象，以及罗娜和米歇尔参加她的婚礼。
20,gold_00021,355,Ann congratulated Sue and Julie on a job well ...,"Ann, Sue and Julie did a great job and they wi...",安妮祝贺苏和朱莉工作完成得很好，她们都同意那天晚上庆祝。,安、苏和朱莉做得很好，今晚他们会举行一个小小的庆祝活动。
21,gold_00022,367,Steve informed his mum that the dishwasher was...,Steve is happy that he got a new dishwasher in...,史蒂夫告知他的母亲洗碗机已经安装完毕，并且运行良好，他指出洗碗机运行安静，而且可能是12套餐...,史蒂夫很高兴他装了一台新的洗碗机。
22,gold_00023,393,Lara confirmed to Marika that she is coming to...,Marika is coming today.,拉拉向玛丽卡确认她今天会来。,玛丽卡今天会来。
23,gold_00024,417,Miranda requested to cancel their meeting due ...,Miranda can't make her meeting with Stephanie ...,米兰达因工作原因请求取消他们的会议，解释说年轻医生长时间工作是很常见的现象，对此斯蒂芬妮开玩...,米兰达不能去见斯蒂芬妮，因为她要工作。
24,gold_00025,432,Javier asked Judie for English-speaking tattoo...,Javier was initially eager to have a tatoo don...,哈维尔向朱迪询问会说英语的纹身店，朱迪推荐了华沙印克，她的女朋友在那里花了一千元做了纹身。哈...,哈维尔最初很想在warsaw ink纹身，但价格太高了。他决定去哥伦比亚做纹身。
25,gold_00026,433,Sam complimented Jessica and Michael on their ...,Sam appreciates the hotel owned by Jessica and...,萨姆赞美了杰西卡和迈克尔的酒店，并确认他将于8月15日下午2点左右到达，表达了再次见到他们的...,山姆很喜欢杰西卡和迈克尔的酒店。他会在8月15日下午2点左右去那里。
26,gold_00027,442,"Terence accused Daniel of stealing his money, ...",Terence accused Daniel of taking his money. Te...,特伦斯指责丹尼尔偷了他的钱，但后来在找到钱后道歉。丹尼尔表达了他对这虚假指控的愤怒。,特伦斯指控丹尼尔偷了他的钱。后来他找到了钱，就向丹尼尔道歉。但是丹尼尔还在生气。
27,gold_00028,499,Natacha offered to pick Charles up at the RER ...,Charles has just landed and he will be at RER ...,娜塔莎提出要从火车站接查尔斯，他大约在下午5点30分到达，并在韦西内站时给她打电话。,查尔斯刚刚落地，他会在下午五点半到达rer，娜塔夏会在那里接他。
28,gold_00029,528,Ann is at school for extra math classes and wi...,Ann is still at school. She will be home at 7 ...,安妮在学校上额外的数学课，晚上7点会回家，梅格那时可以和她见面。,安还在学校，她7点会回家，这样她就可以和麦格见面了。
29,gold_00030,532,Pete is going to check if the store has pear y...,Pete will get a pear yogurt for Jen if they ha...,皮特将去查看商店是否有梨味酸奶给珍，如果没有，他就不要购买任何酸奶，因为珍不喜欢其他口味。,如果商店里有梨味酸奶， 皮特会给珍买的。
30,gold_00031,536,Christie and Katie both feel tired after atten...,Christie and Katie are tired after the party. ...,克里斯蒂和凯蒂在参加了一个她们都很喜欢的精彩派对后，都感到疲惫。,克里斯蒂和凯蒂在聚会后累了。他们都玩得很开心。
31,gold_00032,537,Sam and Carla arranged to meet at a cafe in Me...,Carla has a day off tomorrow. She will meet Sa...,萨姆和卡拉约定明天下午两点在米恩伍德的一家咖啡馆见面，因为那天是卡拉的休息日。他们都表达了对...,卡拉明天有一天假。她将在下午两点在meanwood的一个咖啡馆和山姆见面。
32,gold_00033,544,Joana and Sandy decided to play either Dixit o...,Joana will bring Sandy some games like dixit a...,约阿娜和桑迪决定玩《迪克西特》或《卡卡颂》，约阿娜会把游戏带给桑迪。,琼娜将为桑迪带来一些像迪克西特和卡尔卡松这样的游戏。
33,gold_00034,548,Steve and Rob both recently acquired Dream The...,Steve and Rob will talk about new Dream Theate...,史蒂夫和罗伯最近都获得了梦剧场的新专辑，并计划稍后分享他们对它的看法。他们将在两人都听过专辑...,史蒂夫和罗伯将在听完后谈论新的梦剧场专辑。
34,gold_00035,551,Joy sent Peter the link to her beauty shop and...,Joy sent Peter the link to her beauty shop.,乔伊将她的美容店链接发送给彼得，并邀请他提出任何问题。彼得确认已收到链接，并表示他会查看。,乔伊把她美容店的链接发给了彼得。
35,gold_00036,590,"Ethan, Leo, and Noah are discussing the Solsta...",Ethan and Leo are going to see Sólstafir on 21...,伊森、里奥和诺亚正在讨论索尔斯塔菲尔乐队11月21日的演唱会，里奥和伊森鼓励诺亚参加，尽管可...,伊森和里奥要在21点11分去见索斯塔弗。诺亚也想去，但他可能得工作到很晚。
36,gold_00037,598,A cat ran onto the pitch at Goodison Park duri...,A sweet little black cat got into the pitch du...,在一场比赛中，一只猫跑进了古迪逊公园球场，引得包括布拉德利、吉尔和茱莉亚在内的球迷们感到有趣...,在埃弗顿的足球比赛中，一只可爱的小黑猫钻进了球场。
37,gold_00038,605,Sean is coming over to Barbara's place with hi...,"Barbara, Sean and Zac are meeting at Barbara's...",肖恩将带着他的狗去芭芭拉家，并且计划过夜。扎克也在路上。,芭芭拉、肖恩和扎克今晚在芭芭拉家见面。肖恩会把狗带来的，肖恩和扎克会在这里过夜。
38,gold_00039,616,Jake received a Team of the Week player card a...,Jake has got his first TOTW this year. Tom doe...,杰克获得了一张本周最佳球员卡，并计划出售因为它不适合他的球队，而汤姆今年尽管游戏技术精湛，但...,杰克今年拿到了第一个totw ，汤姆的团队并不出色。
39,gold_00040,621,Phil and Deana are trying to figure out who th...,Phil received a card from Deana. Constantine w...,菲尔和迪安娜正在试图弄清楚在迪安娜的车里发现的太阳镜属于谁，但他们俩都不认识这副太阳镜，艾德...,菲尔收到了迪安娜的一张卡片，康斯坦丁很开心。菲尔有副墨镜。蒂娜在后面收音机上面找到的。迪安娜...
40,gold_00041,635,Mell and Gloria agreed to have a BBQ at Mell’s...,Gloria and Mell plan to have a barbeque at Mel...,梅尔和格洛丽亚同意本周六在梅尔家举行烧烤，她们都表示对塔德的姐姐搬到苏格兰感到欣慰。梅尔承认...,格洛丽亚和梅尔计划星期六在梅尔家吃烧烤。他们很高兴，因为泰德的姐姐搬到了苏格兰。梅尔需要格洛...
41,gold_00042,649,Callan’s Samsung S8 has a black screen and is ...,"Callan's Samsung S8 overheats, so he's going t...",卡兰的三星S8屏幕变黑并过热，之前也出现过类似问题，但他将前往商店进行保修维修，因为他会定期...,卡伦的三星s8过热了，所以他要去店里修理。
42,gold_00043,676,Anna has a stomachache and isn't sure what cau...,Anna got an awful stomachache at night but she...,安娜感到胃痛，她不确定是什么原因引起的，但她的妈妈建议可能是她吃的东西。如果情况没有好转，她...,安娜夜里胃疼得厉害，但她不知道其中的原因。她的妈妈乔安娜会用新鲜的薄荷叶为她做热茶。
43,gold_00044,678,Kate and Sam are downstairs near reception and...,Kate and Jeff are downstairs in a room next to...,凯特和萨姆在接待区楼下发现一个蛋糕正在被一位女士装饰，蛋糕上有一个用杏仁糖制作的大型男性生殖...,凯特和杰夫在楼下接待处旁边的一个房间里。有位女士正在做杏仁蛋糕。
44,gold_00045,690,The group discusses a politician—likely Trump—...,"Mia, Jennifer, Karine and Peter do not like Tr...",该群体讨论了一位政客——很可能是 特朗普 —并一致认为他并非仅仅是老年痴呆，而是故意利用恐惧...,米亚、珍妮弗、卡琳和彼得不喜欢特朗普。
45,gold_00046,711,Alex prefers The Flash over Batman and Superma...,Alex prefers the Flash to Barman and Superman ...,艾力克斯更喜欢闪电侠，而不是蝙蝠侠和超人，他认为闪电侠拥有超人的速度以及穿梭多元宇宙的能力，...,阿莱克斯更喜欢闪电侠，因为他的速度。
46,gold_00047,737,"Damian asked Ethan, who is downtown, to buy hi...",Ethan will buy Damian a kebab. Damian had a ba...,达米安请求身处市中心的伊森帮他买烤肉串，因为他非常饥饿并且今天过得很糟糕。伊森勉强同意，但表...,伊森会请达米安吃烤肉串，达米安今天过得很糟糕。
47,gold_00048,767,"Barry, Jake, and Dave are planning to attend t...","Barry, Dave, Kelly, and Jake will meet around ...",巴里、杰克和戴夫计划参加妇女罢工活动，并将于中午在校园附近集合。凯莉将与戴夫一同前往。,巴里、戴夫、凯利和杰克将于12点在校园附近集合，参加妇女罢工。
48,gold_00049,799,Martha asked Ophelia about the lenses she was ...,Martha likes Ophelia's lenses and wants to buy...,玛莎询问奥菲莉亚个人资料照片中佩戴的隐形眼镜，奥菲莉亚推荐了“疯狂眼镜”品牌，因为它价格合理...,玛莎喜欢奥菲莉娅的眼镜，想买类似的，奥菲莉娅是从crazy lens上买的。
49,gold_00050,800,Linda wants to buy flowers for her mum and ask...,Linda wants to buy flowers for her mother and ...,琳达想为她的妈妈买花，并向她的爸爸迈克尔寻求建议。在琳达发送了可选花卉的照片后，迈克尔建议郁...,琳达想给她妈妈买花，问迈克尔她喜欢哪种花。迈克尔建议琳达买小苍兰。

In [17]:
# Cell 16: Inspect ST outputs

if not df.empty:
    inspection_columns = [
        "id",
        "test_index",
        "dialogue",
        "english_summary",
        "reference_english_summary",
        "final_summary",
        "reference_chinese_summary",
    ]

    inspection_df = df[inspection_columns].copy()
    display(inspection_df)
else:
    print("No results found.")

,id,test_index,dialogue,english_summary,reference_english_summary,final_summary,reference_chinese_summary
0,gold_00001,23,"Anne: You were right, he was lying to me :/\nI...","Anne discovered Mark lied about his age, telli...",Mark lied to Anne about his age. Mark is 40.,安妮发现马克对自己的年龄说了谎，他告诉她自己30岁，但他的护照显示他实际年龄是40岁，这让她...,马克向安妮隐瞒了自己的年龄。他40岁了。
1,gold_00002,30,"Mary: hey, im kinda broke, lend me a few box\r...","Mary asked Carter for some money, and Carter s...",Mary ran out of money. Carter is going to lend...,玛丽向卡特请求了一些钱，卡特说他可以在一个小时后借给她，因为他现在在火车站。,玛丽的钱用完了，卡特打算一小时后借给她一点。
2,gold_00003,39,"Tina: I'll tell you something, this Emirate st...",Tina was delayed at the airport and had a talk...,Tina will catch the evening flight back home. ...,蒂娜在机场延误，并且在回家的航班上遇到了一位健谈的飞行员。艾拉将要参加一个重要的会议，并请蒂...,蒂娜将乘晚间航班回家。阿拉正在去开会的路上。她会让蒂娜知道事情的进展。
3,gold_00004,65,Ana: You sleeping?\r\nCatherine: Not yet.\r\nA...,Ana and Catherine plan to visit their grandma ...,Ana wants to visit grandma tomorrow. Catherine...,安娜和凯瑟琳计划明天去看望她们的奶奶，凯瑟琳会在她醒来后给安娜打电话。然后她们互相道了晚安。,安娜明天想去看望奶奶。凯瑟琳会和她一起去。她起床后会给安娜打电话。
4,gold_00005,66,Joyce: Check this out!\r\nJoyce: <link>\r\nMic...,"Joyce shared a link for a cheap ticket, prompt...",Edson is booking his ticket now.,乔伊斯分享了一个廉价机票的链接，促使迈克尔承认价格，而埃德森立即预订了一张机票。,埃德森正在订票。
5,gold_00006,67,Jane: google maps says it is at least 3h <file...,"Jane and Steven are planning to meet, and Jane...",Jane wants to leave at 4.30 instead of 5 becau...,简和史蒂文计划见面，简希望因为路途遥远而将见面时间提前到下午4点30分，而不是5点，史蒂文同...,简想4点半就走，而不是等到5点，因为谷歌地图提示300公里的车程至少需要3小时，她不想迟到。...
6,gold_00007,78,"Fiona: Are you free?\r\nTina: Yes, what's up?\...",Fiona wants to make Tina’s tart for dinner wit...,Fiona wants to prepare dinner for Chris. She i...,菲奥娜想为克里斯做晚餐，想做蒂娜的馅饼，于是向蒂娜寻求帮助，并承认她买好了派皮，之前因为过度...,菲奥娜想为克里斯准备晚餐。她想起了蒂娜做的馅饼。蒂娜会帮她做的。
7,gold_00008,86,Olafur: are we doing anything for New Year's E...,The group is planning to go to a classy New Ye...,"Nathalie, Olafur and Zoe are planning the New ...",该团队计划前往苏荷区的一家俱乐部参加一场高档的新年晚会，可能是在“蒂芙尼的早餐”俱乐部，他们...,娜塔莉、奥拉维尔和佐伊正在做新年前夜的计划。娜塔莉想要有格调的。但奥拉维尔不喜欢歌剧。他们想...
8,gold_00009,120,"John: wanna go see ""A Star is Born"" on Wed?\r\...","John and Joan agreed to see ""A Star is Born"" o...","Joan and John are going to watch ""A Star is Bo...",约翰和琼同意在周四晚上8点左右观看电影《一个明星的诞生》，此前琼表示周三她很忙。约翰会把电影...,琼和约翰星期四晚上8点左右去看《一个明星的诞生》。
9,gold_00010,137,Peyton: I have been asking you to bring that v...,Cameron is unable to bring Peyton a video game...,Peyton is expecting Cameron to bring the video...,卡梅隆无法给佩顿送游戏机，因为他需要出城另待一周，这促使佩顿建议通过快递寄送。佩顿随后要求卡...,佩顿希望卡梅隆能带游戏机过来，但是卡梅隆可能还要再缺席一周。
10,gold_00011,139,Paul: I just came back home\r\nPaul: What a bu...,Paul returned home after a busy day and realiz...,Paul forgot about his physiotherapy and he wil...,保罗忙碌了一天后回到家，意识到他错过了物理治疗预约，但他会重新安排。艾玛会晚点回家，保罗提出...,保罗忘记去做理疗了，得重新预约。艾玛午夜后回家，所以保罗会给她准备一些吃的。
11,gold_00012,192,"Harris: How are U?\r\nLena: Fine, U?\r\nHarris...",Harris informed Lena that his friend Aoki pass...,"Harris' friend, Aoki, who lives in Michigan, d...",哈里斯告知莉娜，他的朋友青木昨天去世了，他对此感到难过。他几个月前见过青木一次，因为她住在密...,哈里斯的朋友青木住在密歇根州，昨天去世了。哈里斯有几个月没见她了。
12,gold_00013,210,Yaz: Going to slimming club tonight?\r\nMary: ...,Yaz and Mary both admit to overindulging but a...,Yaz and Mary are meeting tonight around 6 and ...,雅兹和玛丽都承认自己暴饮暴食，但同意今晚参加她们的减肥俱乐部会议，预计会受到她们以前的烹饪老...,亚兹和玛丽今晚6点左右见面，一起去减肥俱乐部。他们估计吃得太多会被骂。
13,gold_00014,211,"Ellie: hey, are you at the university?\r\nAali...","Camille is sick, and Ellie and Aaliyah are at ...",Ellie's class is in 342 on the second floor.,卡米尔生病了，埃莉和阿利亚在大学，她们的课程将在二楼342教室举行。,艾莉的班级在二楼342教室。
14,gold_00015,212,Nathan: <file_video>\r\nAaron: OMG!!! \r\nAaro...,Nathan and Aaron found a funny video of a woma...,Nathan and Aaron are discussing a video which ...,内森和亚伦发现了一个关于一位女士做出奇怪表情的搞笑视频，亚伦将其比作他的猫，并开玩笑说这可能...,内森和亚伦正在讨论内森发来的视频。
15,gold_00016,215,Freddie: What are you watching on Netflix? I'v...,Several people discussed what they are watchin...,"Freddie, Kelly, Jim, Greg, Bob, Mike, Mary, Al...",几个人讨论了他们在观看的奈飞剧集，包括《广告狂人》、《王冠》、《异星出lander》、《僵尸...,弗雷迪、凯利、吉姆、格雷格、鲍勃、迈克、玛丽、艾伦和南希正在netflix上观看不同的节目。
16,gold_00017,244,Jones: Hey.\r\nAngelina: Hey.\r\nAngelina: Lon...,Jones and Angelina reconnected and agreed to m...,Jones and Angelina will meet in town in the af...,琼斯和安吉丽娜重逢并同意当天下午在镇上见面，琼斯承诺确认具体地点。,琼斯和安吉丽娜下午会在城里见面。
17,gold_00018,285,Casey: <file_photo>\r\nAmelia: these are so ni...,"Casey did her own nails, which Amelia and Kris...",Casey got a new nail polish and did her nails ...,凯西自己做了美甲，阿米莉亚和克里斯汀非常喜欢，并要求她复制，但凯西拒绝了，因为这花费了她四个...,凯西买了新指甲油，自己做了指甲。她花了近4个小时，所以她不会帮朋友做指甲，因为耗时太长了。
18,gold_00019,319,Sue: Call me when you get this.\r\nSue: it's i...,Sue asked Steve to call her upon receiving the...,Steve is calling Sue at her request.,苏请史蒂夫收到消息后给她打电话，因为这很重要，史蒂夫确认他正在打电话。,史蒂夫正按照苏的要求给她打电话。
19,gold_00020,346,"Timmy: Who do u wanna invite?\r\nGemma: Well, ...",Gemma is inviting Timmy and potentially his da...,"Gemma will invite Timmy and his Date, as well ...",杰玛正在邀请蒂米和他的潜在约会对象，以及洛娜和米歇尔参加聚会，她承认她希望被邀请参加洛娜和米...,杰玛将邀请蒂米和他的约会对象，以及罗娜和米歇尔参加她的婚礼。
20,gold_00021,355,"Ann: Congratulations!!\r\nAnn: You did great, ...",Ann congratulated Sue and Julie on a job well ...,"Ann, Sue and Julie did a great job and they wi...",安妮祝贺苏和朱莉工作完成得很好，她们都同意那天晚上庆祝。,安、苏和朱莉做得很好，今晚他们会举行一个小小的庆祝活动。
21,gold_00022,367,Steve: hiya the dishwasher has turned up\r\nMu...,Steve informed his mum that the dishwasher was...,Steve is happy that he got a new dishwasher in...,史蒂夫告知他的母亲洗碗机已经安装完毕，并且运行良好，他指出洗碗机运行安静，而且可能是12套餐...,史蒂夫很高兴他装了一台新的洗碗机。
22,gold_00023,393,Marika: Are you coming today?\r\nLara: Yes!\r\...,Lara confirmed to Marika that she is coming to...,Marika is coming today.,拉拉向玛丽卡确认她今天会来。,玛丽卡今天会来。
23,gold_00024,417,"Miranda: Hi S, could we cancel tomorrow's meet...",Miranda requested to cancel their meeting due ...,Miranda can't make her meeting with Stephanie ...,米兰达因工作原因请求取消他们的会议，解释说年轻医生长时间工作是很常见的现象，对此斯蒂芬妮开玩...,米兰达不能去见斯蒂芬妮，因为她要工作。
24,gold_00025,432,Javier: Hey do you know any tattoo parlors ove...,Javier asked Judie for English-speaking tattoo...,Javier was initially eager to have a tatoo don...,哈维尔向朱迪询问会说英语的纹身店，朱迪推荐了华沙印克，她的女朋友在那里花了一千元做了纹身。哈...,哈维尔最初很想在warsaw ink纹身，但价格太高了。他决定去哥伦比亚做纹身。
25,gold_00026,433,"Sam: You own a really nice hotel, guys 😊\r\nJe...",Sam complimented Jessica and Michael on their ...,Sam appreciates the hotel owned by Jessica and...,萨姆赞美了杰西卡和迈克尔的酒店，并确认他将于8月15日下午2点左右到达，表达了再次见到他们的...,山姆很喜欢杰西卡和迈克尔的酒店。他会在8月15日下午2点左右去那里。
26,gold_00027,442,"Terence: What the hell, Danny. You took my mon...","Terence accused Daniel of stealing his money, ...",Terence accused Daniel of taking his money. Te...,特伦斯指责丹尼尔偷了他的钱，但后来在找到钱后道歉。丹尼尔表达了他对这虚假指控的愤怒。,特伦斯指控丹尼尔偷了他的钱。后来他找到了钱，就向丹尼尔道歉。但是丹尼尔还在生气。
27,gold_00028,499,"Natacha: hi, i can come and pick you up at the...",Natacha offered to pick Charles up at the RER ...,Charles has just landed and he will be at RER ...,娜塔莎提出要从火车站接查尔斯，他大约在下午5点30分到达，并在韦西内站时给她打电话。,查尔斯刚刚落地，他会在下午五点半到达rer，娜塔夏会在那里接他。
28,gold_00029,528,Meg: still at school?\r\nAnn: i have extra mat...,Ann is at school for extra math classes and wi...,Ann is still at school. She will be home at 7 ...,安妮在学校上额外的数学课，晚上7点会回家，梅格那时可以和她见面。,安还在学校，她7点会回家，这样她就可以和麦格见面了。
29,gold_00030,532,Pete: What flavour yogurt did you want again? ...,Pete is going to check if the store has pear y...,Pete will get a pear yogurt for Jen if they ha...,皮特将去查看商店是否有梨味酸奶给珍，如果没有，他就不要购买任何酸奶，因为珍不喜欢其他口味。,如果商店里有梨味酸奶， 皮特会给珍买的。
30,gold_00031,536,Christie: how are you after the party?\r\nKati...,Christie and Katie both feel tired after atten...,Christie and Katie are tired after the party. ...,克里斯蒂和凯蒂在参加了一个她们都很喜欢的精彩派对后，都感到疲惫。,克里斯蒂和凯蒂在聚会后累了。他们都玩得很开心。
31,gold_00032,537,"Sam: Are you working tomorrow?\r\nCarla: No, i...",Sam and Carla arranged to meet at a cafe in Me...,Carla has a day off tomorrow. She will meet Sa...,萨姆和卡拉约定明天下午两点在米恩伍德的一家咖啡馆见面，因为那天是卡拉的休息日。他们都表达了对...,卡拉明天有一天假。她将在下午两点在meanwood的一个咖啡馆和山姆见面。
32,gold_00033,544,Joana: wana play some games?\r\nSandy: what ga...,Joana and Sandy decided to play either Dixit o...,Joana will bring Sandy some games like dixit a...,约阿娜和桑迪决定玩《迪克西特》或《卡卡颂》，约阿娜会把游戏带给桑迪。,琼娜将为桑迪带来一些像迪克西特和卡尔卡松这样的游戏。
33,gold_00034,548,Steve: Bought the new Dream Theater album 5 mi...,Steve and Rob both recently acquired Dream The...,Steve and Rob will talk about new Dream Theate...,史蒂夫和罗伯最近都获得了梦剧场的新专辑，并计划稍后分享他们对它的看法。他们将在两人都听过专辑...,史蒂夫和罗伯将在听完后谈论新的梦剧场专辑。
34,gold_00035,551,Peter: Can you send me the link of your beauty...,Joy sent Peter the link to her beauty shop and...,Joy sent Peter the link to her beauty shop.,乔伊将她的美容店链接发送给彼得，并邀请他提出任何问题。彼得确认已收到链接，并表示他会查看。,乔伊把她美容店的链接发给了彼得。
35,gold_00036,590,Ethan: who's going to see solstafir?\r\nNoah: ...,"Ethan, Leo, and Noah are discussing the Solsta...",Ethan and Leo are going to see Sólstafir on 21...,伊森、里奥和诺亚正在讨论索尔斯塔菲尔乐队11月21日的演唱会，里奥和伊森鼓励诺亚参加，尽管可...,伊森和里奥要在21点11分去见索斯塔弗。诺亚也想去，但他可能得工作到很晚。
36,gold_00037,598,Bradley: haha look a cat invaded the pitch at ...,A cat ran onto the pitch at Goodison Park duri...,A sweet little black cat got into the pitch du...,在一场比赛中，一只猫跑进了古迪逊公园球场，引得包括布拉德利、吉尔和茱莉亚在内的球迷们感到有趣...,在埃弗顿的足球比赛中，一只可爱的小黑猫钻进了球场。
37,gold_00038,605,"Barbara: I'm home already, you can come over\r...",Sean is coming over to Barbara's place with hi...,"Barbara, Sean and Zac are meeting at Barbara's...",肖恩将带着他的狗去芭芭拉家，并且计划过夜。扎克也在路上。,芭芭拉、肖恩和扎克今晚在芭芭拉家见面。肖恩会把狗带来的，肖恩和扎克会在这里过夜。
38,gold_00039,616,"Jake: dude, I just pulled a TOTW\nJake: my fir...",Jake received a Team of the Week player card a...,Jake has got his first TOTW this year. Tom doe...,杰克获得了一张本周最佳球员卡，并计划出售因为它不适合他的球队，而汤姆今年尽管游戏技术精湛，但...,杰克今年拿到了第一个totw ，汤姆的团队并不出色。
39,gold_00040,621,Phil: Good evening Deana! Many thanks for this...,Phil and Deana are trying to figure out who th...,Phil received a card from Deana. Constantine w...,菲尔和迪安娜正在试图弄清楚在迪安娜的车里发现的太阳镜属于谁，但他们俩都不认识这副太阳镜，艾德...,菲尔收到了迪安娜的一张卡片，康斯坦丁很开心。菲尔有副墨镜。蒂娜在后面收音机上面找到的。迪安娜...
40,gold_00041,635,Mell: Hi there! How are you doing?\r\nGloria: ...,Mell and Gloria agreed to have a BBQ at Mell’s...,Gloria and Mell plan to have a barbeque at Mel...,梅尔和格洛丽亚同意本周六在梅尔家举行烧烤，她们都表示对塔德的姐姐搬到苏格兰感到欣慰。梅尔承认...,格洛丽亚和梅尔计划星期六在梅尔家吃烧烤。他们很高兴，因为泰德的姐姐搬到了苏格兰。梅尔需要格洛...
41,gold_00042,649,Callan: Something's wrong with my Samsung S8.\...,Callan’s Samsung S8 has a black screen and is ...,"Callan's Samsung S8 overheats, so he's going t...",卡兰的三星S8屏幕变黑并过热，之前也出现过类似问题，但他将前往商店进行保修维修，因为他会定期...,卡伦的三星s8过热了，所以他要去店里修理。
42,gold_00043,676,"Anna: Mum, I have a awful stomachache.\r\nJoan...",Anna has a stomachache and isn't sure what cau...,Anna got an awful stomachache at night but she...,安娜感到胃痛，她不确定是什么原因引起的，但她的妈妈建议可能是她吃的东西。如果情况没有好转，她...,安娜夜里胃疼得厉害，但她不知道其中的原因。她的妈妈乔安娜会用新鲜的薄荷叶为她做热茶。
43,gold_00044,678,Sam: Where are you?\nKate: downstairs\nSam: al...,Kate and Sam are downstairs near reception and...,Kate and Jeff are downstairs in a room next to...,凯特和萨姆在接待区楼下发现一个蛋糕正在被一位女士装饰，蛋糕上有一个用杏仁糖制作的大型男性生殖...,凯特和杰夫在楼下接待处旁边的一个房间里。有位女士正在做杏仁蛋糕。
44,gold_00045,690,"Mia: God, he keeps talking about the stupid wa...",The group discusses a politician—likely Trump—...,"Mia, Jennifer, Karine and Peter do not like Tr...",该群体讨论了一位政客——很可能是 特朗普 —并一致认为他并非仅仅是老年痴呆，而是故意利用恐惧...,米亚、珍妮弗、卡琳和彼得不喜欢特朗普。
45,gold_00046,711,Pedro: batman or superman??\r\nAlex: honestly....,Alex prefers The Flash over Batman and Superma...,Alex prefers the Flash to Barman and Superman ...,艾力克斯更喜欢闪电侠，而不是蝙蝠侠和超人，他认为闪电侠拥有超人的速度以及穿梭多元宇宙的能力，...,阿莱克斯更喜欢闪电侠，因为他的速度。
46,gold_00047,737,Damian: are you downtown?\r\nEthan: yes\r\nEth...,"Damian asked Ethan, who is downtown, to buy hi...",Ethan will buy Damian a kebab. Damian had a ba...,达米安请求身处市中心的伊森帮他买烤肉串，因为他非常饥饿并且今天过得很糟糕。伊森勉强同意，但表...,伊森会请达米安吃烤肉串，达米安今天过得很糟糕。
47,gold_00048,767,"Barry: I'm gonna go march in Women's strike, a...","Barry, Jake, and Dave are planning to attend t...","Barry, Dave, Kelly, and Jake will meet around ...",巴里、杰克和戴夫计划参加妇女罢工活动，并将于中午在校园附近集合。凯莉将与戴夫一同前往。,巴里、戴夫、凯利和杰克将于12点在校园附近集合，参加妇女罢工。
48,gold_00049,799,"Martha: Hey, can I ask you a question?\r\nOphe...",Martha asked Ophelia about the lenses she was ...,Martha likes Ophelia's lenses and wants to buy...,玛莎询问奥菲莉亚个人资料照片中佩戴的隐形眼镜，奥菲莉亚推荐了“疯狂眼镜”品牌，因为它价格合理...,玛莎喜欢奥菲莉娅的眼镜，想买类似的，奥菲莉娅是从crazy lens上买的。
49,gold_00050,800,"Linda: Hi Dad, I want to buy flowers for mum! ...",Linda wants to buy flowers for her mum and ask...,Linda wants to buy flowers for her mother and ...,琳达想为她的妈妈买花，并向她的爸爸迈克尔寻求建议。在琳达发送了可选花卉的照片后，迈克尔建议郁...,琳达想给她妈妈买花，问迈克尔她喜欢哪种花。迈克尔建议琳达买小苍兰。