# Semantic-Agent Pipeline for English-to-Chinese Dialogue Summarization

This notebook implements a local semantic-agent pipeline for English-to-Chinese cross-lingual dialogue summarization.

The semantic pipeline uses three local small language model agents. Agent 1 reads the original English dialogue and extracts a structured semantic representation, including participants, speaker intent, actor/action/recipient relations, key events, and the final outcome. Agent 2 selects the most salient events and generates a draft Chinese summary. Agent 3 verifies the draft summary against the original dialogue and revises it only if necessary.

```text
English Dialogue
→ Agent 1: Semantic Understanding Agent
→ Agent 2: Event Selection and Chinese Summary Generation Agent
→ Agent 3: Verification and Revision Agent
→ Final Chinese Summary
```

The pipeline consists of three agents:

```text
Agent 1: Semantic Understanding Agent
Input: original English dialogue
Output: structured semantic representation

Agent 2: Event Selection and Chinese Summary Generation Agent
Input: structured semantic representation from Agent 1
Output: selected events and draft Chinese summary

Agent 3: Verification and Revision Agent
Input: original dialogue + Agent 2 selected events and draft summary
Output: revised final Chinese summary
```
This setup is used as the proposed semantic-agent pipeline. Unlike Direct, Translate-then-Summarize, and Summarize-then-Translate baselines, this pipeline explicitly represents pragmatic meaning, semantic roles, actor/action relations, and final dialogue outcomes before generating the final Chinese summary.

The local small language models are served through Ollama. The notebook controls prompt design, JSON parsing, intermediate output inspection, verification/revision, checkpointing, and result saving.

## 0. Local Ollama Setup

Before running this notebook, install Ollama and download the model locally.

### Recommended model setup

This notebook uses a single-model multi-agent setup. All three agents use Qwen3.5-27B.

```bash
ollama pull qwen3.5:27b
```

You can check downloaded models with:

```bash
ollama list
```

You can check currently loaded models with:

```bash
ollama ps
```

If the Ollama server is not running, start it with:

```bash
ollama serve
```

On macOS, opening the Ollama app usually starts the local server automatically.

In [1]:
# Cell 1: Install required Python packages.
# Run this only once if the packages are not installed

!pip install requests pandas tqdm

Requirement already satisfied: requests in /Applications/anaconda3/envs/nlp/lib/python3.11/site-packages (2.33.1)
Requirement already satisfied: pandas in /Applications/anaconda3/envs/nlp/lib/python3.11/site-packages (3.0.2)
Requirement already satisfied: tqdm in /Applications/anaconda3/envs/nlp/lib/python3.11/site-packages (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Applications/anaconda3/envs/nlp/lib/python3.11/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Applications/anaconda3/envs/nlp/lib/python3.11/site-packages (from requests) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /Applications/anaconda3/envs/nlp/lib/python3.11/site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /Applications/anaconda3/envs/nlp/lib/python3.11/site-packages (from requests) (2026.4.22)
Requirement already satisfied: numpy>=1.26.0 in /Applications/anaconda3/envs/nlp/lib/python3.11/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Applications/anaconda3/envs/nlp/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Applications/anaconda3/envs/nlp/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [2]:
# current working path check
import os
from pathlib import Path

PROJECT_ROOT = Path("/Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization")
os.chdir(PROJECT_ROOT)

print("Current working directory:", Path.cwd())

Current working directory: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization

In [3]:
# Cell 2: Imports and global configuration

import json
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests
import pandas as pd
from tqdm.auto import tqdm

OLLAMA_HOST = "http://localhost:11434"

# Semantic-agent models
# All agents use the same 27B model for a consistent model-capacity setting.
SEMANTIC_UNDERSTANDING_MODEL = "qwen3.5:27b"
SUMMARY_GENERATION_MODEL = "qwen3.5:27b"
REVISION_MODEL = "qwen3.5:27b"

DEFAULT_TEMPERATURE = 0.2
DEFAULT_NUM_CTX = 4096
REVISION_NUM_CTX = 4096

# Gold set path
GOLD_SET_PATH = Path(
    "/Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/data/gold_set_50_zh_XSAMSum_bart.json"
)

# Output directory
OUTPUT_DIR = Path(
    "/Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results"
)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Output files for semantic-agent pipeline
INTERMEDIATE_OUTPUT_PATH = OUTPUT_DIR / "semantic_qwen27b_all_agents_5samples_intermediate.jsonl"
FULL_OUTPUT_PATH = OUTPUT_DIR / "semantic_qwen27b_all_agents_5samples_final.jsonl"
FINAL_CSV_PATH = OUTPUT_DIR / "semantic_qwen27b_all_agents_5samples.csv"
ERROR_OUTPUT_PATH = OUTPUT_DIR / "semantic_qwen27b_all_agents_5samples_errors.jsonl"

print("Gold set path:", GOLD_SET_PATH)
print("Output directory:", OUTPUT_DIR)
print("Intermediate JSONL output path:", INTERMEDIATE_OUTPUT_PATH)
print("Full JSONL output path:", FULL_OUTPUT_PATH)
print("Final CSV output path:", FINAL_CSV_PATH)
print("Error output path:", ERROR_OUTPUT_PATH)

print("Agent 1 model:", SEMANTIC_UNDERSTANDING_MODEL)
print("Agent 2 model:", SUMMARY_GENERATION_MODEL)
print("Agent 3 model:", REVISION_MODEL)

Gold set path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/data/gold_set_50_zh_XSAMSum_bart.json
Output directory: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results
Intermediate JSONL output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/semantic_qwen27b_all_agents_5samples_intermediate.jsonl
Full JSONL output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/semantic_qwen27b_all_agents_5samples_final.jsonl
Final CSV output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/semantic_qwen27b_all_agents_5samples.csv
Error output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/semantic_qwen27b_all_agents_5samples_errors.jsonl
Agent 1 model: qwen3.5:27b
Agent 2 model: qwen3.5:27b
Agent 3 model: qwen3.5:27b

In [4]:
# Cell 3: Check whether Ollama is running

def check_ollama_server() -> bool:
    try:
        response = requests.get(f"{OLLAMA_HOST}/api/tags", timeout=10)
        response.raise_for_status()
        models = response.json().get("models", [])

        print("Ollama server is running.")
        print(f"Downloaded models: {[m.get('name') for m in models]}")

        return True

    except Exception as e:
        print("Could not connect to Ollama.")
        print("Make sure Ollama is installed and running.")
        print("Try running this in Terminal:")
        print("  ollama serve")
        print()
        print("Error:", repr(e))

        return False


_ = check_ollama_server()

Ollama server is running.
Downloaded models: ['qwen3.5:9b', 'qwen3.5:27b']

In [5]:
# Cell 4: Ollama API helper

def call_ollama(
    model: str,
    prompt: str,
    system: Optional[str] = None,
    temperature: float = DEFAULT_TEMPERATURE,
    num_ctx: int = DEFAULT_NUM_CTX,
    timeout: int = 900,
    keep_alive: Optional[str] = None,
    json_mode: bool = True,
) -> str:
    """Call Ollama's local chat API and return the assistant content."""

    messages = []

    if system:
        messages.append({"role": "system", "content": system})

    messages.append({"role": "user", "content": prompt})

    payload = {
        "model": model,
        "messages": messages,
        "stream": False,
        "options": {
            "temperature": temperature,
            "num_ctx": num_ctx,
            "num_predict": 1024,
        },
        "think": False,
    }

    if json_mode:
        payload["format"] = "json"

    if keep_alive is not None:
        payload["keep_alive"] = keep_alive

    response = requests.post(
        f"{OLLAMA_HOST}/api/chat",
        json=payload,
        timeout=timeout,
    )
    response.raise_for_status()

    data = response.json()
    content = data.get("message", {}).get("content", "")

    if content is None:
        content = ""

    return content.strip()


def load_ollama_model(model: str) -> None:
    """Preload a model into Ollama memory."""
    payload = {
        "model": model,
        "messages": [],
        "stream": False,
    }

    response = requests.post(
        f"{OLLAMA_HOST}/api/chat",
        json=payload,
        timeout=300,
    )
    response.raise_for_status()

    print(f"Loaded model: {model}")


def unload_ollama_model(model: str) -> None:
    """Unload a model from Ollama memory."""
    payload = {
        "model": model,
        "messages": [],
        "keep_alive": 0,
        "stream": False,
    }

    response = requests.post(
        f"{OLLAMA_HOST}/api/chat",
        json=payload,
        timeout=300,
    )
    response.raise_for_status()

    print(f"Unloaded model: {model}")

## 1. Prompt Templates

Each agent is defined as:

```text
Agent = model + role-specific prompt + input/output format
```

In the first version, we use a fixed workflow rather than a fully autonomous agent system.

In [ ]:
# Cell 5: Prompt templates

# Agent 1: Semantic Understanding
SEMANTIC_UNDERSTANDING_PROMPT = """Analyze the English dialogue and extract only the key semantic events needed for the final summary.

Focus on:
- participants
- speaker intent
- actor/action/recipient relations
- final decisions, refusals, commitments, changed plans, or cancellations
- the final outcome of the dialogue

Rules:
- Do not analyze every utterance.
- Ignore greetings, jokes, reactions, and closings unless they affect the outcome.
- Resolve ambiguity from context.
- For imperatives, the actor is usually the listener, not the speaker.
  Example: if A says "Just text him" to B, B is the actor.
- Do not infer visual details from placeholders such as <file_photo>, <file_gif>, or <file>.

Extract 1-6 key events. Use fewer events for simple dialogues.
Write final_outcome as one concise sentence.

Output valid JSON only.

Schema:
{
  "participants": ["speaker names"],
  "semantic_grounding": [
    {
      "event_id": 1,
      "speaker": "speaker name",
      "speech_act": "short label",
      "intended_meaning": "concise interpretation",
      "actor": "person or null",
      "action": "concise action",
      "object": "object or null",
      "recipient": "person or null",
      "evidence": ["short quote"]
    }
  ],
  "final_outcome": "one concise sentence"
}

Input dialogue:
{dialogue}

JSON output:
"""

# Agent 2: Event Selection and Chinese Summary Generation
SUMMARY_GENERATION_PROMPT = """You will receive a structured semantic representation of an English dialogue.

Select the most important events and write a concise Chinese summary.

Rules:
- Select only 1-3 salient events.
- Prioritize the final outcome, changed plans, decisions, refusals, commitments, and important actor/action relations.
- If an earlier plan is later changed, summarize the final updated state.
- Do not invent details from placeholders.
- Use natural Chinese.

Conciseness:
- For simple dialogues, prefer 20-50 Chinese characters.
- For complex dialogues, allow up to 80 Chinese characters.

Output valid JSON only.

Schema:
{
  "selected_events": [
    {
      "event_id": 1,
      "key_event": "short description"
    }
  ],
  "summary_zh": "Chinese summary"
}

Input semantic representation:
{semantic_representation}

JSON output:
"""

# Agent 3: Concise Verification and Revision
REVISION_PROMPT = """Verify the draft Chinese summary against the original English dialogue.

Revise only if necessary.

Check for:
- hallucination
- missing final outcome
- wrong actor/action/recipient
- missing key event
- outdated plan
- unsupported visual detail
- awkward Chinese
- unnecessary verbosity

Rules:
- Trust the original dialogue if it conflicts with selected_events.
- Do not rewrite merely for style.
- If the draft is correct, keep it exactly unchanged.
- Be extremely concise.
- Use short issue tags only.
- revision_reason must be under 12 words.
- Output valid JSON only.

Conciseness:
- For simple dialogues, prefer 20-50 Chinese characters.
- For complex dialogues, allow up to 80 Chinese characters.

Allowed issue tags:
"hallucination", "wrong_actor", "wrong_action", "wrong_recipient",
"missing_final_outcome", "missing_key_event", "outdated_plan",
"too_verbose", "awkward_chinese", "unsupported_visual_detail"

Schema:
{
  "needs_revision": false,
  "issues_identified": [],
  "events_dropped": [],
  "revision_reason": "",
  "summary_zh_final": "Chinese summary"
}

Original English dialogue:
{dialogue}

Draft Chinese summary and selected events:
{summary_points}

JSON output:
"""

In [7]:
# Cell 6: JSONL utility functions

def append_jsonl(record: Dict[str, Any], path: Path) -> None:
    """Append one record to a JSONL file."""
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def load_jsonl(path: Path) -> List[Dict[str, Any]]:
    """Load a JSONL file into a list of dictionaries."""
    if not path.exists():
        return []

    records = []

    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            if line:
                records.append(json.loads(line))

    return records


def load_processed_ids(path: Path) -> set:
    """Return IDs that have already been processed."""
    records = load_jsonl(path)

    return {str(record["id"]) for record in records if "id" in record}

In [8]:
# Cell 7: Agent functions

import re

def fill_prompt(template: str, replacements: Dict[str, str]) -> str:
    """Replace only named placeholders while keeping JSON braces in the prompt unchanged."""
    prompt = template

    for key, value in replacements.items():
        prompt = prompt.replace("{" + key + "}", value)

    return prompt


def extract_json_object(text: str) -> Dict[str, Any]:
    """Extract and parse a JSON object from a model response.

    This function is intentionally robust because small local models may:
    - wrap JSON in markdown fences,
    - add extra text before or after JSON,
    - output Python-style booleans such as True/False.
    """
    raw = text.strip()

    # Remove markdown fences if present.
    if raw.startswith("```"):
        lines = raw.splitlines()
        raw = "\n".join(
            line for line in lines
            if not line.strip().startswith("```")
        ).strip()

    candidates = [raw]

    # Try extracting the substring between the first "{" and the last "}".
    start = raw.find("{")
    end = raw.rfind("}")

    if start != -1 and end != -1 and end > start:
        candidates.append(raw[start:end + 1])

    for candidate in candidates:
        # First try direct JSON parsing.
        try:
            parsed = json.loads(candidate)
            if isinstance(parsed, dict):
                return parsed
        except json.JSONDecodeError:
            pass

        # Repair common Python-style JSON issues.
        repaired = candidate
        repaired = re.sub(r"\bTrue\b", "true", repaired)
        repaired = re.sub(r"\bFalse\b", "false", repaired)
        repaired = re.sub(r"\bNone\b", "null", repaired)

        try:
            parsed = json.loads(repaired)
            if isinstance(parsed, dict):
                return parsed
        except json.JSONDecodeError:
            pass

    # Safe fallback for debugging.
    return {
        "raw_output": text,
        "parse_error": True,
    }


def format_json(data: Any) -> str:
    """Format Python objects as readable JSON text."""
    return json.dumps(
        data,
        ensure_ascii=False,
        indent=2,
    )


def extract_final_chinese_summary(revision_result: Dict[str, Any]) -> str:
    """Extract the final Chinese summary from Agent 3's revision output."""
    summary = revision_result.get("summary_zh_final", "")

    if isinstance(summary, list):
        return " ".join(str(item).strip() for item in summary if str(item).strip())

    if isinstance(summary, str):
        return summary.strip()

    if summary:
        return str(summary).strip()

    # Backward-compatible fallback.
    summary = revision_result.get("summary_zh", "")

    if isinstance(summary, str):
        return summary.strip()

    raw_output = revision_result.get("raw_output", "")

    if isinstance(raw_output, str):
        return raw_output.strip()

    return ""


def semantic_understanding_agent(dialogue: str) -> Dict[str, Any]:
    """Agent 1: Information Extraction Agent.

    Input:
        Original English dialogue

    Output:
        Structured representation of the dialogue
    """
    prompt = fill_prompt(
        SEMANTIC_UNDERSTANDING_PROMPT,
        {
            "dialogue": dialogue,
        },
    )

    response = call_ollama(
        model=SEMANTIC_UNDERSTANDING_MODEL,
        prompt=prompt,
        temperature=0.1,
        num_ctx=DEFAULT_NUM_CTX,
        keep_alive="10m",
        json_mode=True,
    )

    return extract_json_object(response)

def summary_generation_agent(
    semantic_representation: Dict[str, Any],
) -> Dict[str, Any]:
    """Agent 2: Summary Generation Agent.

    Input:
        Structured semantic representation from Agent 1

    Output:
        Selected key events and draft Chinese summary
    """
    prompt = fill_prompt(
        SUMMARY_GENERATION_PROMPT,
        {
            "semantic_representation": format_json(semantic_representation),
        },
    )

    response = call_ollama(
        model=SUMMARY_GENERATION_MODEL,
        prompt=prompt,
        temperature=0.2,
        num_ctx=DEFAULT_NUM_CTX,
        keep_alive="10m",
        json_mode=True,
    )

    return extract_json_object(response)


def revision_agent(
    dialogue: str,
    summary_generation_result: Dict[str, Any],
) -> Dict[str, Any]:
    """Agent 3: Verification and Revision Agent.

    Input:
        Original dialogue, selected events, and draft Chinese summary from Agent 2

    Output:
        Revised final Chinese summary
    """
    prompt = fill_prompt(
        REVISION_PROMPT,
        {
            "dialogue": dialogue,
            "summary_points": format_json(summary_generation_result),
        },
    )

    response = call_ollama(
        model=REVISION_MODEL,
        prompt=prompt,
        temperature=0.1,
        num_ctx=REVISION_NUM_CTX,
        keep_alive="10m",
        json_mode=True,
    )

    return extract_json_object(response)

## 2. Agent Functions

Each function corresponds to one agent in the pipeline.

In [9]:
# Cell 8: Three-agent semantic pipeline

def run_agents_1_2(example: Dict[str, Any], verbose: bool = True) -> Dict[str, Any]:
    """Run Agent 1 and Agent 2 and save intermediate outputs."""

    sample_id = str(example.get("id", "unknown"))
    dialogue = example["dialogue"]

    reference_english_summary = example.get("reference_english_summary", "")
    reference_chinese_summary = example.get("reference_chinese_summary", "")

    # Agent 1: Semantic Understanding Agent
    semantic_representation = semantic_understanding_agent(dialogue)

    if verbose:
        print("\n" + "=" * 80)
        print(f"Sample ID: {sample_id}")
        print("=== Agent 1 Intermediate Output: Semantic Representation ===")
        print(format_json(semantic_representation))
        print("=" * 80 + "\n")

    # Agent 2: Event Selection and Chinese Summary Generation Agent
    summary_generation = summary_generation_agent(
        semantic_representation=semantic_representation,
    )

    if verbose:
        print("=== Agent 2 Intermediate Output: Selected Events + Draft Chinese Summary ===")
        print(format_json(summary_generation))
        print("=" * 80 + "\n")

    return {
        "id": sample_id,
        "test_index": example.get("test_index", ""),
        "dialogue": dialogue,

        # References
        "reference_english_summary": reference_english_summary,
        "reference_chinese_summary": reference_chinese_summary,

        # Models
        "agent1_model": SEMANTIC_UNDERSTANDING_MODEL,
        "agent2_model": SUMMARY_GENERATION_MODEL,

        # Intermediate output from Agent 1
        "agent1_semantic_representation": semantic_representation,
        "agent1_semantic_representation_json": format_json(semantic_representation),

        # Intermediate output from Agent 2
        "agent2_summary_generation": summary_generation,
        "agent2_summary_generation_json": format_json(summary_generation),
    }


def run_agent_3_from_intermediate(
    intermediate_record: Dict[str, Any],
    verbose: bool = True,
) -> Dict[str, Any]:
    """Run Agent 3 using saved Agent 1/2 intermediate outputs."""

    dialogue = intermediate_record["dialogue"]
    summary_generation = intermediate_record["agent2_summary_generation"]

    # Agent 3: Verification and Revision Agent
    revision = revision_agent(
        dialogue=dialogue,
        summary_generation_result=summary_generation,
    )

    final_chinese_summary = extract_final_chinese_summary(
        revision_result=revision,
    )

    if verbose:
        print("=== Agent 3 Output: Verification + Revision ===")
        print(format_json(revision))
        print()
        print("=== Final Chinese Summary ===")
        print(final_chinese_summary)
        print("=" * 80 + "\n")

    return {
        **intermediate_record,

        # Model
        "agent3_model": REVISION_MODEL,

        # Agent 3 output
        "agent3_revision": revision,
        "agent3_revision_json": format_json(revision),

        # Final output
        "agent3_final_chinese_summary": final_chinese_summary,
        "final_summary": final_chinese_summary,

        # Metadata
        "pipeline": "semantic_agent",
        "num_model_calls": 3,
    }


def run_three_agent_pipeline(example: Dict[str, Any], verbose: bool = True) -> Dict[str, Any]:
    """Run the full semantic-agent pipeline for one example."""

    # Since all agents use the same 27B model, load it once.
    load_ollama_model(SEMANTIC_UNDERSTANDING_MODEL)

    # Agent 1 + Agent 2
    intermediate_record = run_agents_1_2(example, verbose=verbose)

    # Agent 3
    final_record = run_agent_3_from_intermediate(
        intermediate_record,
        verbose=verbose,
    )

    return final_record

## 3. Test with Examples

Start with five examples before running the full dataset.  
This is the best way to inspect the intermediate outputs between agents.

In [10]:
# Cell 9: Load first 5 examples from the gold set

def load_examples_from_gold_set(path: Path, n: int = 5) -> List[Dict[str, Any]]:
    """Load the first n examples from the gold-set JSON file."""
    if not path.exists():
        raise FileNotFoundError(f"Gold set not found: {path}")

    with path.open("r", encoding="utf-8") as f:
        raw_data = json.load(f)

    examples = []

    for i, item in enumerate(raw_data[:n]):
        examples.append({
            "id": f"gold_{i+1:05d}",
            "test_index": item.get("test_index", ""),
            "dialogue": item["dialogue"],
            "reference_english_summary": item.get("summary", ""),
            "reference_chinese_summary": item.get("summary_zh", ""),
        })

    return examples


test_data = load_examples_from_gold_set(GOLD_SET_PATH, n=5)

print(f"Loaded {len(test_data)} examples.")
print("First example:")
print(test_data[0])

Loaded 5 examples.
First example:
{'id': 'gold_00001', 'test_index': 59, 'dialogue': "Laura: Where are you?\r\nPaul: Almost there.\r\nLaura: Which is?\r\nPaul: Close to the Mac.\r\nLaura: That's so far away!\r\nPaul: 15 mins\r\nLaura: I am not waiting any more, see you some other time.\r\nPaul: Please, wait!\r\nLaura: I've waited 30 minutes, 15 minutes ago you wrote you were almost here. This is too much.\r\nPaul: I am so sorry.\r\nLaura: I am not. ", 'reference_english_summary': 'Paul is late for a meeting with Laura and she refuses to wait any longer.', 'reference_chinese_summary': '保罗和劳拉见面时迟到了，现在劳拉不想再等了。'}

In [11]:
# Cell 10: Run the semantic-agent pipeline for the first example

result = run_three_agent_pipeline(test_data[0], verbose=True)
result

Loaded model: qwen3.5:27b

================================================================================
Sample ID: gold_00001
=== Agent 1 Intermediate Output: Semantic Representation ===
{
  "participants": [
    "Laura",
    "Paul"
  ],
  "semantic_grounding": [
    {
      "event_id": 1,
      "speaker": "Paul",
      "speech_act": "status update",
      "intended_meaning": "Paul informs Laura of his current location and estimated arrival time.",
      "actor": "Paul",
      "action": "reporting location and ETA",
      "object": "15 minutes away near the Mac",
      "recipient": "Laura",
      "evidence": [
        "Close to the Mac.",
        "15 mins"
      ]
    },
    {
      "event_id": 2,
      "speaker": "Laura",
      "speech_act": "cancellation",
      "intended_meaning": "Laura decides to end the meeting due to excessive waiting time.",
      "actor": "Laura",
      "action": "canceling the meeting",
      "object": "the planned meeting",
      "recipient": "Paul",
      "evidence": [
        "I am not waiting any more, see you some other time."
      ]
    },
    {
      "event_id": 3,
      "speaker": "Paul",
      "speech_act": "plea",
      "intended_meaning": "Paul attempts to persuade Laura to wait for him.",
      "actor": "Laura",
      "action": "waiting",
      "object": "Paul",
      "recipient": "Laura",
      "evidence": [
        "Please, wait!"
      ]
    },
    {
      "event_id": 4,
      "speaker": "Laura",
      "speech_act": "refusal",
      "intended_meaning": "Laura rejects Paul's plea and confirms the cancellation.",
      "actor": "Laura",
      "action": "refusing to wait",
      "object": "Paul's request",
      "recipient": "Paul",
      "evidence": [
        "I've waited 30 minutes... This is too much.",
        "I am not."
      ]
    }
  ],
  "final_outcome": "Laura cancels the meeting and refuses to wait for Paul after he is 30 minutes late."
}
================================================================================

=== Agent 2 Intermediate Output: Selected Events + Draft Chinese Summary ===
{
  "selected_events": [
    {
      "event_id": 2,
      "key_event": "Laura cancels the meeting due to excessive waiting time."
    },
    {
      "event_id": 4,
      "key_event": "Laura refuses Paul's plea to wait and confirms the cancellation."
    }
  ],
  "summary_zh": "保罗告知劳拉自己还有15分钟到达，但劳拉因已等待30分钟而取消会面，并拒绝了保罗要求继续等待的请求。"
}
================================================================================

=== Agent 3 Output: Verification + Revision ===
{
  "needs_revision": false,
  "issues_identified": [],
  "events_dropped": [],
  "revision_reason": "",
  "summary_zh_final": "保罗告知劳拉自己还有15分钟到达，但劳拉因已等待30分钟而取消会面，并拒绝了保罗要求继续等待的请求。"
}

=== Final Chinese Summary ===
保罗告知劳拉自己还有15分钟到达，但劳拉因已等待30分钟而取消会面，并拒绝了保罗要求继续等待的请求。
================================================================================

{'id': 'gold_00001',
 'test_index': 59,
 'dialogue': "Laura: Where are you?\r\nPaul: Almost there.\r\nLaura: Which is?\r\nPaul: Close to the Mac.\r\nLaura: That's so far away!\r\nPaul: 15 mins\r\nLaura: I am not waiting any more, see you some other time.\r\nPaul: Please, wait!\r\nLaura: I've waited 30 minutes, 15 minutes ago you wrote you were almost here. This is too much.\r\nPaul: I am so sorry.\r\nLaura: I am not. ",
 'reference_english_summary': 'Paul is late for a meeting with Laura and she refuses to wait any longer.',
 'reference_chinese_summary': '保罗和劳拉见面时迟到了，现在劳拉不想再等了。',
 'agent1_model': 'qwen3.5:27b',
 'agent2_model': 'qwen3.5:27b',
 'agent1_semantic_representation': {'participants': ['Laura', 'Paul'],
  'semantic_grounding': [{'event_id': 1,
    'speaker': 'Paul',
    'speech_act': 'status update',
    'intended_meaning': 'Paul informs Laura of his current location and estimated arrival time.',
    'actor': 'Paul',
    'action': 'reporting location and ETA',
    'object': '15 minutes away near the Mac',
    'recipient': 'Laura',
    'evidence': ['Close to the Mac.', '15 mins']},
   {'event_id': 2,
    'speaker': 'Laura',
    'speech_act': 'cancellation',
    'intended_meaning': 'Laura decides to end the meeting due to excessive waiting time.',
    'actor': 'Laura',
    'action': 'canceling the meeting',
    'object': 'the planned meeting',
    'recipient': 'Paul',
    'evidence': ['I am not waiting any more, see you some other time.']},
   {'event_id': 3,
    'speaker': 'Paul',
    'speech_act': 'plea',
    'intended_meaning': 'Paul attempts to persuade Laura to wait for him.',
    'actor': 'Laura',
    'action': 'waiting',
    'object': 'Paul',
    'recipient': 'Laura',
    'evidence': ['Please, wait!']},
   {'event_id': 4,
    'speaker': 'Laura',
    'speech_act': 'refusal',
    'intended_meaning': "Laura rejects Paul's plea and confirms the cancellation.",
    'actor': 'Laura',
    'action': 'refusing to wait',
    'object': "Paul's request",
    'recipient': 'Paul',
    'evidence': ["I've waited 30 minutes... This is too much.", 'I am not.']}],
  'final_outcome': 'Laura cancels the meeting and refuses to wait for Paul after he is 30 minutes late.'},
 'agent1_semantic_representation_json': '{\n  "participants": [\n    "Laura",\n    "Paul"\n  ],\n  "semantic_grounding": [\n    {\n      "event_id": 1,\n      "speaker": "Paul",\n      "speech_act": "status update",\n      "intended_meaning": "Paul informs Laura of his current location and estimated arrival time.",\n      "actor": "Paul",\n      "action": "reporting location and ETA",\n      "object": "15 minutes away near the Mac",\n      "recipient": "Laura",\n      "evidence": [\n        "Close to the Mac.",\n        "15 mins"\n      ]\n    },\n    {\n      "event_id": 2,\n      "speaker": "Laura",\n      "speech_act": "cancellation",\n      "intended_meaning": "Laura decides to end the meeting due to excessive waiting time.",\n      "actor": "Laura",\n      "action": "canceling the meeting",\n      "object": "the planned meeting",\n      "recipient": "Paul",\n      "evidence": [\n        "I am not waiting any more, see you some other time."\n      ]\n    },\n    {\n      "event_id": 3,\n      "speaker": "Paul",\n      "speech_act": "plea",\n      "intended_meaning": "Paul attempts to persuade Laura to wait for him.",\n      "actor": "Laura",\n      "action": "waiting",\n      "object": "Paul",\n      "recipient": "Laura",\n      "evidence": [\n        "Please, wait!"\n      ]\n    },\n    {\n      "event_id": 4,\n      "speaker": "Laura",\n      "speech_act": "refusal",\n      "intended_meaning": "Laura rejects Paul\'s plea and confirms the cancellation.",\n      "actor": "Laura",\n      "action": "refusing to wait",\n      "object": "Paul\'s request",\n      "recipient": "Paul",\n      "evidence": [\n        "I\'ve waited 30 minutes... This is too much.",\n        "I am not."\n      ]\n    }\n  ],\n  "final_outcome": "Laura cancels the meeting and refuses to wait for Paul after he is 30 minutes late."\n}',
 'agent2_summary_generation': {'selected_events': [{'event_id': 2,
    'key_event': 'Laura cancels the meeting due to excessive waiting time.'},
   {'event_id': 4,
    'key_event': "Laura refuses Paul's plea to wait and confirms the cancellation."}],
  'summary_zh': '保罗告知劳拉自己还有15分钟到达，但劳拉因已等待30分钟而取消会面，并拒绝了保罗要求继续等待的请求。'},
 'agent2_summary_generation_json': '{\n  "selected_events": [\n    {\n      "event_id": 2,\n      "key_event": "Laura cancels the meeting due to excessive waiting time."\n    },\n    {\n      "event_id": 4,\n      "key_event": "Laura refuses Paul\'s plea to wait and confirms the cancellation."\n    }\n  ],\n  "summary_zh": "保罗告知劳拉自己还有15分钟到达，但劳拉因已等待30分钟而取消会面，并拒绝了保罗要求继续等待的请求。"\n}',
 'agent3_model': 'qwen3.5:27b',
 'agent3_revision': {'needs_revision': False,
  'issues_identified': [],
  'events_dropped': [],
  'revision_reason': '',
  'summary_zh_final': '保罗告知劳拉自己还有15分钟到达，但劳拉因已等待30分钟而取消会面，并拒绝了保罗要求继续等待的请求。'},
 'agent3_revision_json': '{\n  "needs_revision": false,\n  "issues_identified": [],\n  "events_dropped": [],\n  "revision_reason": "",\n  "summary_zh_final": "保罗告知劳拉自己还有15分钟到达，但劳拉因已等待30分钟而取消会面，并拒绝了保罗要求继续等待的请求。"\n}',
 'agent3_final_chinese_summary': '保罗告知劳拉自己还有15分钟到达，但劳拉因已等待30分钟而取消会面，并拒绝了保罗要求继续等待的请求。',
 'final_summary': '保罗告知劳拉自己还有15分钟到达，但劳拉因已等待30分钟而取消会面，并拒绝了保罗要求继续等待的请求。',
 'pipeline': 'semantic_agent',
 'num_model_calls': 3}

In [12]:
# Cell 11: Print semantic-agent pipeline result clearly

def print_semantic_agent_result(result: Dict[str, Any]) -> None:
    print("=== Original Dialogue ===")
    print(result["dialogue"])
    print()

    print("=== Agent 1 Intermediate Output: Semantic Representation ===")
    print(result["agent1_semantic_representation_json"])
    print()

    print("=== Agent 2 Intermediate Output: Selected Events + Draft Chinese Summary ===")
    print(result["agent2_summary_generation_json"])
    print()

    print("=== Agent 3 Output: Verification + Revision ===")
    print(result["agent3_revision_json"])
    print()

    print("=== Final Chinese Summary ===")
    print(result["final_summary"])
    print()

    print("=== Reference English Summary ===")
    print(result["reference_english_summary"])
    print()

    print("=== Reference Chinese Summary ===")
    print(result["reference_chinese_summary"])
    print()

    print("=== Metadata ===")
    print("Pipeline:", result["pipeline"])
    print("Agent 1 model:", result["agent1_model"])
    print("Agent 2 model:", result["agent2_model"])
    print("Agent 3 model:", result["agent3_model"])
    print("Model calls:", result["num_model_calls"])


print_semantic_agent_result(result)

=== Original Dialogue ===
Laura: Where are you?
Paul: Almost there.
Laura: Which is?
Paul: Close to the Mac.
Laura: That's so far away!
Paul: 15 mins
Laura: I am not waiting any more, see you some other time.
Paul: Please, wait!
Laura: I've waited 30 minutes, 15 minutes ago you wrote you were almost here. This is too much.
Paul: I am so sorry.
Laura: I am not.

=== Agent 1 Intermediate Output: Semantic Representation ===
{
  "participants": [
    "Laura",
    "Paul"
  ],
  "semantic_grounding": [
    {
      "event_id": 1,
      "speaker": "Paul",
      "speech_act": "status update",
      "intended_meaning": "Paul informs Laura of his current location and estimated arrival time.",
      "actor": "Paul",
      "action": "reporting location and ETA",
      "object": "15 minutes away near the Mac",
      "recipient": "Laura",
      "evidence": [
        "Close to the Mac.",
        "15 mins"
      ]
    },
    {
      "event_id": 2,
      "speaker": "Laura",
      "speech_act": "cancellation",
      "intended_meaning": "Laura decides to end the meeting due to excessive waiting time.",
      "actor": "Laura",
      "action": "canceling the meeting",
      "object": "the planned meeting",
      "recipient": "Paul",
      "evidence": [
        "I am not waiting any more, see you some other time."
      ]
    },
    {
      "event_id": 3,
      "speaker": "Paul",
      "speech_act": "plea",
      "intended_meaning": "Paul attempts to persuade Laura to wait for him.",
      "actor": "Laura",
      "action": "waiting",
      "object": "Paul",
      "recipient": "Laura",
      "evidence": [
        "Please, wait!"
      ]
    },
    {
      "event_id": 4,
      "speaker": "Laura",
      "speech_act": "refusal",
      "intended_meaning": "Laura rejects Paul's plea and confirms the cancellation.",
      "actor": "Laura",
      "action": "refusing to wait",
      "object": "Paul's request",
      "recipient": "Paul",
      "evidence": [
        "I've waited 30 minutes... This is too much.",
        "I am not."
      ]
    }
  ],
  "final_outcome": "Laura cancels the meeting and refuses to wait for Paul after he is 30 minutes late."
}

=== Agent 2 Intermediate Output: Selected Events + Draft Chinese Summary ===
{
  "selected_events": [
    {
      "event_id": 2,
      "key_event": "Laura cancels the meeting due to excessive waiting time."
    },
    {
      "event_id": 4,
      "key_event": "Laura refuses Paul's plea to wait and confirms the cancellation."
    }
  ],
  "summary_zh": "保罗告知劳拉自己还有15分钟到达，但劳拉因已等待30分钟而取消会面，并拒绝了保罗要求继续等待的请求。"
}

=== Agent 3 Output: Verification + Revision ===
{
  "needs_revision": false,
  "issues_identified": [],
  "events_dropped": [],
  "revision_reason": "",
  "summary_zh_final": "保罗告知劳拉自己还有15分钟到达，但劳拉因已等待30分钟而取消会面，并拒绝了保罗要求继续等待的请求。"
}

=== Final Chinese Summary ===
保罗告知劳拉自己还有15分钟到达，但劳拉因已等待30分钟而取消会面，并拒绝了保罗要求继续等待的请求。

=== Reference English Summary ===
Paul is late for a meeting with Laura and she refuses to wait any longer.

=== Reference Chinese Summary ===
保罗和劳拉见面时迟到了，现在劳拉不想再等了。

=== Metadata ===
Pipeline: semantic_agent
Agent 1 model: qwen3.5:27b
Agent 2 model: qwen3.5:27b
Agent 3 model: qwen3.5:27b
Model calls: 3

## 4. Save Results

This saves all intermediate outputs and the final output.

In [13]:
# Cell 12: Reset previous outputs before batch inference

INTERMEDIATE_OUTPUT_PATH.unlink(missing_ok=True)
FULL_OUTPUT_PATH.unlink(missing_ok=True)
FINAL_CSV_PATH.unlink(missing_ok=True)
ERROR_OUTPUT_PATH.unlink(missing_ok=True)

print("Previous output files reset.")
print("Intermediate output path:", INTERMEDIATE_OUTPUT_PATH)
print("Final JSONL output path:", FULL_OUTPUT_PATH)
print("CSV output path:", FINAL_CSV_PATH)
print("Error output path:", ERROR_OUTPUT_PATH)

Previous output files reset.
Intermediate output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/semantic_qwen27b_all_agents_5samples_intermediate.jsonl
Final JSONL output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/semantic_qwen27b_all_agents_5samples_final.jsonl
CSV output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/semantic_qwen27b_all_agents_5samples.csv
Error output path: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/semantic_qwen27b_all_agents_5samples_errors.jsonl

## 5. Batch Inference with Checkpointing

This cell processes examples one by one and appends each completed result to `results/agentic_outputs.jsonl`.

If the notebook stops, already processed examples remain saved.

In [ ]:
# Cell 13: Two-stage batch inference with semantic-agent pipeline
# Time stamp: 9m 9.6s

from datetime import datetime

MAX_EXAMPLES = 5
SLEEP_SECONDS = 0.2

subset = test_data[:MAX_EXAMPLES]

print("Batch inference started at:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("Semantic-agent pipeline with all 27B agents")
print("Agent 1 model:", SEMANTIC_UNDERSTANDING_MODEL)
print("Agent 2 model:", SUMMARY_GENERATION_MODEL)
print("Agent 3 model:", REVISION_MODEL)

# Load the shared 27B model once
load_ollama_model(SEMANTIC_UNDERSTANDING_MODEL)

# -------------------------
# Stage 1: Agent 1 + Agent 2
# -------------------------

processed_intermediate_ids = load_processed_ids(INTERMEDIATE_OUTPUT_PATH)
print(f"Already processed by Agent 1/2: {len(processed_intermediate_ids)} examples")

for ex in tqdm(
    subset,
    desc=f"Stage 1: Agent 1/2 with {SEMANTIC_UNDERSTANDING_MODEL}",
):
    sample_id = str(ex.get("id", "unknown"))

    if sample_id in processed_intermediate_ids:
        print(f"Skipping Agent 1/2 already processed sample: {sample_id}")
        continue

    try:
        intermediate_record = run_agents_1_2(ex, verbose=True)

        append_jsonl(intermediate_record, INTERMEDIATE_OUTPUT_PATH)
        processed_intermediate_ids.add(sample_id)

        time.sleep(SLEEP_SECONDS)

    except Exception as e:
        error_record = {
            "stage": "agent_1_2",
            "id": sample_id,
            "test_index": ex.get("test_index", ""),
            "error": repr(e),
            "dialogue": ex.get("dialogue", ""),
        }

        append_jsonl(error_record, ERROR_OUTPUT_PATH)
        print(f"Error in Agent 1/2 on {sample_id}: {repr(e)}")


# -------------------------
# Stage 2: Agent 3
# -------------------------

intermediate_records = load_jsonl(INTERMEDIATE_OUTPUT_PATH)

processed_final_ids = load_processed_ids(FULL_OUTPUT_PATH)
print(f"Already processed by Agent 3: {len(processed_final_ids)} examples")

for intermediate_record in tqdm(
    intermediate_records,
    desc=f"Stage 2: Agent 3 with {REVISION_MODEL}",
):
    sample_id = str(intermediate_record.get("id", "unknown"))

    if sample_id in processed_final_ids:
        print(f"Skipping Agent 3 already processed sample: {sample_id}")
        continue

    try:
        final_record = run_agent_3_from_intermediate(
            intermediate_record,
            verbose=True,
        )

        append_jsonl(final_record, FULL_OUTPUT_PATH)
        processed_final_ids.add(sample_id)

        time.sleep(SLEEP_SECONDS)

    except Exception as e:
        error_record = {
            "stage": "agent_3",
            "id": sample_id,
            "test_index": intermediate_record.get("test_index", ""),
            "error": repr(e),
            "dialogue": intermediate_record.get("dialogue", ""),
        }

        append_jsonl(error_record, ERROR_OUTPUT_PATH)
        print(f"Error in Agent 3 on {sample_id}: {repr(e)}")

print("Batch inference finished at:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print(f"Finished. Intermediate outputs saved to: {INTERMEDIATE_OUTPUT_PATH}")
print(f"Finished. Final outputs saved to: {FULL_OUTPUT_PATH}")

Batch inference started at: 2026-05-08 02:47:57
Semantic-agent pipeline with all 27B agents
Agent 1 model: qwen3.5:27b
Agent 2 model: qwen3.5:27b
Agent 3 model: qwen3.5:27b
Loaded model: qwen3.5:27b
Already processed by Agent 1/2: 0 examples

Stage 1: Agent 1/2 with qwen3.5:27b:   0%|          | 0/5 [00:00<?, ?it/s]

================================================================================
Sample ID: gold_00001
=== Agent 1 Intermediate Output: Semantic Representation ===
{
  "participants": [
    "Laura",
    "Paul"
  ],
  "semantic_grounding": [
    {
      "event_id": 1,
      "speaker": "Paul",
      "speech_act": "status update",
      "intended_meaning": "Paul informs Laura of his current location and estimated arrival time.",
      "actor": "Paul",
      "action": "reporting location and ETA",
      "object": "15 minutes away near the Mac",
      "recipient": "Laura",
      "evidence": [
        "Close to the Mac.",
        "15 mins"
      ]
    },
    {
      "event_id": 2,
      "speaker": "Laura",
      "speech_act": "cancellation",
      "intended_meaning": "Laura decides to end the meeting due to excessive waiting time.",
      "actor": "Laura",
      "action": "canceling the meeting",
      "object": "the planned meeting",
      "recipient": "Paul",
      "evidence": [
        "I am not waiting any more, see you some other time."
      ]
    },
    {
      "event_id": 3,
      "speaker": "Paul",
      "speech_act": "plea",
      "intended_meaning": "Paul attempts to persuade Laura to wait for him.",
      "actor": "Laura",
      "action": "waiting",
      "object": "Paul",
      "recipient": "Laura",
      "evidence": [
        "Please, wait!"
      ]
    },
    {
      "event_id": 4,
      "speaker": "Laura",
      "speech_act": "refusal",
      "intended_meaning": "Laura rejects Paul's plea and confirms the cancellation.",
      "actor": "Laura",
      "action": "refusing to wait",
      "object": "Paul's request",
      "recipient": "Paul",
      "evidence": [
        "I've waited 30 minutes... This is too much.",
        "I am not."
      ]
    }
  ],
  "final_outcome": "Laura cancels the meeting and leaves because Paul is 15 minutes late after she had already waited 30 minutes."
}
================================================================================

=== Agent 2 Intermediate Output: Selected Events + Draft Chinese Summary ===
{
  "selected_events": [
    {
      "event_id": 2,
      "key_event": "Laura cancels the meeting due to excessive waiting time."
    },
    {
      "event_id": 4,
      "key_event": "Laura refuses Paul's plea to wait and confirms the cancellation."
    }
  ],
  "summary_zh": "Laura 因已等待 30 分钟且 Paul 仍迟到 15 分钟，决定取消会面并拒绝 Paul 的等待请求，最终离开。"
}
================================================================================


================================================================================
Sample ID: gold_00002
=== Agent 1 Intermediate Output: Semantic Representation ===
{
  "participants": [
    "Finn",
    "Zadie"
  ],
  "semantic_grounding": [
    {
      "event_id": 1,
      "speaker": "Finn",
      "speech_act": "invitation",
      "intended_meaning": "Finn invites Zadie to visit Elephant and Castle tomorrow to see the Latin American community before it is demolished.",
      "actor": "Finn",
      "action": "invite",
      "object": "trip to Elephant and Castle",
      "recipient": "Zadie",
      "evidence": [
        "Fancy joining?"
      ]
    },
    {
      "event_id": 2,
      "speaker": "Zadie",
      "speech_act": "acceptance",
      "intended_meaning": "Zadie accepts the invitation and expresses interest in the food.",
      "actor": "Zadie",
      "action": "accept",
      "object": "invitation",
      "recipient": "Finn",
      "evidence": [
        "Sure!",
        "I'm totally up for it"
      ]
    },
    {
      "event_id": 3,
      "speaker": "Zadie",
      "speech_act": "proposal",
      "intended_meaning": "Zadie proposes meeting in the early evening around 2 o'clock.",
      "actor": "Zadie",
      "action": "propose time",
      "object": "2 o'clock",
      "recipient": "Finn",
      "evidence": [
        "I'd say early evening, 2-ish?"
      ]
    },
    {
      "event_id": 4,
      "speaker": "Finn",
      "speech_act": "agreement",
      "intended_meaning": "Finn agrees to the proposed time and suggests meeting at the main entrance of the shopping centre.",
      "actor": "Finn",
      "action": "confirm time and location",
      "object": "2 o'clock at main entrance",
      "recipient": "Zadie",
      "evidence": [
        "Yeah, that's fine by me.",
        "Shall I see you at the main entrance"
      ]
    },
    {
      "event_id": 5,
      "speaker": "Zadie",
      "speech_act": "confirmation",
      "intended_meaning": "Zadie confirms the final plan to meet at 2 o'clock at the main entrance.",
      "actor": "Zadie",
      "action": "confirm plan",
      "object": "meeting details",
      "recipient": "Finn",
      "evidence": [
        "2 o'clock at unspecified main entrance then? Sounds good to mw"
      ]
    }
  ],
  "final_outcome": "Finn and Zadie agreed to meet tomorrow at 2:00 PM at the main entrance of the Elephant and Castle shopping centre to explore the area."
}
================================================================================

=== Agent 2 Intermediate Output: Selected Events + Draft Chinese Summary ===
{
  "selected_events": [
    {
      "event_id": 2,
      "key_event": "Zadie accepts Finn's invitation to visit Elephant and Castle."
    },
    {
      "event_id": 4,
      "key_event": "Finn agrees to meet at 2:00 PM at the main entrance."
    },
    {
      "event_id": 5,
      "key_event": "Zadie confirms the final meeting plan."
    }
  ],
  "summary_zh": "Finn 邀请 Zadie 明天去 Elephant and Castle 参观，Zadie 欣然接受。两人最终商定于下午 2 点在购物中心主入口见面。"
}
================================================================================


================================================================================
Sample ID: gold_00003
=== Agent 1 Intermediate Output: Semantic Representation ===
{
  "participants": [
    "Josh",
    "Brian"
  ],
  "semantic_grounding": [
    {
      "event_id": 1,
      "speaker": "Josh",
      "speech_act": "inquiry",
      "intended_meaning": "Josh asks for advice on buying an iPad and specifically questions the value of Apple.",
      "actor": "Josh",
      "action": "asks for recommendation",
      "object": "iPad brand",
      "recipient": "Brian",
      "evidence": [
        "do u think apple it's a good choice?"
      ]
    },
    {
      "event_id": 2,
      "speaker": "Brian",
      "speech_act": "recommendation",
      "intended_meaning": "Brian advises against Apple and suggests Samsung, Xiaomi, or Sony based on budget.",
      "actor": "Brian",
      "action": "recommends brands",
      "object": "Samsung, Xiaomi, Sony",
      "recipient": "Josh",
      "evidence": [
        "Samsung, Xiaomi, Sony",
        "depends on yr budget.."
      ]
    },
    {
      "event_id": 3,
      "speaker": "Josh",
      "speech_act": "statement",
      "intended_meaning": "Josh specifies his budget limit for the purchase.",
      "actor": "Josh",
      "action": "states budget",
      "object": "2000",
      "recipient": "Brian",
      "evidence": [
        "let's say 2000.."
      ]
    },
    {
      "event_id": 4,
      "speaker": "Brian",
      "speech_act": "offer",
      "intended_meaning": "Brian offers to procure a Samsung device for Josh at a lower price.",
      "actor": "Brian",
      "action": "offers to buy cheaper",
      "object": "Samsung",
      "recipient": "Josh",
      "evidence": [
        "actually, if u want samsung I can get it cheaper for u"
      ]
    },
    {
      "event_id": 5,
      "speaker": "Brian",
      "speech_act": "request",
      "intended_meaning": "Brian instructs Josh to contact him after work to finalize the deal.",
      "actor": "Josh",
      "action": "call",
      "object": "Brian",
      "recipient": "Brian",
      "evidence": [
        "call me after work, ok?"
      ]
    },
    {
      "event_id": 6,
      "speaker": "Josh",
      "speech_act": "commitment",
      "intended_meaning": "Josh agrees to call Brian after work.",
      "actor": "Josh",
      "action": "agrees to call",
      "object": null,
      "recipient": "Brian",
      "evidence": [
        "ok"
      ]
    }
  ],
  "final_outcome": "Josh agreed to call Brian after work to purchase a Samsung device at a discounted price."
}
================================================================================

=== Agent 2 Intermediate Output: Selected Events + Draft Chinese Summary ===
{
  "selected_events": [
    {
      "event_id": 4,
      "key_event": "Brian offers to buy a Samsung device for Josh at a lower price."
    },
    {
      "event_id": 5,
      "key_event": "Brian asks Josh to call after work to finalize the deal."
    },
    {
      "event_id": 6,
      "key_event": "Josh agrees to call Brian after work."
    }
  ],
  "summary_zh": "Josh 询问购买 iPad 的建议，Brian 推荐三星并提议以更低价格代购。Josh 确认预算后，两人约定下班后通电话以完成交易。"
}
================================================================================


================================================================================
Sample ID: gold_00004
=== Agent 1 Intermediate Output: Semantic Representation ===
{
  "participants": [
    "Frank",
    "Andy"
  ],
  "semantic_grounding": [
    {
      "event_id": 1,
      "speaker": "Frank",
      "speech_act": "admonition",
      "intended_meaning": "Frank urges Andy to study for his upcoming quiz instead of watching TV.",
      "actor": "Andy",
      "action": "study",
      "object": "quiz",
      "recipient": null,
      "evidence": [
        "so go study for it"
      ]
    },
    {
      "event_id": 2,
      "speaker": "Andy",
      "speech_act": "refusal",
      "intended_meaning": "Andy declines to study now, planning to do it tomorrow instead.",
      "actor": "Andy",
      "action": "study",
      "object": "quiz",
      "recipient": null,
      "evidence": [
        "i'll study for it tomorrow"
      ]
    },
    {
      "event_id": 3,
      "speaker": "Frank",
      "speech_act": "skepticism",
      "intended_meaning": "Frank doubts Andy's ability to wake up on time to study tomorrow.",
      "actor": "Andy",
      "action": "wake up on time",
      "object": null,
      "recipient": null,
      "evidence": [
        "yea like ur gonna wake up on time for that"
      ]
    },
    {
      "event_id": 4,
      "speaker": "Andy",
      "speech_act": "rejection",
      "intended_meaning": "Andy rejects Frank's authority and ends the argument.",
      "actor": "Andy",
      "action": "reject advice",
      "object": null,
      "recipient": "Frank",
      "evidence": [
        "dude your not my dad"
      ]
    }
  ],
  "final_outcome": "Andy refuses Frank's advice to study immediately and insists on studying tomorrow, dismissing Frank's concerns."
}
================================================================================

=== Agent 2 Intermediate Output: Selected Events + Draft Chinese Summary ===
{
  "selected_events": [
    {
      "event_id": 1,
      "key_event": "Frank urges Andy to study for the quiz immediately."
    },
    {
      "event_id": 2,
      "key_event": "Andy refuses and plans to study tomorrow instead."
    },
    {
      "event_id": 4,
      "key_event": "Andy rejects Frank's authority and ends the argument."
    }
  ],
  "summary_zh": "Frank 敦促 Andy 立即为测验复习，但 Andy 拒绝并计划明天再学。面对 Frank 对其能否按时起床的质疑，Andy 反驳称 Frank 并非其父亲，并结束了争论。"
}
================================================================================


================================================================================
Sample ID: gold_00005
=== Agent 1 Intermediate Output: Semantic Representation ===
{
  "participants": [
    "Crystal",
    "Irene"
  ],
  "semantic_grounding": [
    {
      "event_id": 1,
      "speaker": "Crystal",
      "speech_act": "statement",
      "intended_meaning": "Crystal explains that her son has outgrown his clothes.",
      "actor": "Crystal",
      "action": "states",
      "object": "son's clothes no longer fit",
      "recipient": null,
      "evidence": [
        "he got so big he doesn't fit his clothes anymore"
      ]
    },
    {
      "event_id": 2,
      "speaker": "Irene",
      "speech_act": "offer",
      "intended_meaning": "Irene offers to take the boy shopping and buy him something.",
      "actor": "Irene",
      "action": "offers to take and buy",
      "object": "shopping trip",
      "recipient": "Crystal's son",
      "evidence": [
        "Let me take him, I also promise to buy him something"
      ]
    },
    {
      "event_id": 3,
      "speaker": "Crystal",
      "speech_act": "hesitation",
      "intended_meaning": "Crystal expresses reluctance because shopping is a burden.",
      "actor": "Crystal",
      "action": "expresses reluctance",
      "object": "shopping",
      "recipient": null,
      "evidence": [
        "well yeah it's just such a drag"
      ]
    },
    {
      "event_id": 4,
      "speaker": "Irene",
      "speech_act": "persuasion",
      "intended_meaning": "Irene insists on taking the boy, calling Crystal a bore at shopping.",
      "actor": "Irene",
      "action": "insists",
      "object": "taking the boy",
      "recipient": "Crystal",
      "evidence": [
        "you were always a bore when shopping :P just let me take the little man"
      ]
    },
    {
      "event_id": 5,
      "speaker": "Crystal",
      "speech_act": "acceptance",
      "intended_meaning": "Crystal agrees to let Irene take the boy.",
      "actor": "Crystal",
      "action": "agrees",
      "object": "Irene's offer",
      "recipient": "Irene",
      "evidence": [
        "ok"
      ]
    }
  ],
  "final_outcome": "Crystal agrees to let Irene take her son shopping and buy him new clothes."
}
================================================================================

=== Agent 2 Intermediate Output: Selected Events + Draft Chinese Summary ===
{
  "selected_events": [
    {
      "event_id": 2,
      "key_event": "Irene offers to take Crystal's son shopping and buy him clothes."
    },
    {
      "event_id": 5,
      "key_event": "Crystal agrees to let Irene take her son shopping."
    }
  ],
  "summary_zh": "Crystal 表示儿子衣服穿不下了，Irene 主动提出带他去买新衣服，尽管 Crystal 起初觉得购物麻烦，但最终同意了 Irene 的提议。"
}
================================================================================

Already processed by Agent 3: 0 examples

Stage 2: Agent 3 with qwen3.5:27b:   0%|          | 0/5 [00:00<?, ?it/s]

=== Agent 3 Output: Verification + Revision ===
{
  "needs_revision": false,
  "issues_identified": [],
  "events_dropped": [],
  "revision_reason": "",
  "summary_zh_final": "Laura 因已等待 30 分钟且 Paul 仍迟到 15 分钟，决定取消会面并拒绝 Paul 的等待请求，最终离开。"
}

=== Final Chinese Summary ===
Laura 因已等待 30 分钟且 Paul 仍迟到 15 分钟，决定取消会面并拒绝 Paul 的等待请求，最终离开。
================================================================================

=== Agent 3 Output: Verification + Revision ===
{
  "needs_revision": false,
  "issues_identified": [],
  "events_dropped": [],
  "revision_reason": "",
  "summary_zh_final": "Finn 邀请 Zadie 明天去 Elephant and Castle 参观，Zadie 欣然接受。两人最终商定于下午 2 点在购物中心主入口见面。"
}

=== Final Chinese Summary ===
Finn 邀请 Zadie 明天去 Elephant and Castle 参观，Zadie 欣然接受。两人最终商定于下午 2 点在购物中心主入口见面。
================================================================================

=== Agent 3 Output: Verification + Revision ===
{
  "needs_revision": false,
  "issues_identified": [],
  "events_dropped": [],
  "revision_reason": "",
  "summary_zh_final": "Josh 询问购买 iPad 的建议，Brian 推荐三星并提议以更低价格代购。Josh 确认预算后，两人约定下班后通电话以完成交易。"
}

=== Final Chinese Summary ===
Josh 询问购买 iPad 的建议，Brian 推荐三星并提议以更低价格代购。Josh 确认预算后，两人约定下班后通电话以完成交易。
================================================================================

=== Agent 3 Output: Verification + Revision ===
{
  "needs_revision": false,
  "issues_identified": [],
  "events_dropped": [],
  "revision_reason": "",
  "summary_zh_final": "Frank 敦促 Andy 立即为测验复习，但 Andy 拒绝并计划明天再学。面对 Frank 对其能否按时起床的质疑，Andy 反驳称 Frank 并非其父亲，并结束了争论。"
}

=== Final Chinese Summary ===
Frank 敦促 Andy 立即为测验复习，但 Andy 拒绝并计划明天再学。面对 Frank 对其能否按时起床的质疑，Andy 反驳称 Frank 并非其父亲，并结束了争论。
================================================================================

=== Agent 3 Output: Verification + Revision ===
{
  "needs_revision": false,
  "issues_identified": [],
  "events_dropped": [],
  "revision_reason": "",
  "summary_zh_final": "Crystal 表示儿子衣服穿不下了，Irene 主动提出带他去买新衣服，尽管 Crystal 起初觉得购物麻烦，但最终同意了 Irene 的提议。"
}

=== Final Chinese Summary ===
Crystal 表示儿子衣服穿不下了，Irene 主动提出带他去买新衣服，尽管 Crystal 起初觉得购物麻烦，但最终同意了 Irene 的提议。
================================================================================

Batch inference finished at: 2026-05-08 02:57:07
Finished. Intermediate outputs saved to: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/semantic_qwen27b_all_agents_5samples_intermediate.jsonl
Finished. Final outputs saved to: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/semantic_qwen27b_all_agents_5samples_final.jsonl

## 6. Export Final Summaries to CSV

This file can be used for ROUGE, BERTScore, OmniScore, or manual analysis.

In [16]:
# Cell 14: Export semantic-agent summaries to CSV

records = load_jsonl(FULL_OUTPUT_PATH)

rows = []

for record in records:
    if "final_summary" not in record:
        continue

    rows.append({
        "id": record.get("id", ""),
        "test_index": record.get("test_index", ""),
        "dialogue": record.get("dialogue", ""),

        # Final output
        "final_summary": record.get("final_summary", ""),

        # References
        "reference_english_summary": record.get("reference_english_summary", ""),
        "reference_chinese_summary": record.get("reference_chinese_summary", ""),

        # Intermediate outputs
        "agent1_semantic_representation_json": record.get(
            "agent1_semantic_representation_json", ""
        ),
        "agent2_summary_generation_json": record.get(
            "agent2_summary_generation_json", ""
        ),
        "agent3_revision_json": record.get(
            "agent3_revision_json", ""
        ),

        # Agent 3 final
        "agent3_final_chinese_summary": record.get(
            "agent3_final_chinese_summary", ""
        ),

        # Metadata
        "pipeline": record.get("pipeline", "semantic_agent"),
        "agent1_model": record.get("agent1_model", ""),
        "agent2_model": record.get("agent2_model", ""),
        "agent3_model": record.get("agent3_model", ""),
        "num_model_calls": record.get("num_model_calls", 3),
    })

df = pd.DataFrame(rows)

if not df.empty:
    df = df.drop_duplicates(subset=["id"], keep="last")

df.to_csv(FINAL_CSV_PATH, index=False, encoding="utf-8-sig")

print(f"Saved final summaries to: {FINAL_CSV_PATH}")
df

Saved final summaries to: /Users/yunu919/Desktop/CLMS/LING573/573ChineseEnglishSummarization/notebooks/agents/results/semantic_qwen27b_all_agents_5samples.csv

,id,test_index,dialogue,final_summary,reference_english_summary,reference_chinese_summary,agent1_semantic_representation_json,agent2_summary_generation_json,agent3_revision_json,agent3_final_chinese_summary,pipeline,agent1_model,agent2_model,agent3_model,num_model_calls
0,gold_00001,59,Laura: Where are you?\r\nPaul: Almost there.\r...,Laura 因已等待 30 分钟且 Paul 仍迟到 15 分钟，决定取消会面并拒绝 Pau...,Paul is late for a meeting with Laura and she ...,保罗和劳拉见面时迟到了，现在劳拉不想再等了。,"{\n ""participants"": [\n ""Laura"",\n ""Pau...","{\n ""selected_events"": [\n {\n ""event...","{\n ""needs_revision"": false,\n ""issues_ident...",Laura 因已等待 30 分钟且 Paul 仍迟到 15 分钟，决定取消会面并拒绝 Pau...,semantic_agent,qwen3.5:27b,qwen3.5:27b,qwen3.5:27b,3
1,gold_00002,81,Finn: Hey\r\nZadie: Hi there! What's up?\r\nFi...,Finn 邀请 Zadie 明天去 Elephant and Castle 参观，Zadie...,Finn and Zadie are going to Elephant and Castl...,费恩和查蒂明天2点去象堡，他们会在正门碰头。,"{\n ""participants"": [\n ""Finn"",\n ""Zadi...","{\n ""selected_events"": [\n {\n ""event...","{\n ""needs_revision"": false,\n ""issues_ident...",Finn 邀请 Zadie 明天去 Elephant and Castle 参观，Zadie...,semantic_agent,qwen3.5:27b,qwen3.5:27b,qwen3.5:27b,3
2,gold_00003,85,Josh: I need to buy an iPad?\r\nJosh: do u thi...,Josh 询问购买 iPad 的建议，Brian 推荐三星并提议以更低价格代购。Josh 确...,Josh wants to buy a tablet and doesn't know wh...,乔什想买个平板，但不知道该选哪个牌子。按照布莱恩的说法，其他品牌比苹果更好，他能弄来更便宜的...,"{\n ""participants"": [\n ""Josh"",\n ""Bria...","{\n ""selected_events"": [\n {\n ""event...","{\n ""needs_revision"": false,\n ""issues_ident...",Josh 询问购买 iPad 的建议，Brian 推荐三星并提议以更低价格代购。Josh 确...,semantic_agent,qwen3.5:27b,qwen3.5:27b,qwen3.5:27b,3
3,gold_00004,87,Frank: wat are u doing??\r\nAndy: watching Arr...,Frank 敦促 Andy 立即为测验复习，但 Andy 拒绝并计划明天再学。面对 Fran...,Frank tries to encourage Andy to learn for the...,弗兰克试图激励安迪，为明天的测验学习。,"{\n ""participants"": [\n ""Frank"",\n ""And...","{\n ""selected_events"": [\n {\n ""event...","{\n ""needs_revision"": false,\n ""issues_ident...",Frank 敦促 Andy 立即为测验复习，但 Andy 拒绝并计划明天再学。面对 Fran...,semantic_agent,qwen3.5:27b,qwen3.5:27b,qwen3.5:27b,3
4,gold_00005,123,Crystal: <file_photo>\r\nIrene: He's so big!\r...,Crystal 表示儿子衣服穿不下了，Irene 主动提出带他去买新衣服，尽管 Crysta...,Irene will take Crystal's son shopping for clo...,艾琳会带克里斯特尔的儿子去买衣服。,"{\n ""participants"": [\n ""Crystal"",\n ""I...","{\n ""selected_events"": [\n {\n ""event...","{\n ""needs_revision"": false,\n ""issues_ident...",Crystal 表示儿子衣服穿不下了，Irene 主动提出带他去买新衣服，尽管 Crysta...,semantic_agent,qwen3.5:27b,qwen3.5:27b,qwen3.5:27b,3

In [17]:
# Cell 15: Compare semantic-agent outputs with references

comparison_columns = [
    "id",
    "test_index",
    "final_summary",
    "reference_chinese_summary",
]

comparison_df = df[comparison_columns].copy()

comparison_df

,id,test_index,final_summary,reference_chinese_summary
0,gold_00001,59,Laura 因已等待 30 分钟且 Paul 仍迟到 15 分钟，决定取消会面并拒绝 Pau...,保罗和劳拉见面时迟到了，现在劳拉不想再等了。
1,gold_00002,81,Finn 邀请 Zadie 明天去 Elephant and Castle 参观，Zadie...,费恩和查蒂明天2点去象堡，他们会在正门碰头。
2,gold_00003,85,Josh 询问购买 iPad 的建议，Brian 推荐三星并提议以更低价格代购。Josh 确...,乔什想买个平板，但不知道该选哪个牌子。按照布莱恩的说法，其他品牌比苹果更好，他能弄来更便宜的...
3,gold_00004,87,Frank 敦促 Andy 立即为测验复习，但 Andy 拒绝并计划明天再学。面对 Fran...,弗兰克试图激励安迪，为明天的测验学习。
4,gold_00005,123,Crystal 表示儿子衣服穿不下了，Irene 主动提出带他去买新衣服，尽管 Crysta...,艾琳会带克里斯特尔的儿子去买衣服。

In [18]:
# Cell 16: Inspect semantic-agent intermediate outputs and final output

if not df.empty:
    inspection_columns = [
        "id",
        "test_index",
        "dialogue",
        "agent1_semantic_representation_json",
        "agent2_summary_generation_json",
        "agent3_revision_json",
        "final_summary",
        "reference_english_summary",
        "reference_chinese_summary",
    ]

    inspection_df = df[inspection_columns].copy()
    display(inspection_df)
else:
    print("No results found.")

,id,test_index,dialogue,agent1_semantic_representation_json,agent2_summary_generation_json,agent3_revision_json,final_summary,reference_english_summary,reference_chinese_summary
0,gold_00001,59,Laura: Where are you?\r\nPaul: Almost there.\r...,"{\n ""participants"": [\n ""Laura"",\n ""Pau...","{\n ""selected_events"": [\n {\n ""event...","{\n ""needs_revision"": false,\n ""issues_ident...",Laura 因已等待 30 分钟且 Paul 仍迟到 15 分钟，决定取消会面并拒绝 Pau...,Paul is late for a meeting with Laura and she ...,保罗和劳拉见面时迟到了，现在劳拉不想再等了。
1,gold_00002,81,Finn: Hey\r\nZadie: Hi there! What's up?\r\nFi...,"{\n ""participants"": [\n ""Finn"",\n ""Zadi...","{\n ""selected_events"": [\n {\n ""event...","{\n ""needs_revision"": false,\n ""issues_ident...",Finn 邀请 Zadie 明天去 Elephant and Castle 参观，Zadie...,Finn and Zadie are going to Elephant and Castl...,费恩和查蒂明天2点去象堡，他们会在正门碰头。
2,gold_00003,85,Josh: I need to buy an iPad?\r\nJosh: do u thi...,"{\n ""participants"": [\n ""Josh"",\n ""Bria...","{\n ""selected_events"": [\n {\n ""event...","{\n ""needs_revision"": false,\n ""issues_ident...",Josh 询问购买 iPad 的建议，Brian 推荐三星并提议以更低价格代购。Josh 确...,Josh wants to buy a tablet and doesn't know wh...,乔什想买个平板，但不知道该选哪个牌子。按照布莱恩的说法，其他品牌比苹果更好，他能弄来更便宜的...
3,gold_00004,87,Frank: wat are u doing??\r\nAndy: watching Arr...,"{\n ""participants"": [\n ""Frank"",\n ""And...","{\n ""selected_events"": [\n {\n ""event...","{\n ""needs_revision"": false,\n ""issues_ident...",Frank 敦促 Andy 立即为测验复习，但 Andy 拒绝并计划明天再学。面对 Fran...,Frank tries to encourage Andy to learn for the...,弗兰克试图激励安迪，为明天的测验学习。
4,gold_00005,123,Crystal: <file_photo>\r\nIrene: He's so big!\r...,"{\n ""participants"": [\n ""Crystal"",\n ""I...","{\n ""selected_events"": [\n {\n ""event...","{\n ""needs_revision"": false,\n ""issues_ident...",Crystal 表示儿子衣服穿不下了，Irene 主动提出带他去买新衣服，尽管 Crysta...,Irene will take Crystal's son shopping for clo...,艾琳会带克里斯特尔的儿子去买衣服。